//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/AnimalNPC.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `DeathUpdate`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:97-148`
pub fn DeathUpdate(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port DeathUpdate — oracle/oracle/codemp/game/AnimalNPC.c:97")
}

/// Raven `Update`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:151-154`
pub fn Update(
    pVeh: *mut Vehicle_t,
    pUcmd: *const usercmd_t,
) -> qboolean {
    todo!("Port Update — oracle/oracle/codemp/game/AnimalNPC.c:151")
}

/// Raven `ProcessMoveCommands`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:168-329`
pub fn ProcessMoveCommands(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port ProcessMoveCommands — oracle/oracle/codemp/game/AnimalNPC.c:168")
}

/// Raven `ProcessOrientCommands`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:338-464`
pub fn ProcessOrientCommands(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port ProcessOrientCommands — oracle/oracle/codemp/game/AnimalNPC.c:338")
}

/// Raven `AnimalProcessOri`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:467-470`
pub fn AnimalProcessOri(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port AnimalProcessOri — oracle/oracle/codemp/game/AnimalNPC.c:467")
}

/// Raven `AnimateVehicle`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:474-615`
pub fn AnimateVehicle(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port AnimateVehicle — oracle/oracle/codemp/game/AnimalNPC.c:474")
}

/// Raven `AnimateRiders`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:620-849`
pub fn AnimateRiders(
    pVeh: *mut Vehicle_t,
) {
    todo!("Port AnimateRiders — oracle/oracle/codemp/game/AnimalNPC.c:620")
}

/// Raven `G_SetAnimalVehicleFunctions`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:857-887`
pub fn G_SetAnimalVehicleFunctions(
    pVehInfo: *mut vehicleInfo_t,
) {
    todo!("Port G_SetAnimalVehicleFunctions — oracle/oracle/codemp/game/AnimalNPC.c:857")
}

/// Raven `G_CreateAnimalNPC`.
///
/// Source: `oracle/oracle/codemp/game/AnimalNPC.c:904-925`
pub fn G_CreateAnimalNPC(
    pVeh: *mut *mut Vehicle_t,
    strAnimalType: *const c_char,
) {
    todo!("Port G_CreateAnimalNPC — oracle/oracle/codemp/game/AnimalNPC.c:904")
}
