//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/bg_g2_utils.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `BG_AttachToRancor`.
///
/// Source: `oracle/oracle/codemp/game/bg_g2_utils.c:25-98`
pub fn BG_AttachToRancor(
    ghoul2: *mut c_void,
    rancYaw: f32,
    rancOrigin: vec3_t,
    time: c_int,
    modelList: *mut qhandle_t,
    modelScale: vec3_t,
    inMouth: qboolean,
    out_origin: vec3_t,
    out_angles: vec3_t,
    out_axis: *mut vec3_t,
) {
    todo!("Port BG_AttachToRancor — oracle/oracle/codemp/game/bg_g2_utils.c:25")
}

/// Raven `BG_GetRootSurfNameWithVariant`.
///
/// Source: `oracle/oracle/codemp/game/bg_g2_utils.c:101-122`
pub fn BG_GetRootSurfNameWithVariant(
    ghoul2: *mut c_void,
    rootSurfName: *const c_char,
    returnSurfName: *mut c_char,
    returnSize: c_int,
) -> qboolean {
    todo!("Port BG_GetRootSurfNameWithVariant — oracle/oracle/codemp/game/bg_g2_utils.c:101")
}
