// PORT-COMPLETE: bg_saber.c 11/33
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/bg_saber.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
//!
//! Nearly every function in this file reads/writes the file-static Raven
//! `pmove_t *pm` working set (`pm->ps`, `pm->cmd`, `pm->animations`, …). Per
//! the precedent already established in `bg_pmove.rs`/`w_saber.rs`, the
//! representation of that working set (how a no-arg C signature threads it
//! without a porting-rules §B3 static) is a genuine unsettled design fork —
//! every such function here is parked with `PORT-ESCALATION(pmove-working-state)`.
//! Likewise `saberMoveData`/`transitionMove`/`saberMoveTransitionAngle` (the
//! ~90-entry move-data const tables) are not yet ported into the Rust tree —
//! functions that need them are parked with
//! `PORT-ESCALATION(saber-move-data-table)`. Functions that read the bare
//! `g_entities` global with no world/entity-arena handle in scope are parked
//! with `PORT-ESCALATION(raw-ptr-skeleton-no-world-handle)`, matching
//! `g_combat.rs`. The clean, pointer/value-parameterized pure functions below
//! are ported.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

use mp_bg::public::saber_move_name::{
    LS_A_BL2TR, LS_A_BR2TL, LS_A_L2R, LS_A_R2L, LS_A_T2B, LS_A_TL2BR, LS_A_TR2BL, LS_H1_BL,
    LS_H1_BR, LS_H1_B_, LS_H1_T_, LS_H1_TL, LS_H1_TR, LS_NONE, LS_PARRY_LL, LS_PARRY_LR,
    LS_PARRY_UL, LS_PARRY_UP, LS_PARRY_UR, LS_READY, LS_V1_BL, LS_V1_BR, LS_V1_B_, LS_V1__L,
    LS_V1__R, LS_V1_T_, LS_V1_TL, LS_V1_TR, LS_B1_BL, LS_B1_BR, LS_D1_BL, LS_D1_BR,
};
use mp_bg::public::saber_quadrant::saberQuadrant_t;
use mp_bg::public::anim_number::animNumber_t;
use mp_bg::public::saberlock::SABERLOCK_WIN;

// Raven `qboolean` is `c_int` (`qfalse == 0`, `qtrue == 1`); the lowercase
// `qtrue`/`qfalse` spellings are not exported here (see `w_saber.rs`), so the
// ported bodies below return the bare `1`/`0` those constants alias.

/// Raven `PM_irand_timesync`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:10-25`
// PORT-ESCALATION(pmove-working-state): reads the file-static `pmove_t *pm`
// (`pm->cmd.serverTime`) with no world/pmove handle in the skeleton signature.
pub fn PM_irand_timesync(
    val1: c_int,
    val2: c_int,
) -> c_int {
    todo!("Port PM_irand_timesync — parked: pmove-working-state")
}

/// Raven `BG_ForcePowerDrain`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:27-100`
// PORT-ESCALATION(unported-global-table): needs the `forcePowerNeeded[level][power]`
// const table (bg_local.h), not yet ported into the Rust tree.
pub fn BG_ForcePowerDrain(
    ps: *mut playerState_t,
    forcePower: forcePowers_t,
    overrideAmt: c_int,
) {
    todo!("Port BG_ForcePowerDrain — parked: unported-global-table (forcePowerNeeded)")
}

/// Raven `BG_EnoughForcePowerForMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:102-111`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps->fd.forcePower` and
// calls `PM_AddEvent`, both against the file-static `pm` working set.
pub fn BG_EnoughForcePowerForMove(
    cost: c_int,
) -> qboolean {
    todo!("Port BG_EnoughForcePowerForMove — parked: pmove-working-state")
}

/// Raven `PM_AttackMoveForQuad`.
///
/// Raven: maps a saber quadrant to the "instant attack" saber move that
/// starts from that quadrant.
/// Source: `oracle/oracle/codemp/game/bg_saber.c:392-420`
pub fn PM_AttackMoveForQuad(
    quad: c_int,
) -> saberMoveName_t {
    if quad == saberQuadrant_t::Q_B as c_int || quad == saberQuadrant_t::Q_BR as c_int {
        return LS_A_BR2TL;
    }
    if quad == saberQuadrant_t::Q_R as c_int {
        return LS_A_R2L;
    }
    if quad == saberQuadrant_t::Q_TR as c_int {
        return LS_A_TR2BL;
    }
    if quad == saberQuadrant_t::Q_T as c_int {
        return LS_A_T2B;
    }
    if quad == saberQuadrant_t::Q_TL as c_int {
        return LS_A_TL2BR;
    }
    if quad == saberQuadrant_t::Q_L as c_int {
        return LS_A_L2R;
    }
    if quad == saberQuadrant_t::Q_BL as c_int {
        return LS_A_BL2TR;
    }
    LS_NONE
}

/// Raven `PM_SaberAnimTransitionAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:424-581`
// PORT-ESCALATION(saber-move-data-table): needs the `saberMoveData`/
// `transitionMove` const tables (not yet ported) and calls `PM_SaberKataDone`,
// itself parked on `pmove-working-state`.
pub fn PM_SaberAnimTransitionAnim(
    curmove: c_int,
    newmove: c_int,
) -> c_int {
    todo!("Port PM_SaberAnimTransitionAnim — parked: saber-move-data-table")
}

/// Raven `PM_CheckStabDown`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:584-648`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps`, `pm->cmd`,
// `pm->trace` against the file-static `pm` working set.
pub fn PM_CheckStabDown() -> saberMoveName_t {
    todo!("Port PM_CheckStabDown — parked: pmove-working-state")
}

/// Raven `PM_SaberMoveQuadrantForMovement`.
///
/// Raven: picks the attack quadrant implied by the player's forward/right
/// movement command.
/// Source: `oracle/oracle/codemp/game/bg_saber.c:650-697`
pub fn PM_SaberMoveQuadrantForMovement(
    ucmd: *mut usercmd_t,
) -> c_int {
    unsafe {
        let rightmove = (*ucmd).rightmove;
        let forwardmove = (*ucmd).forwardmove;
        if rightmove > 0 {
            //moving right
            if forwardmove > 0 {
                //forward right = TL2BR slash
                saberQuadrant_t::Q_TL as c_int
            } else if forwardmove < 0 {
                //backward right = BL2TR uppercut
                saberQuadrant_t::Q_BL as c_int
            } else {
                //just right is a left slice
                saberQuadrant_t::Q_L as c_int
            }
        } else if rightmove < 0 {
            //moving left
            if forwardmove > 0 {
                //forward left = TR2BL slash
                saberQuadrant_t::Q_TR as c_int
            } else if forwardmove < 0 {
                //backward left = BR2TL uppercut
                saberQuadrant_t::Q_BR as c_int
            } else {
                //just left is a right slice
                saberQuadrant_t::Q_R as c_int
            }
        } else {
            //not moving left or right
            if forwardmove > 0 {
                //forward= T2B slash
                saberQuadrant_t::Q_T as c_int
            } else if forwardmove < 0 {
                //backward= T2B slash //or B2T uppercut?
                saberQuadrant_t::Q_T as c_int
            } else {
                //Not moving at all
                saberQuadrant_t::Q_R as c_int
            }
        }
    }
}

/// Raven `PM_SaberInBounce`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:700-711`
pub fn PM_SaberInBounce(
    r#move: c_int,
) -> qboolean {
    if r#move >= LS_B1_BR && r#move <= LS_B1_BL {
        return 1;
    }
    if r#move >= LS_D1_BR && r#move <= LS_D1_BL {
        return 1;
    }
    0
}

/// Raven `PM_SaberAttackChainAngle`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:783-790`
// PORT-ESCALATION(saber-move-data-table): needs the `saberMoveData`/
// `saberMoveTransitionAngle` const tables, not yet ported.
pub fn PM_SaberAttackChainAngle(
    move1: c_int,
    move2: c_int,
) -> c_int {
    todo!("Port PM_SaberAttackChainAngle — parked: saber-move-data-table")
}

/// Raven `PM_SaberKataDone`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:792-884`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps->m_iVehicleNum`,
// `pm->ps->fd.saberAnimLevel`, `pm->ps->saberAttackChainCount` against the
// file-static `pm` working set.
pub fn PM_SaberKataDone(
    curmove: c_int,
    newmove: c_int,
) -> qboolean {
    todo!("Port PM_SaberKataDone — parked: pmove-working-state")
}

/// Raven `PM_SetAnimFrame`.
///
/// Raven: `torso`/`legs` params are unused in the compiled body (only the
/// saber-lock frame is ever set here).
/// Source: `oracle/oracle/codemp/game/bg_saber.c:886-889`
pub fn PM_SetAnimFrame(
    gent: *mut playerState_t,
    frame: c_int,
    torso: qboolean,
    legs: qboolean,
) {
    unsafe {
        (*gent).saberLockFrame = frame;
    }
}

/// Raven `PM_SaberLockWinAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:891-983`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps->torsoAnim`,
// `pm->ps->saberMove`, etc. and calls the unresolved `PM_SetAnim`, all against
// the file-static `pm` working set.
pub fn PM_SaberLockWinAnim(
    victory: qboolean,
    superBreak: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockWinAnim — parked: pmove-working-state")
}

/// Raven `PM_SaberLockLoseAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1000-1126`
// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the `#ifdef QAGAME` branch
// calls `NPC_SetAnim(&g_entities[genemy->clientNum], ...)` against the bare
// `g_entities` global with no world/entity-arena handle in the skeleton
// signature (rulings item 1: `g_entities` lives on the world, not a static).
pub fn PM_SaberLockLoseAnim(
    genemy: *mut playerState_t,
    victory: qboolean,
    superBreak: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockLoseAnim — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `PM_SaberLockResultAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1128-1232`
// PORT-ESCALATION(pmove-working-state): compares `duelist->clientNum` against
// `pm->ps->clientNum` and calls the unresolved `PM_SetAnim`/`NPC_SetAnim`
// (`g_entities`) branches, against the file-static `pm` working set.
pub fn PM_SaberLockResultAnim(
    duelist: *mut playerState_t,
    superBreak: qboolean,
    won: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockResultAnim — parked: pmove-working-state")
}

/// Raven `PM_SaberLockBreak`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1234-1340`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps` throughout
// against the file-static `pm` working set.
pub fn PM_SaberLockBreak(
    genemy: *mut playerState_t,
    victory: qboolean,
    strength: c_int,
) {
    todo!("Port PM_SaberLockBreak — parked: pmove-working-state")
}

/// Raven `BG_CheckIncrementLockAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1342-1398`
pub fn BG_CheckIncrementLockAnim(
    anim: c_int,
    winOrLose: c_int,
) -> qboolean {
    let mut increment: qboolean = 0; // qfalse //???
    // RULE: if you are the first style in the lock anim, you advance from LOSING position to WINNING position
    //       if you are the second style in the lock anim, you advance from WINNING position to LOSING position

    // increment to win:
    const INCREMENT_TO_WIN: &[animNumber_t] = &[
        animNumber_t::BOTH_LK_DL_DL_S_L_1, //lock if I'm using dual vs. dual and I initiated
        animNumber_t::BOTH_LK_DL_DL_S_L_2, //lock if I'm using dual vs. dual and other initiated
        animNumber_t::BOTH_LK_DL_DL_T_L_1, //lock if I'm using dual vs. dual and I initiated
        animNumber_t::BOTH_LK_DL_DL_T_L_2, //lock if I'm using dual vs. dual and other initiated
        animNumber_t::BOTH_LK_DL_S_S_L_1,  //lock if I'm using dual vs. a single
        animNumber_t::BOTH_LK_DL_S_T_L_1,  //lock if I'm using dual vs. a single
        animNumber_t::BOTH_LK_DL_ST_S_L_1, //lock if I'm using dual vs. a staff
        animNumber_t::BOTH_LK_DL_ST_T_L_1, //lock if I'm using dual vs. a staff
        animNumber_t::BOTH_LK_S_S_S_L_1,   //lock if I'm using single vs. a single and I initiated
        animNumber_t::BOTH_LK_S_S_T_L_2, //lock if I'm using single vs. a single and other initiated
        animNumber_t::BOTH_LK_ST_S_S_L_1, //lock if I'm using staff vs. a single
        animNumber_t::BOTH_LK_ST_S_T_L_1, //lock if I'm using staff vs. a single
        animNumber_t::BOTH_LK_ST_ST_T_L_1, //lock if I'm using staff vs. a staff and I initiated
        animNumber_t::BOTH_LK_ST_ST_T_L_2, //lock if I'm using staff vs. a staff and other initiated
    ];

    // decrement to win:
    const DECREMENT_TO_WIN: &[animNumber_t] = &[
        animNumber_t::BOTH_LK_S_DL_S_L_1, //lock if I'm using single vs. a dual
        animNumber_t::BOTH_LK_S_DL_T_L_1, //lock if I'm using single vs. a dual
        animNumber_t::BOTH_LK_S_S_S_L_2, //lock if I'm using single vs. a single and other intitiated
        animNumber_t::BOTH_LK_S_S_T_L_1, //lock if I'm using single vs. a single and I initiated
        animNumber_t::BOTH_LK_S_ST_S_L_1, //lock if I'm using single vs. a staff
        animNumber_t::BOTH_LK_S_ST_T_L_1, //lock if I'm using single vs. a staff
        animNumber_t::BOTH_LK_ST_DL_S_L_1, //lock if I'm using staff vs. dual
        animNumber_t::BOTH_LK_ST_DL_T_L_1, //lock if I'm using staff vs. dual
        animNumber_t::BOTH_LK_ST_ST_S_L_1, //lock if I'm using staff vs. a staff and I initiated
        animNumber_t::BOTH_LK_ST_ST_S_L_2, //lock if I'm using staff vs. a staff and other initiated
    ];

    if INCREMENT_TO_WIN.iter().any(|&a| a as c_int == anim) {
        increment = if winOrLose == SABERLOCK_WIN { 1 } else { 0 };
    } else if DECREMENT_TO_WIN.iter().any(|&a| a as c_int == anim) {
        increment = if winOrLose == SABERLOCK_WIN { 0 } else { 1 };
    }
    increment
}

/// Raven `PM_SaberLocked`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1401-1581`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps`, `pm->animations`
// throughout against the file-static `pm` working set.
pub fn PM_SaberLocked() {
    todo!("Port PM_SaberLocked — parked: pmove-working-state")
}

/// Raven `PM_SaberInBrokenParry`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1583-1594`
pub fn PM_SaberInBrokenParry(
    r#move: c_int,
) -> qboolean {
    if r#move >= LS_V1_BR && r#move <= LS_V1_B_ {
        return 1;
    }
    if r#move >= LS_H1_T_ && r#move <= LS_H1_BL {
        return 1;
    }
    0
}

/// Raven `PM_BrokenParryForParry`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1597-1621`
pub fn PM_BrokenParryForParry(
    r#move: c_int,
) -> c_int {
    if r#move == LS_PARRY_UP {
        return LS_H1_T_;
    }
    if r#move == LS_PARRY_UR {
        return LS_H1_TR;
    }
    if r#move == LS_PARRY_UL {
        return LS_H1_TL;
    }
    if r#move == LS_PARRY_LR {
        return LS_H1_BL;
    }
    if r#move == LS_PARRY_LL {
        return LS_H1_BR;
    }
    if r#move == LS_READY {
        return LS_H1_B_;
    }
    LS_NONE
}

/// Raven `PM_CanBackstab`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1625-1655`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps`/`pm->trace` against the
// file-static `pm` working set.
pub fn PM_CanBackstab() -> qboolean {
    todo!("Port PM_CanBackstab — parked: pmove-working-state")
}

/// Raven `PM_SaberFlipOverAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1657-1753`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps`/`pm->cmd`
// against the file-static `pm` working set.
pub fn PM_SaberFlipOverAttackMove() -> saberMoveName_t {
    todo!("Port PM_SaberFlipOverAttackMove — parked: pmove-working-state")
}

/// Raven `PM_SaberBackflipAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1755-1791`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps` against the
// file-static `pm` working set.
pub fn PM_SaberBackflipAttackMove() -> c_int {
    todo!("Port PM_SaberBackflipAttackMove — parked: pmove-working-state")
}

/// Raven `PM_SaberDualJumpAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1793-1800`
// PORT-ESCALATION(pmove-working-state): writes `pm->ps` against the
// file-static `pm` working set.
pub fn PM_SaberDualJumpAttackMove() -> c_int {
    todo!("Port PM_SaberDualJumpAttackMove — parked: pmove-working-state")
}

/// Raven `PM_SomeoneInFront`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1804-1833`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_SomeoneInFront(
    tr: *mut trace_t,
) -> qboolean {
    todo!("Port PM_SomeoneInFront — parked: pmove-working-state")
}

/// Raven `PM_SaberLungeAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1835-1889`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps`/`pm->cmd` against the
// file-static `pm` working set.
pub fn PM_SaberLungeAttackMove(
    noSpecials: qboolean,
) -> saberMoveName_t {
    todo!("Port PM_SaberLungeAttackMove — parked: pmove-working-state")
}

/// Raven `PM_SaberJumpAttackMove2`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1891-1945`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_SaberJumpAttackMove2() -> saberMoveName_t {
    todo!("Port PM_SaberJumpAttackMove2 — parked: pmove-working-state")
}

/// Raven `PM_SaberJumpAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1947-1993`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps` against the
// file-static `pm` working set.
pub fn PM_SaberJumpAttackMove() -> saberMoveName_t {
    todo!("Port PM_SaberJumpAttackMove — parked: pmove-working-state")
}

/// Raven `PM_GroundDistance`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1995-2009`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps`/`pm->trace` against the
// file-static `pm` working set.
pub fn PM_GroundDistance() -> f32 {
    todo!("Port PM_GroundDistance — parked: pmove-working-state")
}

/// Raven `PM_WalkableGroundDistance`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2011-2030`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps`/`pm->trace` against the
// file-static `pm` working set.
pub fn PM_WalkableGroundDistance() -> f32 {
    todo!("Port PM_WalkableGroundDistance — parked: pmove-working-state")
}

/// Raven `PM_CanDoDualDoubleAttacks`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2033-2056`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_CanDoDualDoubleAttacks() -> qboolean {
    todo!("Port PM_CanDoDualDoubleAttacks — parked: pmove-working-state")
}

/// Raven `PM_CheckEnemyPresence`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2058-2110`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps`/`pm->trace` against the
// file-static `pm` working set.
pub fn PM_CheckEnemyPresence(
    dir: c_int,
    radius: f32,
) -> qboolean {
    todo!("Port PM_CheckEnemyPresence — parked: pmove-working-state")
}

/// Raven `PM_CheckPullAttack`.
///
/// Raven: the entire body is `#if 0`-disabled ("disabling these for MP, they
/// aren't useful") — the compiled function is unconditionally `return LS_NONE;`.
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2117-2226`
pub fn PM_CheckPullAttack() -> saberMoveName_t {
    LS_NONE
}

/// Raven `PM_InSecondaryStyle`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2228-2239`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps->fd` against the
// file-static `pm` working set.
pub fn PM_InSecondaryStyle() -> qboolean {
    todo!("Port PM_InSecondaryStyle — parked: pmove-working-state")
}

/// Raven `PM_SaberAttackForMovement`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2241-2618`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps`/`pm->cmd`
// throughout and needs the `saberMoveData` const table (also
// `saber-move-data-table`), against the file-static `pm` working set.
pub fn PM_SaberAttackForMovement(
    curmove: saberMoveName_t,
) -> saberMoveName_t {
    todo!("Port PM_SaberAttackForMovement — parked: pmove-working-state, saber-move-data-table")
}

/// Raven `PM_KickMoveForConditions`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2620-2691`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps` against the
// file-static `pm` working set.
pub fn PM_KickMoveForConditions() -> c_int {
    todo!("Port PM_KickMoveForConditions — parked: pmove-working-state")
}

/// Raven `PM_SaberMoveOkayForKata`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2696-2707`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps->saberMove` against the
// file-static `pm` working set.
pub fn PM_SaberMoveOkayForKata() -> qboolean {
    todo!("Port PM_SaberMoveOkayForKata — parked: pmove-working-state")
}

/// Raven `PM_CanDoKata`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2709-2748`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_CanDoKata() -> qboolean {
    todo!("Port PM_CanDoKata — parked: pmove-working-state")
}

/// Raven `PM_CheckAltKickAttack`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2750-2775`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_CheckAltKickAttack() -> qboolean {
    todo!("Port PM_CheckAltKickAttack — parked: pmove-working-state")
}

/// Raven `PM_SaberPowerCheck`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2785-2800`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps->fd` and needs the
// unported `forcePowerNeeded` table, against the file-static `pm` working set.
pub fn PM_SaberPowerCheck() -> qboolean {
    todo!("Port PM_SaberPowerCheck — parked: pmove-working-state")
}

/// Raven `PM_CanDoRollStab`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2802-2820`
// PORT-ESCALATION(pmove-working-state): reads `pm->ps` against the
// file-static `pm` working set.
pub fn PM_CanDoRollStab() -> qboolean {
    todo!("Port PM_CanDoRollStab — parked: pmove-working-state")
}

/// Raven `PM_WeaponLightsaber`.
///
/// Raven: the main per-frame saber weapon state machine (965 LOC) — reads and
/// writes almost every field of `pm->ps` and the `saberMoveData`/
/// `transitionMove`/`weaponData`/`bg_parryDebounce` const tables.
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2836-3800`
// PORT-ESCALATION(pmove-working-state): the entire body is built on the
// file-static `pm`/`pml` working set (see module doc); also needs
// `saber-move-data-table`. Parked whole — porting piecemeal without the
// working-set decision would require inventing an ad-hoc shape.
pub fn PM_WeaponLightsaber() {
    todo!("Port PM_WeaponLightsaber — parked: pmove-working-state, saber-move-data-table")
}

/// Raven `PM_SetSaberMove`.
///
/// Raven: applies a chosen saber move to `pm->ps` (anim, timers, flags) —
/// 297 LOC, reads the `saberMoveData` const table throughout.
/// Source: `oracle/oracle/codemp/game/bg_saber.c:3802-4098`
// PORT-ESCALATION(pmove-working-state): reads/writes `pm->ps` throughout and
// needs `saberMoveData` (also `saber-move-data-table`), against the
// file-static `pm` working set.
pub fn PM_SetSaberMove(
    newMove: c_short,
) {
    todo!("Port PM_SetSaberMove — parked: pmove-working-state, saber-move-data-table")
}

/// Raven `BG_MySaber`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:4100-4141`
// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads the bare
// `g_entities` global with no world/entity-arena handle in the skeleton
// signature (rulings item 1: `g_entities` lives on the world, not a static).
pub fn BG_MySaber(
    clientNum: c_int,
    saberNum: c_int,
) -> *mut saberInfo_t {
    todo!("Port BG_MySaber — parked: raw-ptr-skeleton-no-world-handle")
}
