//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/bg_saber.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `PM_irand_timesync`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:10-25`
pub fn PM_irand_timesync(
    val1: c_int,
    val2: c_int,
) -> c_int {
    todo!("Port PM_irand_timesync — oracle/oracle/codemp/game/bg_saber.c:10")
}

/// Raven `BG_ForcePowerDrain`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:27-100`
pub fn BG_ForcePowerDrain(
    ps: *mut playerState_t,
    forcePower: forcePowers_t,
    overrideAmt: c_int,
) {
    todo!("Port BG_ForcePowerDrain — oracle/oracle/codemp/game/bg_saber.c:27")
}

/// Raven `BG_EnoughForcePowerForMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:102-111`
pub fn BG_EnoughForcePowerForMove(
    cost: c_int,
) -> qboolean {
    todo!("Port BG_EnoughForcePowerForMove — oracle/oracle/codemp/game/bg_saber.c:102")
}

/// Raven `PM_AttackMoveForQuad`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:392-420`
pub fn PM_AttackMoveForQuad(
    quad: c_int,
) -> saberMoveName_t {
    todo!("Port PM_AttackMoveForQuad — oracle/oracle/codemp/game/bg_saber.c:392")
}

/// Raven `PM_SaberAnimTransitionAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:424-581`
pub fn PM_SaberAnimTransitionAnim(
    curmove: c_int,
    newmove: c_int,
) -> c_int {
    todo!("Port PM_SaberAnimTransitionAnim — oracle/oracle/codemp/game/bg_saber.c:424")
}

/// Raven `PM_CheckStabDown`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:584-648`
pub fn PM_CheckStabDown() -> saberMoveName_t {
    todo!("Port PM_CheckStabDown — oracle/oracle/codemp/game/bg_saber.c:584")
}

/// Raven `PM_SaberMoveQuadrantForMovement`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:650-697`
pub fn PM_SaberMoveQuadrantForMovement(
    ucmd: *mut usercmd_t,
) -> c_int {
    todo!("Port PM_SaberMoveQuadrantForMovement — oracle/oracle/codemp/game/bg_saber.c:650")
}

/// Raven `PM_SaberInBounce`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:700-711`
pub fn PM_SaberInBounce(
    r#move: c_int,
) -> qboolean {
    todo!("Port PM_SaberInBounce — oracle/oracle/codemp/game/bg_saber.c:700")
}

/// Raven `PM_SaberAttackChainAngle`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:783-790`
pub fn PM_SaberAttackChainAngle(
    move1: c_int,
    move2: c_int,
) -> c_int {
    todo!("Port PM_SaberAttackChainAngle — oracle/oracle/codemp/game/bg_saber.c:783")
}

/// Raven `PM_SaberKataDone`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:792-884`
pub fn PM_SaberKataDone(
    curmove: c_int,
    newmove: c_int,
) -> qboolean {
    todo!("Port PM_SaberKataDone — oracle/oracle/codemp/game/bg_saber.c:792")
}

/// Raven `PM_SetAnimFrame`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:886-889`
pub fn PM_SetAnimFrame(
    gent: *mut playerState_t,
    frame: c_int,
    torso: qboolean,
    legs: qboolean,
) {
    todo!("Port PM_SetAnimFrame — oracle/oracle/codemp/game/bg_saber.c:886")
}

/// Raven `PM_SaberLockWinAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:891-983`
pub fn PM_SaberLockWinAnim(
    victory: qboolean,
    superBreak: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockWinAnim — oracle/oracle/codemp/game/bg_saber.c:891")
}

/// Raven `PM_SaberLockLoseAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1000-1126`
pub fn PM_SaberLockLoseAnim(
    genemy: *mut playerState_t,
    victory: qboolean,
    superBreak: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockLoseAnim — oracle/oracle/codemp/game/bg_saber.c:1000")
}

/// Raven `PM_SaberLockResultAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1128-1232`
pub fn PM_SaberLockResultAnim(
    duelist: *mut playerState_t,
    superBreak: qboolean,
    won: qboolean,
) -> c_int {
    todo!("Port PM_SaberLockResultAnim — oracle/oracle/codemp/game/bg_saber.c:1128")
}

/// Raven `PM_SaberLockBreak`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1234-1340`
pub fn PM_SaberLockBreak(
    genemy: *mut playerState_t,
    victory: qboolean,
    strength: c_int,
) {
    todo!("Port PM_SaberLockBreak — oracle/oracle/codemp/game/bg_saber.c:1234")
}

/// Raven `BG_CheckIncrementLockAnim`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1342-1398`
pub fn BG_CheckIncrementLockAnim(
    anim: c_int,
    winOrLose: c_int,
) -> qboolean {
    todo!("Port BG_CheckIncrementLockAnim — oracle/oracle/codemp/game/bg_saber.c:1342")
}

/// Raven `PM_SaberLocked`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1401-1581`
pub fn PM_SaberLocked() {
    todo!("Port PM_SaberLocked — oracle/oracle/codemp/game/bg_saber.c:1401")
}

/// Raven `PM_SaberInBrokenParry`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1583-1594`
pub fn PM_SaberInBrokenParry(
    r#move: c_int,
) -> qboolean {
    todo!("Port PM_SaberInBrokenParry — oracle/oracle/codemp/game/bg_saber.c:1583")
}

/// Raven `PM_BrokenParryForParry`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1597-1621`
pub fn PM_BrokenParryForParry(
    r#move: c_int,
) -> c_int {
    todo!("Port PM_BrokenParryForParry — oracle/oracle/codemp/game/bg_saber.c:1597")
}

/// Raven `PM_CanBackstab`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1625-1655`
pub fn PM_CanBackstab() -> qboolean {
    todo!("Port PM_CanBackstab — oracle/oracle/codemp/game/bg_saber.c:1625")
}

/// Raven `PM_SaberFlipOverAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1657-1753`
pub fn PM_SaberFlipOverAttackMove() -> saberMoveName_t {
    todo!("Port PM_SaberFlipOverAttackMove — oracle/oracle/codemp/game/bg_saber.c:1657")
}

/// Raven `PM_SaberBackflipAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1755-1791`
pub fn PM_SaberBackflipAttackMove() -> c_int {
    todo!("Port PM_SaberBackflipAttackMove — oracle/oracle/codemp/game/bg_saber.c:1755")
}

/// Raven `PM_SaberDualJumpAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1793-1800`
pub fn PM_SaberDualJumpAttackMove() -> c_int {
    todo!("Port PM_SaberDualJumpAttackMove — oracle/oracle/codemp/game/bg_saber.c:1793")
}

/// Raven `PM_SomeoneInFront`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1804-1833`
pub fn PM_SomeoneInFront(
    tr: *mut trace_t,
) -> qboolean {
    todo!("Port PM_SomeoneInFront — oracle/oracle/codemp/game/bg_saber.c:1804")
}

/// Raven `PM_SaberLungeAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1835-1889`
pub fn PM_SaberLungeAttackMove(
    noSpecials: qboolean,
) -> saberMoveName_t {
    todo!("Port PM_SaberLungeAttackMove — oracle/oracle/codemp/game/bg_saber.c:1835")
}

/// Raven `PM_SaberJumpAttackMove2`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1891-1945`
pub fn PM_SaberJumpAttackMove2() -> saberMoveName_t {
    todo!("Port PM_SaberJumpAttackMove2 — oracle/oracle/codemp/game/bg_saber.c:1891")
}

/// Raven `PM_SaberJumpAttackMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1947-1993`
pub fn PM_SaberJumpAttackMove() -> saberMoveName_t {
    todo!("Port PM_SaberJumpAttackMove — oracle/oracle/codemp/game/bg_saber.c:1947")
}

/// Raven `PM_GroundDistance`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:1995-2009`
pub fn PM_GroundDistance() -> f32 {
    todo!("Port PM_GroundDistance — oracle/oracle/codemp/game/bg_saber.c:1995")
}

/// Raven `PM_WalkableGroundDistance`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2011-2030`
pub fn PM_WalkableGroundDistance() -> f32 {
    todo!("Port PM_WalkableGroundDistance — oracle/oracle/codemp/game/bg_saber.c:2011")
}

/// Raven `PM_CanDoDualDoubleAttacks`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2033-2056`
pub fn PM_CanDoDualDoubleAttacks() -> qboolean {
    todo!("Port PM_CanDoDualDoubleAttacks — oracle/oracle/codemp/game/bg_saber.c:2033")
}

/// Raven `PM_CheckEnemyPresence`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2058-2110`
pub fn PM_CheckEnemyPresence(
    dir: c_int,
    radius: f32,
) -> qboolean {
    todo!("Port PM_CheckEnemyPresence — oracle/oracle/codemp/game/bg_saber.c:2058")
}

/// Raven `PM_CheckPullAttack`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2117-2226`
pub fn PM_CheckPullAttack() -> saberMoveName_t {
    todo!("Port PM_CheckPullAttack — oracle/oracle/codemp/game/bg_saber.c:2117")
}

/// Raven `PM_InSecondaryStyle`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2228-2239`
pub fn PM_InSecondaryStyle() -> qboolean {
    todo!("Port PM_InSecondaryStyle — oracle/oracle/codemp/game/bg_saber.c:2228")
}

/// Raven `PM_SaberAttackForMovement`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2241-2618`
pub fn PM_SaberAttackForMovement(
    curmove: saberMoveName_t,
) -> saberMoveName_t {
    todo!("Port PM_SaberAttackForMovement — oracle/oracle/codemp/game/bg_saber.c:2241")
}

/// Raven `PM_KickMoveForConditions`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2620-2691`
pub fn PM_KickMoveForConditions() -> c_int {
    todo!("Port PM_KickMoveForConditions — oracle/oracle/codemp/game/bg_saber.c:2620")
}

/// Raven `PM_SaberMoveOkayForKata`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2696-2707`
pub fn PM_SaberMoveOkayForKata() -> qboolean {
    todo!("Port PM_SaberMoveOkayForKata — oracle/oracle/codemp/game/bg_saber.c:2696")
}

/// Raven `PM_CanDoKata`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2709-2748`
pub fn PM_CanDoKata() -> qboolean {
    todo!("Port PM_CanDoKata — oracle/oracle/codemp/game/bg_saber.c:2709")
}

/// Raven `PM_CheckAltKickAttack`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2750-2775`
pub fn PM_CheckAltKickAttack() -> qboolean {
    todo!("Port PM_CheckAltKickAttack — oracle/oracle/codemp/game/bg_saber.c:2750")
}

/// Raven `PM_SaberPowerCheck`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2785-2800`
pub fn PM_SaberPowerCheck() -> qboolean {
    todo!("Port PM_SaberPowerCheck — oracle/oracle/codemp/game/bg_saber.c:2785")
}

/// Raven `PM_CanDoRollStab`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2802-2820`
pub fn PM_CanDoRollStab() -> qboolean {
    todo!("Port PM_CanDoRollStab — oracle/oracle/codemp/game/bg_saber.c:2802")
}

/// Raven `PM_WeaponLightsaber`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:2836-3800`
pub fn PM_WeaponLightsaber() {
    todo!("Port PM_WeaponLightsaber — oracle/oracle/codemp/game/bg_saber.c:2836")
}

/// Raven `PM_SetSaberMove`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:3802-4098`
pub fn PM_SetSaberMove(
    newMove: c_short,
) {
    todo!("Port PM_SetSaberMove — oracle/oracle/codemp/game/bg_saber.c:3802")
}

/// Raven `BG_MySaber`.
///
/// Source: `oracle/oracle/codemp/game/bg_saber.c:4100-4141`
pub fn BG_MySaber(
    clientNum: c_int,
    saberNum: c_int,
) -> *mut saberInfo_t {
    todo!("Port BG_MySaber — oracle/oracle/codemp/game/bg_saber.c:4100")
}
