// PORT-COMPLETE: g_arenas.c 0/1

//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/g_arenas.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level` (maxclients,
// clients[], numNonSpectatorClients, sortedClients[], teamScores[], time),
// `g_entities`, `g_gametype`, and calls `trap_SendConsoleCommand` — no GameWorld/engine handle.
/// Raven `UpdateTournamentInfo`.
///
/// Source: `oracle/oracle/codemp/game/g_arenas.c:20-101`
pub fn UpdateTournamentInfo(ctx: GameContext<'_>) {
    todo!("Port UpdateTournamentInfo — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_arenas.c:20")
}
