// PORT-COMPLETE: g_client.c 19/27
//! FAITHFUL port of `oracle/oracle/codemp/game/g_client.c` — client functions
//! that don't happen every frame.
//!
//! Generated by `tools/closure-prototype/fnskel.py`, then filled by the
//! jampgame mega-pass (settled fork rulings,
//! `docs/handoffs/jampgame-fork-discovery.md`). STAGING ONLY — not wired into
//! crates/; the tree is not compiled per porter ("Do NOT run cargo").
//!
//! SPINE (fork rulings 1/4 + `docs/architecture/engine-seam.md`, precedent
//! `w_force.rs`): logic fns that reach `level`/cvars/`g_entities`/traps thread
//! the `GameContext<'_>` receiver (`.world: *mut GameWorld`, `.engine`). Globals
//! are `GameWorld` fields (fork 1): `level` → `(*ctx.world).level`, cvars →
//! `(*ctx.world).cvars`, `g_entities[i]` → `(*ctx.world).entities[i]`. Traps go
//! through `trap::X(ctx.engine, <Name>Args::new(…))`. Cross-file callees are
//! invoked with the packet's resolved raw-pointer signatures verbatim (their
//! own porters thread the spine). Raw `gentity_t*`/`gclient_t*` chains are
//! transcribed as `unsafe` raw-pointer field access mirroring the C exactly.
//!
//! Constant spellings the packet does not enumerate (`FL_*`, `DEFAULT_*`,
//! `Q_COLOR_ESCAPE`, …) are transcribed by their faithful Raven names and
//! resolved at integration (same convention as `w_force.rs`).
//!
//! PARKED (see PORT-ESCALATION markers): functions that STORE an entity
//! fn-pointer (`gentity_t.{think,touch,use_,die}` are still raw
//! `extern "C" fn` pointers on the struct, NOT the `EntXxx` enums — the enum
//! dispatch is not yet wired into the layout, so a plain `pub fn` target cannot
//! be assigned faithfully); ghoul2 `trap_G2API_*` users (handle threading +
//! Args constructors not in this packet); the `random()` float-RNG macro
//! (fork 3: threaded LCG, unreachable here); `va(fmt, …)` varargs sites (the
//! resolved `va` drops the C varargs); and the large ghoul2/bg-entangled
//! `Client*`/body-queue functions.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;
use crate::trap;
use crate::world::GameContext;

use mp_abi::game::syscalls::G_ENTITIES_IN_BOX::GEntitiesInBoxArgs;
use mp_qshared::shared::{MAX_GENTITIES, MAX_CLIENTS};

// Raven `qboolean` is `c_int`; keep the source spelling at assignment sites.
// Source: `oracle/oracle/codemp/game/q_shared.h`
const qtrue: qboolean = 1;
const qfalse: qboolean = 0;

/// Raven `playerMins` — the standard player bounding-box mins.
/// Source: `oracle/oracle/codemp/game/g_client.c:9`
static playerMins: vec3_t = [-15.0, -15.0, DEFAULT_MINS_2 as vec_t];
/// Raven `playerMaxs` — the standard player bounding-box maxs.
/// Source: `oracle/oracle/codemp/game/g_client.c:10`
static playerMaxs: vec3_t = [15.0, 15.0, DEFAULT_MAXS_2 as vec_t];

/// `VectorLength` header-inline helper (plain-C branch; the `_XBOX` asm branch
/// is ignored per the packet rider).
/// Source: `oracle/oracle/codemp/game/q_shared.h:1460-1489`
#[inline]
fn VectorLength(v: vec3_t) -> vec_t {
    (v[0] * v[0] + v[1] * v[1] + v[2] * v[2]).sqrt()
}

/// `FOFS(x)` — byte offset of field `x` within `gentity_t` (Raven macro,
/// `g_local.h`). Used as the `fieldofs` argument to `G_Find`.
#[inline]
fn fofs_classname() -> c_int {
    core::mem::offset_of!(gentity_t, classname) as c_int
}

/// Raven `SP_info_player_duel`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:27-39`
pub fn SP_info_player_duel(ent: *mut gentity_t) {
    unsafe {
        let mut i: c_int = 0;

        crate::g_spawn::G_SpawnInt(
            b"nobots\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_BOTS;
        }
        crate::g_spawn::G_SpawnInt(
            b"nohumans\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_HUMANS;
        }
    }
}

/// Raven `SP_info_player_duel1`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:47-59`
pub fn SP_info_player_duel1(ent: *mut gentity_t) {
    unsafe {
        let mut i: c_int = 0;

        crate::g_spawn::G_SpawnInt(
            b"nobots\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_BOTS;
        }
        crate::g_spawn::G_SpawnInt(
            b"nohumans\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_HUMANS;
        }
    }
}

/// Raven `SP_info_player_duel2`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:67-79`
pub fn SP_info_player_duel2(ent: *mut gentity_t) {
    unsafe {
        let mut i: c_int = 0;

        crate::g_spawn::G_SpawnInt(
            b"nobots\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_BOTS;
        }
        crate::g_spawn::G_SpawnInt(
            b"nohumans\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_HUMANS;
        }
    }
}

/// Raven `SP_info_player_deathmatch`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:88-99`
pub fn SP_info_player_deathmatch(ent: *mut gentity_t) {
    unsafe {
        let mut i: c_int = 0;

        crate::g_spawn::G_SpawnInt(
            b"nobots\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_BOTS;
        }
        crate::g_spawn::G_SpawnInt(
            b"nohumans\0".as_ptr() as *const c_char,
            b"0\0".as_ptr() as *const c_char,
            &mut i,
        );
        if i != 0 {
            (*ent).flags |= FL_NO_HUMANS;
        }
    }
}

/// Raven `SP_info_player_start` — equivalent to `info_player_deathmatch`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:105-108`
pub fn SP_info_player_start(ent: *mut gentity_t) {
    unsafe {
        (*ent).classname = b"info_player_deathmatch\0".as_ptr() as *const c_char;
        SP_info_player_deathmatch(ent);
    }
}

/// Raven `SP_info_player_start_red` — Red Team DM start.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:121-123`
pub fn SP_info_player_start_red(ent: *mut gentity_t) {
    SP_info_player_deathmatch(ent);
}

/// Raven `SP_info_player_start_blue` — Blue Team DM start.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:136-138`
pub fn SP_info_player_start_blue(ent: *mut gentity_t) {
    SP_info_player_deathmatch(ent);
}

/// Raven `SiegePointUse` — toggle the siege spawn point on/off.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:140-151`
pub fn SiegePointUse(self_: *mut gentity_t, other: *mut gentity_t, activator: *mut gentity_t) {
    unsafe {
        // Toggle the point on/off
        if (*self_).genericValue1 != 0 {
            (*self_).genericValue1 = 0;
        } else {
            (*self_).genericValue1 = 1;
        }
    }
}

/// Raven `SP_info_player_siegeteam1` — siege start point, team1.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:164-187`
// PORT-ESCALATION(fn-ptr-store-shape-mismatch): stores `ent->use = SiegePointUse`,
// but `gentity_t.use_` is still a raw `extern "C" fn` pointer (not the `EntUse`
// enum) and the target is a plain `pub fn` — cannot assign faithfully until the
// fn-ID enum dispatch (ruling 2) is wired into the struct layout. Also reads
// `g_gametype`.
pub fn SP_info_player_siegeteam1(ent: *mut gentity_t) {
    todo!("Port SP_info_player_siegeteam1 — parked: fn-ptr-store-shape-mismatch")
}

/// Raven `SP_info_player_siegeteam2` — siege start point, team2.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:200-223`
// PORT-ESCALATION(fn-ptr-store-shape-mismatch): stores `ent->use = SiegePointUse`
// into the still-raw `gentity_t.use_` fn pointer (see siegeteam1). Also reads
// `g_gametype`.
pub fn SP_info_player_siegeteam2(ent: *mut gentity_t) {
    todo!("Port SP_info_player_siegeteam2 — parked: fn-ptr-store-shape-mismatch")
}

/// Raven `SP_info_player_intermission` — the intermission view point (no-op
/// spawn; the point is only read by the intermission code).
///
/// Source: `oracle/oracle/codemp/game/g_client.c:230-232`
pub fn SP_info_player_intermission(ent: *mut gentity_t) {}

/// Raven `SP_info_player_intermission_red`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:241-243`
pub fn SP_info_player_intermission_red(ent: *mut gentity_t) {}

/// Raven `SP_info_player_intermission_blue`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:252-254`
pub fn SP_info_player_intermission_blue(ent: *mut gentity_t) {}

/// Raven `ThrowSaberToAttacker` — drop the Jedi-Master saber toward the killer.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:258-344`
// PORT-ESCALATION(gjmsaber-global-plus-g2-traps): reads the file-scope
// `gJMSaberEnt`/`g_entities`, adds the ghoul2 saber model via `WP_SaberAddG2Model`,
// and calls `trap_SetConfigstring`/`trap_LinkEntity`; the ghoul2 model handle
// threading is not resolved in this packet.
pub fn ThrowSaberToAttacker(self_: *mut gentity_t, attacker: *mut gentity_t) {
    todo!("Port ThrowSaberToAttacker — parked: gjmsaber-global-plus-g2-traps")
}

/// Raven `JMSaberThink`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:346-383`
// PORT-ESCALATION(gjmsaber-global-plus-trap): writes the file-scope `gJMSaberEnt`,
// reads `level`, calls `trap_LinkEntity`, and is itself stored as a `think`
// fn-pointer (raw `extern "C" fn` on `gentity_t`, not the `EntThink` enum).
pub fn JMSaberThink(ent: *mut gentity_t) {
    todo!("Port JMSaberThink — parked: gjmsaber-global-plus-trap")
}

/// Raven `JMSaberTouch` — pick up the JM saber, become the Jedi Master.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:385-469`
// PORT-ESCALATION(traps-va-plus-fn-ptr-store): calls `trap_SetConfigstring`/
// `trap_SendServerCommand` with `va(...)` varargs, `G_KillG2Queue`, reads
// `g_spawnInvulnerability`/`level`; stored as a `touch` fn-pointer (raw
// `extern "C" fn`, not the `EntTouch` enum).
pub fn JMSaberTouch(self_: *mut gentity_t, other: *mut gentity_t, trace: *mut trace_t) {
    todo!("Port JMSaberTouch — parked: traps-va-plus-fn-ptr-store")
}

/// Raven `SP_info_jedimaster_start` — the JM saber spawn point.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:476-516`
// PORT-ESCALATION(fn-ptr-store-shape-mismatch): stores `ent->touch = JMSaberTouch`
// and `ent->think = JMSaberThink` into the still-raw `gentity_t` fn pointers,
// writes `gJMSaberEnt`, reads `g_gametype`/`level`, calls `trap_LinkEntity`.
pub fn SP_info_jedimaster_start(ent: *mut gentity_t) {
    todo!("Port SP_info_jedimaster_start — parked: fn-ptr-store-shape-mismatch")
}

/// Raven `SpotWouldTelefrag` — would a client spawn on `spot` overlap another
/// client?
///
/// Source: `oracle/oracle/codemp/game/g_client.c:532-552`
pub fn SpotWouldTelefrag(ctx: GameContext<'_>, spot: *mut gentity_t) -> qboolean {
    unsafe {
        let mut touch: [c_int; MAX_GENTITIES] = [0; MAX_GENTITIES];
        let mut mins: vec3_t = [0.0; 3];
        let mut maxs: vec3_t = [0.0; 3];

        for k in 0..3 {
            mins[k] = (*spot).s.origin[k] + playerMins[k];
            maxs[k] = (*spot).s.origin[k] + playerMaxs[k];
        }
        let num = trap::EntitiesInBox(
            ctx.engine,
            GEntitiesInBoxArgs::new(
                &mins as *const vec3_t,
                &maxs as *const vec3_t,
                touch.as_mut_ptr(),
                MAX_GENTITIES as c_int,
            ),
        );

        let mut i = 0;
        while i < num {
            let hit = &mut (*ctx.world).entities[touch[i as usize] as usize] as *mut gentity_t;
            // if ( hit->client && hit->client->ps.stats[STAT_HEALTH] > 0 ) — the
            // health test is commented out in Raven; any client presence telefrags.
            if !(*hit).client.is_null() {
                return qtrue;
            }
            i += 1;
        }

        qfalse
    }
}

/// Raven `SpotWouldTelefrag2` — would `mover` moved to `dest` overlap a solid?
///
/// Source: `oracle/oracle/codemp/game/g_client.c:554-580`
pub fn SpotWouldTelefrag2(ctx: GameContext<'_>, mover: *mut gentity_t, dest: vec3_t) -> qboolean {
    unsafe {
        let mut touch: [c_int; MAX_GENTITIES] = [0; MAX_GENTITIES];
        let mut mins: vec3_t = [0.0; 3];
        let mut maxs: vec3_t = [0.0; 3];

        for k in 0..3 {
            mins[k] = dest[k] + (*mover).r.mins[k];
            maxs[k] = dest[k] + (*mover).r.maxs[k];
        }
        let num = trap::EntitiesInBox(
            ctx.engine,
            GEntitiesInBoxArgs::new(
                &mins as *const vec3_t,
                &maxs as *const vec3_t,
                touch.as_mut_ptr(),
                MAX_GENTITIES as c_int,
            ),
        );

        let mut i = 0;
        while i < num {
            let hit = &mut (*ctx.world).entities[touch[i as usize] as usize] as *mut gentity_t;
            if hit == mover {
                i += 1;
                continue;
            }
            if (*hit).r.contents & (*mover).r.contents != 0 {
                return qtrue;
            }
            i += 1;
        }

        qfalse
    }
}

/// Raven `SelectNearestDeathmatchSpawnPoint` — find the spot we DON'T want.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:590-611`
pub fn SelectNearestDeathmatchSpawnPoint(from: vec3_t) -> *mut gentity_t {
    unsafe {
        let mut nearestDist: f32 = 999999.0;
        let mut nearestSpot: *mut gentity_t = core::ptr::null_mut();
        let mut spot: *mut gentity_t = core::ptr::null_mut();

        loop {
            spot = crate::g_utils::G_Find(
                spot,
                fofs_classname(),
                b"info_player_deathmatch\0".as_ptr() as *const c_char,
            );
            if spot.is_null() {
                break;
            }
            let mut delta: vec3_t = [0.0; 3];
            for k in 0..3 {
                delta[k] = (*spot).s.origin[k] - from[k];
            }
            let dist = VectorLength(delta);
            if dist < nearestDist {
                nearestDist = dist;
                nearestSpot = spot;
            }
        }

        nearestSpot
    }
}

/// Raven `SelectRandomDeathmatchSpawnPoint` — a random non-telefragging spot.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:622-645`
pub fn SelectRandomDeathmatchSpawnPoint(ctx: GameContext<'_>) -> *mut gentity_t {
    const MAX_SPAWN_POINTS: usize = 128;
    unsafe {
        let mut count: c_int = 0;
        let mut spot: *mut gentity_t = core::ptr::null_mut();
        let mut spots: [*mut gentity_t; MAX_SPAWN_POINTS] = [core::ptr::null_mut(); MAX_SPAWN_POINTS];

        loop {
            spot = crate::g_utils::G_Find(
                spot,
                fofs_classname(),
                b"info_player_deathmatch\0".as_ptr() as *const c_char,
            );
            if spot.is_null() {
                break;
            }
            if SpotWouldTelefrag(ctx, spot) != 0 {
                continue;
            }
            spots[count as usize] = spot;
            count += 1;
        }

        if count == 0 {
            // no spots that won't telefrag
            return crate::g_utils::G_Find(
                core::ptr::null_mut(),
                fofs_classname(),
                b"info_player_deathmatch\0".as_ptr() as *const c_char,
            );
        }

        let selection = crate::bg_lib::rand() % count;
        spots[selection as usize]
    }
}

/// Raven `SelectRandomFurthestSpawnPoint` — a start furthest from the avoid
/// point.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:654-758`
// PORT-ESCALATION(rng-random-macro): line 751 `rnd = random() * (numSpots / 2)`
// uses the Q3 `random()` float-RNG macro, which fork ruling 3 maps to the owned,
// threaded LCG — not reachable from this signature (no Rng handle). Also reads
// `g_gametype`.
pub fn SelectRandomFurthestSpawnPoint(
    avoidPoint: vec3_t,
    origin: vec3_t,
    angles: vec3_t,
    team: team_t,
) -> *mut gentity_t {
    todo!("Port SelectRandomFurthestSpawnPoint — parked: rng-random-macro")
}

/// Raven `SelectDuelSpawnPoint` — a duel/powerduel start furthest from the avoid
/// point.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:760-845`
// PORT-ESCALATION(rng-random-macro): line 838 `rnd = random() * (numSpots / 2)`
// uses the Q3 `random()` float-RNG macro (fork ruling 3: threaded LCG), not
// reachable from this signature.
pub fn SelectDuelSpawnPoint(
    team: c_int,
    avoidPoint: vec3_t,
    origin: vec3_t,
    angles: vec3_t,
) -> *mut gentity_t {
    todo!("Port SelectDuelSpawnPoint — parked: rng-random-macro")
}

/// Raven `SelectSpawnPoint` — chooses a player start, deathmatch start, etc.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:854-884`
pub fn SelectSpawnPoint(
    avoidPoint: vec3_t,
    origin: vec3_t,
    angles: vec3_t,
    team: team_t,
) -> *mut gentity_t {
    SelectRandomFurthestSpawnPoint(avoidPoint, origin, angles, team)
}

/// Raven `SelectInitialSpawnPoint` — a spawn marked 'initial', else normal
/// selection.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:894-913`
// PORT-ESCALATION(vec3-outparam-plus-ctx): calls `SpotWouldTelefrag(spot)` (needs
// `trap_EntitiesInBox`, i.e. a `GameContext` the resolved skeleton signature does
// not carry) AND writes the `origin`/`angles` out-params
// (`VectorCopy(spot->s.origin, origin); origin[2] += 9; …`) which the by-value
// (Copy) `vec3_t` skeleton parameters cannot flow back to the caller — the
// shared vec3-outparam convention. Both are integration decisions.
pub fn SelectInitialSpawnPoint(origin: vec3_t, angles: vec3_t, team: team_t) -> *mut gentity_t {
    todo!("Port SelectInitialSpawnPoint — parked: vec3-outparam-plus-ctx")
}

/// Raven `SelectSpectatorSpawnPoint`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:921-928`
// PORT-ESCALATION(level-locals-field-paths): reads `level.intermission_origin`/
// `level.intermission_angle` after `FindIntermissionPoint()`; the exact
// `level_locals_t` field spellings are resolved at integration.
pub fn SelectSpectatorSpawnPoint(origin: vec3_t, angles: vec3_t) -> *mut gentity_t {
    todo!("Port SelectSpectatorSpawnPoint — parked: level-locals-field-paths")
}

/// Raven `InitBodyQue` — allocate the body-queue entities.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:953-964`
// PORT-ESCALATION(fn-ptr-store-shape-mismatch): fills `level.bodyQue[]` via
// `G_Spawn` and writes the queue entities' fn pointers; needs `level` write +
// the fn-ID enum wiring.
pub fn InitBodyQue() {
    todo!("Port InitBodyQue — parked: fn-ptr-store-shape-mismatch")
}

/// Raven `BodySink` — after death, sink the body into the ground and remove.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:973-986`
// PORT-ESCALATION(fn-ptr-store-shape-mismatch): re-arms `ent->think = BodySink`
// (raw `extern "C" fn` on `gentity_t`, not `EntThink`), reads `level`, calls
// `trap_UnlinkEntity`.
pub fn BodySink(ent: *mut gentity_t) {
    todo!("Port BodySink — parked: fn-ptr-store-shape-mismatch")
}

/// Raven `CopyToBodyQue` — copy a dead client into the body queue.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:996-1105`
// PORT-ESCALATION(fn-ptr-store-plus-traps): stores `think = BodySink`,
// `die = body_die` (still-raw fn pointers), reads `g_entities`, writes `level`,
// calls `trap_LinkEntity`/`trap_UnlinkEntity`/`trap_PointContents`/
// `trap_SendServerCommand`.
pub fn CopyToBodyQue(ent: *mut gentity_t) -> qboolean {
    todo!("Port CopyToBodyQue — parked: fn-ptr-store-plus-traps")
}

/// Raven `SetClientViewAngle` — set the client's view + delta angles.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1116-1128`
pub fn SetClientViewAngle(ent: *mut gentity_t, angle: vec3_t) {
    unsafe {
        let client = (*ent).client;
        // set the delta angle
        for i in 0..3 {
            // ANGLE2SHORT(x) == ((int)((x)*65536/360) & 65535)
            let cmdAngle: c_int = ((angle[i] * 65536.0 / 360.0) as c_int) & 65535;
            (*client).ps.delta_angles[i] = cmdAngle - (*client).pers.cmd.angles[i] as c_int;
        }
        // VectorCopy( angle, ent->s.angles );
        (*ent).s.angles = angle;
        // VectorCopy( ent->s.angles, ent->client->ps.viewangles );
        (*client).ps.viewangles = (*ent).s.angles;
    }
}

/// Raven `MaintainBodyQueue`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1130-1159`
// PORT-ESCALATION(traps-plus-body-queue): calls `CopyToBodyQue` (parked), reads
// `level`, sends `va(...)`-formatted server commands via `trap_SendServerCommand`.
pub fn MaintainBodyQueue(ent: *mut gentity_t) {
    todo!("Port MaintainBodyQueue — parked: traps-plus-body-queue")
}

/// Raven `respawn` — respawn a client (or queue the body).
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1167-1228`
// PORT-ESCALATION(multi-global-trap-cluster): reads `gEscaping`/`g_gametype`/
// `g_siegeRespawn`/`g_siegeRespawnCheck`/`level`, calls `trap_LinkEntity`/
// `trap_UnlinkEntity`, `G_TempEntity`, `ClientSpawn`/`SiegeRespawn`.
pub fn respawn(ent: *mut gentity_t) {
    todo!("Port respawn — parked: multi-global-trap-cluster")
}

/// Raven `TeamCount` — count players on a team.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1237-1259`
// PORT-ESCALATION(level-locals-field-paths): walks `level.maxclients`/
// `level.clients[i].pers.connected`/`.sess.sessionTeam` and reads `g_gametype`;
// the exact `level_locals_t`/session field spellings are resolved at integration.
pub fn TeamCount(ignoreClientNum: c_int, team: c_int) -> team_t {
    todo!("Port TeamCount — parked: level-locals-field-paths")
}

/// Raven `TeamLeader` — find a team's leader client number.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1268-1282`
// PORT-ESCALATION(level-locals-field-paths): walks `level.maxclients`/
// `level.clients[i]` session fields; resolved at integration.
pub fn TeamLeader(team: c_int) -> c_int {
    todo!("Port TeamLeader — parked: level-locals-field-paths")
}

/// Raven `PickTeam` — pick the emptier team.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1291-1308`
// PORT-ESCALATION(level-locals-field-paths): calls `TeamCount` (parked) over
// `level` session fields; resolved at integration.
pub fn PickTeam(ignoreClientNum: c_int) -> team_t {
    todo!("Port PickTeam — parked: level-locals-field-paths")
}

/// Raven `ClientCleanName` — sanitize a player name (colors, spaces, length).
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1335-1410`
pub fn ClientCleanName(r#in: *const c_char, out: *mut c_char, outSize: c_int) {
    // Q_COLOR_ESCAPE == '^'; ColorIndex(c) == ((c - '0') & 0x07).
    const Q_COLOR_ESCAPE: c_char = b'^' as c_char;
    #[inline]
    fn ColorIndex(c: c_char) -> c_int {
        (c as c_int - '0' as c_int) & 0x07
    }
    unsafe {
        // save room for trailing null byte
        let outSize = outSize - 1;

        let mut len: c_int = 0;
        let mut colorlessLen: c_int = 0;
        let p = out; // start of dest
        *p = 0;
        let mut spaces: c_int = 0;

        let mut inp = r#in;
        let mut outp = out;

        loop {
            let ch = *inp;
            inp = inp.add(1);
            if ch == 0 {
                break;
            }

            // don't allow leading spaces
            if *p == 0 && ch == b' ' as c_char {
                continue;
            }

            // check colors
            if ch == Q_COLOR_ESCAPE {
                // solo trailing carat is not a color prefix
                if *inp == 0 {
                    break;
                }

                // don't allow black in a name, period
                if ColorIndex(*inp) == 0 {
                    inp = inp.add(1);
                    continue;
                }

                // make sure room in dest for both chars
                if len > outSize - 2 {
                    break;
                }

                *outp = ch;
                outp = outp.add(1);
                *outp = *inp;
                outp = outp.add(1);
                inp = inp.add(1);
                len += 2;
                continue;
            }

            // don't allow too many consecutive spaces
            if ch == b' ' as c_char {
                spaces += 1;
                if spaces > 3 {
                    continue;
                }
            } else {
                spaces = 0;
            }

            if len > outSize - 1 {
                break;
            }

            *outp = ch;
            outp = outp.add(1);
            colorlessLen += 1;
            len += 1;
        }
        *outp = 0;

        // don't allow empty names
        if *p == 0 || colorlessLen == 0 {
            crate::q_shared::Q_strncpyz(p, b"Padawan\0".as_ptr() as *const c_char, outSize);
        }
    }
}

/// Raven `G_SaberModelSetup`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1423-1499`
// PORT-ESCALATION(g2-ghoul2-traps): builds the saber ghoul2 models via
// `trap_G2API_*` (AddBolt/CleanGhoul2Models/CopySpecificGhoul2Model/
// InitGhoul2Model/SetBoltInfo/SetSkin); the ghoul2 handle threading + Args
// constructors are not resolved in this packet.
pub fn G_SaberModelSetup(ent: *mut gentity_t) -> qboolean {
    todo!("Port G_SaberModelSetup — parked: g2-ghoul2-traps")
}

/// Raven `SetupGameGhoul2Model`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1519-1870`
// PORT-ESCALATION(g2-ghoul2-traps-plus-bg): the full server-side ghoul2 model
// setup — dozens of `trap_G2API_*` calls, `BG_*` model/animation validation,
// `g_gametype`/`g_trueJedi`/`level`/`bgHumanoidAnimations`/`bgSiegeClasses`
// globals; ghoul2 handle threading unresolved here.
pub fn SetupGameGhoul2Model(ent: *mut gentity_t, modelname: *mut c_char, skinName: *mut c_char) {
    todo!("Port SetupGameGhoul2Model — parked: g2-ghoul2-traps-plus-bg")
}

/// Raven `ClientUserinfoChanged` — apply a client's userinfo string.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:1888-2235`
// PORT-ESCALATION(multi-global-trap-va-cluster): reads/writes userinfo via
// `trap_GetUserinfo`/`trap_SetUserinfo`/`trap_SetConfigstring`/
// `trap_SendServerCommand`, formats with `va(...)`, calls `SetupGameGhoul2Model`
// (parked) and `BG_Siege*`, reads `g_entities`/`g_gametype`/`level`/`bgSiegeClasses`.
pub fn ClientUserinfoChanged(clientNum: c_int) {
    todo!("Port ClientUserinfoChanged — parked: multi-global-trap-va-cluster")
}

/// Raven `ClientConnect`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2258-2373`
// PORT-ESCALATION(multi-global-trap-va-cluster): `trap_GetUserinfo`/
// `trap_SendServerCommand` + `va(...)`, session/bot init, reads
// `g_entities`/`g_gametype`/`g_needpass`/`g_password`/`level`; returns a raw
// `*mut c_char` into a fn-scope static buffer (fork 5) that the raw-ptr
// signature cannot own.
pub fn ClientConnect(clientNum: c_int, firstTime: qboolean, isBot: qboolean) -> *mut c_char {
    todo!("Port ClientConnect — parked: multi-global-trap-va-cluster")
}

/// Raven `ClientBegin`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2393-2593`
// PORT-ESCALATION(multi-global-trap-va-cluster): traps
// (`trap_GetUserinfo`/`trap_SetUserinfo`/`trap_SendServerCommand`/
// `trap_UnlinkEntity`), `va(...)`, `ClientSpawn`/`SetTeam`/`SetupGameGhoul2Model`
// (parked), reads `gSiegeRound*`/`g_entities`/`g_gametype`/`level`.
pub fn ClientBegin(clientNum: c_int, allowTeamReset: qboolean) {
    todo!("Port ClientBegin — parked: multi-global-trap-va-cluster")
}

/// Raven `AllForceDisabled` — are all force powers disabled by the mask?
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2595-2613`
pub fn AllForceDisabled(force: c_int) -> qboolean {
    if force != 0 {
        for i in 0..NUM_FORCE_POWERS {
            if force & (1 << i) == 0 {
                return qfalse;
            }
        }
        return qtrue;
    }

    qfalse
}

/// Raven `G_BreakArm` — set up a broken-limb state and pain animation.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2616-2674`
// PORT-ESCALATION(va-varargs-plus-rng): builds a sound name with `va(...)` +
// `Q_irand(1,3)` (the resolved `va` drops the C varargs, and `Q_irand` is part
// of the threaded-RNG surface, fork ruling 3).
pub fn G_BreakArm(ent: *mut gentity_t, arm: c_int) {
    todo!("Port G_BreakArm — parked: va-varargs-plus-rng")
}

/// Raven `G_UpdateClientAnims`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2681-2926`
// PORT-ESCALATION(g2-trap-plus-bg): drives torso/legs bone anims via
// `trap_G2API_SetBoneAnim` and `BG_SaberStartTransAnim`, reads
// `bgAllAnims`/`level`; ghoul2 handle threading unresolved here.
pub fn G_UpdateClientAnims(self_: *mut gentity_t, animSpeedScale: f32) {
    todo!("Port G_UpdateClientAnims — parked: g2-trap-plus-bg")
}

/// Raven `ClientSpawn` — spawn/respawn a client into the world (864 LOC).
///
/// Source: `oracle/oracle/codemp/game/g_client.c:2938-3801`
// PORT-ESCALATION(mega-fn-globals-traps-bg-fnptr): the largest function in the
// file — ~18 cvars, `g_entities`/`level`/`playerMins`/`playerMaxs`/`ammoData`/
// `weaponData`/`WeaponReadyAnim`/`bgSiegeClasses` globals, many traps
// (`trap_Cvar_Set`/`trap_GetUsercmd`/`trap_GetUserinfo`/`trap_SetUserinfo`/
// `trap_ICARUS_*`/`trap_LinkEntity`), `BG_*`/`WP_*` calls, `va(...)`, and stores
// `die = player_die` (still-raw fn pointer). Beyond safe single-porter
// transcription without compilation; integration to thread the spine.
pub fn ClientSpawn(ent: *mut gentity_t) {
    todo!("Port ClientSpawn — parked: mega-fn-globals-traps-bg-fnptr")
}

/// Raven `ClientDisconnect`.
///
/// Source: `oracle/oracle/codemp/game/g_client.c:3816-3938`
// PORT-ESCALATION(multi-global-trap-g2): `trap_G2API_CleanGhoul2Models`/
// `trap_G2_HaveWeGhoul2Models`/`trap_SetConfigstring`/`trap_UnlinkEntity`,
// bot/log/follow teardown, reads `g_entities`/`g_gametype`, writes `level`.
pub fn ClientDisconnect(clientNum: c_int) {
    todo!("Port ClientDisconnect — parked: multi-global-trap-g2")
}
