//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/g_ICARUScb.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `Q3_TaskIDClear`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:270-273`
pub fn Q3_TaskIDClear(
    taskID: *mut c_int,
) {
    todo!("Port Q3_TaskIDClear — oracle/oracle/codemp/game/g_ICARUScb.c:270")
}

/// Raven `G_DebugPrint`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:275-324`
pub fn G_DebugPrint(
    level: c_int,
    format: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port G_DebugPrint — oracle/oracle/codemp/game/g_ICARUScb.c:275")
}

/// Raven `Q3_GetAnimLower`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:331-344`
pub fn Q3_GetAnimLower(
    ent: *mut gentity_t,
) -> *mut c_char {
    todo!("Port Q3_GetAnimLower — oracle/oracle/codemp/game/g_ICARUScb.c:331")
}

/// Raven `Q3_GetAnimUpper`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:351-364`
pub fn Q3_GetAnimUpper(
    ent: *mut gentity_t,
) -> *mut c_char {
    todo!("Port Q3_GetAnimUpper — oracle/oracle/codemp/game/g_ICARUScb.c:351")
}

/// Raven `Q3_GetAnimBoth`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:371-398`
pub fn Q3_GetAnimBoth(
    ent: *mut gentity_t,
) -> *mut c_char {
    todo!("Port Q3_GetAnimBoth — oracle/oracle/codemp/game/g_ICARUScb.c:371")
}

/// Raven `Q3_PlaySound`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:400-520`
pub fn Q3_PlaySound(
    taskID: c_int,
    entID: c_int,
    name: *const c_char,
    channel: *const c_char,
) -> c_int {
    todo!("Port Q3_PlaySound — oracle/oracle/codemp/game/g_ICARUScb.c:400")
}

/// Raven `Q3_Play`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:527-560`
pub fn Q3_Play(
    taskID: c_int,
    entID: c_int,
    r#type: *const c_char,
    name: *const c_char,
) {
    todo!("Port Q3_Play — oracle/oracle/codemp/game/g_ICARUScb.c:527")
}

/// Raven `anglerCallback`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:569-591`
pub fn anglerCallback(
    ent: *mut gentity_t,
) {
    todo!("Port anglerCallback — oracle/oracle/codemp/game/g_ICARUScb.c:569")
}

/// Raven `moverCallback`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:603-633`
pub fn moverCallback(
    ent: *mut gentity_t,
) {
    todo!("Port moverCallback — oracle/oracle/codemp/game/g_ICARUScb.c:603")
}

/// Raven `Blocked_Mover`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:635-658`
pub fn Blocked_Mover(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) {
    todo!("Port Blocked_Mover — oracle/oracle/codemp/game/g_ICARUScb.c:635")
}

/// Raven `moveAndRotateCallback`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:667-673`
pub fn moveAndRotateCallback(
    ent: *mut gentity_t,
) {
    todo!("Port moveAndRotateCallback — oracle/oracle/codemp/game/g_ICARUScb.c:667")
}

/// Raven `Q3_Lerp2Start`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:682-721`
pub fn Q3_Lerp2Start(
    entID: c_int,
    taskID: c_int,
    duration: f32,
) {
    todo!("Port Q3_Lerp2Start — oracle/oracle/codemp/game/g_ICARUScb.c:682")
}

/// Raven `Q3_Lerp2End`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:730-769`
pub fn Q3_Lerp2End(
    entID: c_int,
    taskID: c_int,
    duration: f32,
) {
    todo!("Port Q3_Lerp2End — oracle/oracle/codemp/game/g_ICARUScb.c:730")
}

/// Raven `Q3_Lerp2Pos`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:781-883`
pub fn Q3_Lerp2Pos(
    taskID: c_int,
    entID: c_int,
    origin: vec3_t,
    angles: vec3_t,
    duration: f32,
) {
    todo!("Port Q3_Lerp2Pos — oracle/oracle/codemp/game/g_ICARUScb.c:781")
}

/// Raven `Q3_Lerp2Angles`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:892-939`
pub fn Q3_Lerp2Angles(
    taskID: c_int,
    entID: c_int,
    angles: vec3_t,
    duration: f32,
) {
    todo!("Port Q3_Lerp2Angles — oracle/oracle/codemp/game/g_ICARUScb.c:892")
}

/// Raven `Q3_GetTag`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:948-970`
pub fn Q3_GetTag(
    entID: c_int,
    name: *const c_char,
    lookup: c_int,
    info: vec3_t,
) -> c_int {
    todo!("Port Q3_GetTag — oracle/oracle/codemp/game/g_ICARUScb.c:948")
}

/// Raven `Q3_Use`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:981-998`
pub fn Q3_Use(
    entID: c_int,
    target: *const c_char,
) {
    todo!("Port Q3_Use — oracle/oracle/codemp/game/g_ICARUScb.c:981")
}

/// Raven `Q3_Kill`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1009-1052`
pub fn Q3_Kill(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_Kill — oracle/oracle/codemp/game/g_ICARUScb.c:1009")
}

/// Raven `Q3_RemoveEnt`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1062-1116`
pub fn Q3_RemoveEnt(
    victim: *mut gentity_t,
) {
    todo!("Port Q3_RemoveEnt — oracle/oracle/codemp/game/g_ICARUScb.c:1062")
}

/// Raven `Q3_Remove`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1128-1168`
pub fn Q3_Remove(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_Remove — oracle/oracle/codemp/game/g_ICARUScb.c:1128")
}

/// Raven `Q3_GetFloat`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1189-1559`
pub fn Q3_GetFloat(
    entID: c_int,
    r#type: c_int,
    name: *const c_char,
    value: *mut f32,
) -> c_int {
    todo!("Port Q3_GetFloat — oracle/oracle/codemp/game/g_ICARUScb.c:1189")
}

/// Raven `Q3_GetVector`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1573-1629`
pub fn Q3_GetVector(
    entID: c_int,
    r#type: c_int,
    name: *const c_char,
    value: vec3_t,
) -> c_int {
    todo!("Port Q3_GetVector — oracle/oracle/codemp/game/g_ICARUScb.c:1573")
}

/// Raven `Q3_GetString`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1642-1854`
pub fn Q3_GetString(
    entID: c_int,
    r#type: c_int,
    name: *const c_char,
    value: *mut *mut c_char,
) -> c_int {
    todo!("Port Q3_GetString — oracle/oracle/codemp/game/g_ICARUScb.c:1642")
}

/// Raven `MoveOwner`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1865-1886`
pub fn MoveOwner(
    self_: *mut gentity_t,
) {
    todo!("Port MoveOwner — oracle/oracle/codemp/game/g_ICARUScb.c:1865")
}

/// Raven `Q3_SetTeleportDest`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1895-1920`
pub fn Q3_SetTeleportDest(
    entID: c_int,
    org: vec3_t,
) -> qboolean {
    todo!("Port Q3_SetTeleportDest — oracle/oracle/codemp/game/g_ICARUScb.c:1895")
}

/// Raven `Q3_SetOrigin`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1929-1961`
pub fn Q3_SetOrigin(
    entID: c_int,
    origin: vec3_t,
) {
    todo!("Port Q3_SetOrigin — oracle/oracle/codemp/game/g_ICARUScb.c:1929")
}

/// Raven `Q3_SetCopyOrigin`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1970-1983`
pub fn Q3_SetCopyOrigin(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetCopyOrigin — oracle/oracle/codemp/game/g_ICARUScb.c:1970")
}

/// Raven `Q3_SetVelocity`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:1992-2013`
pub fn Q3_SetVelocity(
    entID: c_int,
    axis: c_int,
    speed: f32,
) {
    todo!("Port Q3_SetVelocity — oracle/oracle/codemp/game/g_ICARUScb.c:1992")
}

/// Raven `Q3_SetAngles`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2022-2042`
pub fn Q3_SetAngles(
    entID: c_int,
    angles: vec3_t,
) {
    todo!("Port Q3_SetAngles — oracle/oracle/codemp/game/g_ICARUScb.c:2022")
}

/// Raven `Q3_Lerp2Origin`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2051-2112`
pub fn Q3_Lerp2Origin(
    taskID: c_int,
    entID: c_int,
    origin: vec3_t,
    duration: f32,
) {
    todo!("Port Q3_Lerp2Origin — oracle/oracle/codemp/game/g_ICARUScb.c:2051")
}

/// Raven `Q3_SetOriginOffset`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2114-2140`
pub fn Q3_SetOriginOffset(
    entID: c_int,
    axis: c_int,
    offset: f32,
) {
    todo!("Port Q3_SetOriginOffset — oracle/oracle/codemp/game/g_ICARUScb.c:2114")
}

/// Raven `Q3_SetEnemy`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2149-2197`
pub fn Q3_SetEnemy(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetEnemy — oracle/oracle/codemp/game/g_ICARUScb.c:2149")
}

/// Raven `Q3_SetLeader`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2207-2246`
pub fn Q3_SetLeader(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetLeader — oracle/oracle/codemp/game/g_ICARUScb.c:2207")
}

/// Raven `Q3_SetNavGoal`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2255-2320`
pub fn Q3_SetNavGoal(
    entID: c_int,
    name: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetNavGoal — oracle/oracle/codemp/game/g_ICARUScb.c:2255")
}

/// Raven `SetLowerAnim`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2330-2347`
pub fn SetLowerAnim(
    entID: c_int,
    animID: c_int,
) {
    todo!("Port SetLowerAnim — oracle/oracle/codemp/game/g_ICARUScb.c:2330")
}

/// Raven `SetUpperAnim`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2358-2375`
pub fn SetUpperAnim(
    entID: c_int,
    animID: c_int,
) {
    todo!("Port SetUpperAnim — oracle/oracle/codemp/game/g_ICARUScb.c:2358")
}

/// Raven `Q3_SetAnimUpper`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2384-2405`
pub fn Q3_SetAnimUpper(
    entID: c_int,
    anim_name: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetAnimUpper — oracle/oracle/codemp/game/g_ICARUScb.c:2384")
}

/// Raven `Q3_SetAnimLower`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2414-2437`
pub fn Q3_SetAnimLower(
    entID: c_int,
    anim_name: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetAnimLower — oracle/oracle/codemp/game/g_ICARUScb.c:2414")
}

/// Raven `Q3_SetAnimHoldTime`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2449-2476`
pub fn Q3_SetAnimHoldTime(
    entID: c_int,
    int_data: c_int,
    lower: qboolean,
) {
    todo!("Port Q3_SetAnimHoldTime — oracle/oracle/codemp/game/g_ICARUScb.c:2449")
}

/// Raven `Q3_SetHealth`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2487-2527`
pub fn Q3_SetHealth(
    entID: c_int,
    data: c_int,
) {
    todo!("Port Q3_SetHealth — oracle/oracle/codemp/game/g_ICARUScb.c:2487")
}

/// Raven `Q3_SetArmor`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2539-2559`
pub fn Q3_SetArmor(
    entID: c_int,
    data: c_int,
) {
    todo!("Port Q3_SetArmor — oracle/oracle/codemp/game/g_ICARUScb.c:2539")
}

/// Raven `Q3_SetBState`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2573-2687`
pub fn Q3_SetBState(
    entID: c_int,
    bs_name: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetBState — oracle/oracle/codemp/game/g_ICARUScb.c:2573")
}

/// Raven `Q3_SetTempBState`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2699-2737`
pub fn Q3_SetTempBState(
    entID: c_int,
    bs_name: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetTempBState — oracle/oracle/codemp/game/g_ICARUScb.c:2699")
}

/// Raven `Q3_SetDefaultBState`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2749-2771`
pub fn Q3_SetDefaultBState(
    entID: c_int,
    bs_name: *const c_char,
) {
    todo!("Port Q3_SetDefaultBState — oracle/oracle/codemp/game/g_ICARUScb.c:2749")
}

/// Raven `Q3_SetDPitch`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2783-2787`
pub fn Q3_SetDPitch(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetDPitch — oracle/oracle/codemp/game/g_ICARUScb.c:2783")
}

/// Raven `Q3_SetDYaw`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2799-2803`
pub fn Q3_SetDYaw(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetDYaw — oracle/oracle/codemp/game/g_ICARUScb.c:2799")
}

/// Raven `Q3_SetShootDist`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2815-2819`
pub fn Q3_SetShootDist(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetShootDist — oracle/oracle/codemp/game/g_ICARUScb.c:2815")
}

/// Raven `Q3_SetVisrange`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2831-2835`
pub fn Q3_SetVisrange(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetVisrange — oracle/oracle/codemp/game/g_ICARUScb.c:2831")
}

/// Raven `Q3_SetEarshot`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2847-2851`
pub fn Q3_SetEarshot(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetEarshot — oracle/oracle/codemp/game/g_ICARUScb.c:2847")
}

/// Raven `Q3_SetVigilance`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2863-2867`
pub fn Q3_SetVigilance(
    entID: c_int,
    data: f32,
) {
    todo!("Port Q3_SetVigilance — oracle/oracle/codemp/game/g_ICARUScb.c:2863")
}

/// Raven `Q3_SetVFOV`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2879-2883`
pub fn Q3_SetVFOV(
    entID: c_int,
    data: c_int,
) {
    todo!("Port Q3_SetVFOV — oracle/oracle/codemp/game/g_ICARUScb.c:2879")
}

/// Raven `Q3_SetHFOV`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2895-2899`
pub fn Q3_SetHFOV(
    entID: c_int,
    data: c_int,
) {
    todo!("Port Q3_SetHFOV — oracle/oracle/codemp/game/g_ICARUScb.c:2895")
}

/// Raven `Q3_SetWidth`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2911-2915`
pub fn Q3_SetWidth(
    entID: c_int,
    data: c_int,
) {
    todo!("Port Q3_SetWidth — oracle/oracle/codemp/game/g_ICARUScb.c:2911")
}

/// Raven `Q3_SetTimeScale`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2926-2929`
pub fn Q3_SetTimeScale(
    entID: c_int,
    data: *const c_char,
) {
    todo!("Port Q3_SetTimeScale — oracle/oracle/codemp/game/g_ICARUScb.c:2926")
}

/// Raven `Q3_SetInvisible`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2941-2968`
pub fn Q3_SetInvisible(
    entID: c_int,
    invisible: qboolean,
) {
    todo!("Port Q3_SetInvisible — oracle/oracle/codemp/game/g_ICARUScb.c:2941")
}

/// Raven `Q3_SetVampire`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2979-2983`
pub fn Q3_SetVampire(
    entID: c_int,
    vampire: qboolean,
) {
    todo!("Port Q3_SetVampire — oracle/oracle/codemp/game/g_ICARUScb.c:2979")
}

/// Raven `Q3_SetGreetAllies`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:2993-2997`
pub fn Q3_SetGreetAllies(
    entID: c_int,
    greet: qboolean,
) {
    todo!("Port Q3_SetGreetAllies — oracle/oracle/codemp/game/g_ICARUScb.c:2993")
}

/// Raven `Q3_SetViewTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3009-3013`
pub fn Q3_SetViewTarget(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetViewTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3009")
}

/// Raven `Q3_SetWatchTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3025-3029`
pub fn Q3_SetWatchTarget(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetWatchTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3025")
}

/// Raven `Q3_SetLoopSound`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3031-3054`
pub fn Q3_SetLoopSound(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetLoopSound — oracle/oracle/codemp/game/g_ICARUScb.c:3031")
}

/// Raven `Q3_SetICARUSFreeze`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3056-3078`
pub fn Q3_SetICARUSFreeze(
    entID: c_int,
    name: *const c_char,
    freeze: qboolean,
) {
    todo!("Port Q3_SetICARUSFreeze — oracle/oracle/codemp/game/g_ICARUScb.c:3056")
}

/// Raven `Q3_SetViewEntity`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3089-3092`
pub fn Q3_SetViewEntity(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetViewEntity — oracle/oracle/codemp/game/g_ICARUScb.c:3089")
}

/// Raven `Q3_SetWeapon`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3104-3111`
pub fn Q3_SetWeapon(
    entID: c_int,
    wp_name: *const c_char,
) {
    todo!("Port Q3_SetWeapon — oracle/oracle/codemp/game/g_ICARUScb.c:3104")
}

/// Raven `Q3_SetItem`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3122-3126`
pub fn Q3_SetItem(
    entID: c_int,
    item_name: *const c_char,
) {
    todo!("Port Q3_SetItem — oracle/oracle/codemp/game/g_ICARUScb.c:3122")
}

/// Raven `Q3_SetWalkSpeed`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3139-3161`
pub fn Q3_SetWalkSpeed(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetWalkSpeed — oracle/oracle/codemp/game/g_ICARUScb.c:3139")
}

/// Raven `Q3_SetRunSpeed`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3173-3195`
pub fn Q3_SetRunSpeed(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetRunSpeed — oracle/oracle/codemp/game/g_ICARUScb.c:3173")
}

/// Raven `Q3_SetYawSpeed`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3207-3211`
pub fn Q3_SetYawSpeed(
    entID: c_int,
    float_data: f32,
) {
    todo!("Port Q3_SetYawSpeed — oracle/oracle/codemp/game/g_ICARUScb.c:3207")
}

/// Raven `Q3_SetAggression`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3223-3227`
pub fn Q3_SetAggression(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetAggression — oracle/oracle/codemp/game/g_ICARUScb.c:3223")
}

/// Raven `Q3_SetAim`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3239-3243`
pub fn Q3_SetAim(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetAim — oracle/oracle/codemp/game/g_ICARUScb.c:3239")
}

/// Raven `Q3_SetFriction`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3255-3273`
pub fn Q3_SetFriction(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetFriction — oracle/oracle/codemp/game/g_ICARUScb.c:3255")
}

/// Raven `Q3_SetGravity`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3285-3307`
pub fn Q3_SetGravity(
    entID: c_int,
    float_data: f32,
) {
    todo!("Port Q3_SetGravity — oracle/oracle/codemp/game/g_ICARUScb.c:3285")
}

/// Raven `Q3_SetWait`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3319-3330`
pub fn Q3_SetWait(
    entID: c_int,
    float_data: f32,
) {
    todo!("Port Q3_SetWait — oracle/oracle/codemp/game/g_ICARUScb.c:3319")
}

/// Raven `Q3_SetShotSpacing`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3333-3337`
pub fn Q3_SetShotSpacing(
    entID: c_int,
    int_data: c_int,
) {
    todo!("Port Q3_SetShotSpacing — oracle/oracle/codemp/game/g_ICARUScb.c:3333")
}

/// Raven `Q3_SetFollowDist`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3348-3352`
pub fn Q3_SetFollowDist(
    entID: c_int,
    float_data: f32,
) {
    todo!("Port Q3_SetFollowDist — oracle/oracle/codemp/game/g_ICARUScb.c:3348")
}

/// Raven `Q3_SetScale`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3364-3396`
pub fn Q3_SetScale(
    entID: c_int,
    float_data: f32,
) {
    todo!("Port Q3_SetScale — oracle/oracle/codemp/game/g_ICARUScb.c:3364")
}

/// Raven `Q3_GameSideCheckStringCounterIncrement`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3406-3429`
pub fn Q3_GameSideCheckStringCounterIncrement(
    string: *const c_char,
) -> f32 {
    todo!("Port Q3_GameSideCheckStringCounterIncrement — oracle/oracle/codemp/game/g_ICARUScb.c:3406")
}

/// Raven `Q3_SetCount`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3440-3460`
pub fn Q3_SetCount(
    entID: c_int,
    data: *const c_char,
) {
    todo!("Port Q3_SetCount — oracle/oracle/codemp/game/g_ICARUScb.c:3440")
}

/// Raven `Q3_SetTargetName`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3472-3490`
pub fn Q3_SetTargetName(
    entID: c_int,
    targetname: *const c_char,
) {
    todo!("Port Q3_SetTargetName — oracle/oracle/codemp/game/g_ICARUScb.c:3472")
}

/// Raven `Q3_SetTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3502-3520`
pub fn Q3_SetTarget(
    entID: c_int,
    target: *const c_char,
) {
    todo!("Port Q3_SetTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3502")
}

/// Raven `Q3_SetTarget2`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3531-3552`
pub fn Q3_SetTarget2(
    entID: c_int,
    target2: *const c_char,
) {
    todo!("Port Q3_SetTarget2 — oracle/oracle/codemp/game/g_ICARUScb.c:3531")
}

/// Raven `Q3_SetRemoveTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3562-3566`
pub fn Q3_SetRemoveTarget(
    entID: c_int,
    target: *const c_char,
) {
    todo!("Port Q3_SetRemoveTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3562")
}

/// Raven `Q3_SetPainTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3578-3599`
pub fn Q3_SetPainTarget(
    entID: c_int,
    targetname: *const c_char,
) {
    todo!("Port Q3_SetPainTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3578")
}

/// Raven `Q3_SetFullName`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3610-3628`
pub fn Q3_SetFullName(
    entID: c_int,
    fullName: *const c_char,
) {
    todo!("Port Q3_SetFullName — oracle/oracle/codemp/game/g_ICARUScb.c:3610")
}

/// Raven `Q3_SetMusicState`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3630-3634`
pub fn Q3_SetMusicState(
    dms: *const c_char,
) {
    todo!("Port Q3_SetMusicState — oracle/oracle/codemp/game/g_ICARUScb.c:3630")
}

/// Raven `Q3_SetForcePowerLevel`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3636-3640`
pub fn Q3_SetForcePowerLevel(
    entID: c_int,
    forcePower: c_int,
    forceLevel: c_int,
) {
    todo!("Port Q3_SetForcePowerLevel — oracle/oracle/codemp/game/g_ICARUScb.c:3636")
}

/// Raven `Q3_SetParm`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3651-3690`
pub fn Q3_SetParm(
    entID: c_int,
    parmNum: c_int,
    parmValue: *const c_char,
) {
    todo!("Port Q3_SetParm — oracle/oracle/codemp/game/g_ICARUScb.c:3651")
}

/// Raven `Q3_SetCaptureGoal`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3701-3705`
pub fn Q3_SetCaptureGoal(
    entID: c_int,
    name: *const c_char,
) {
    todo!("Port Q3_SetCaptureGoal — oracle/oracle/codemp/game/g_ICARUScb.c:3701")
}

/// Raven `Q3_SetEvent`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3714-3718`
pub fn Q3_SetEvent(
    entID: c_int,
    event_name: *const c_char,
) {
    todo!("Port Q3_SetEvent — oracle/oracle/codemp/game/g_ICARUScb.c:3714")
}

/// Raven `Q3_SetIgnorePain`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3727-3731`
pub fn Q3_SetIgnorePain(
    entID: c_int,
    data: qboolean,
) {
    todo!("Port Q3_SetIgnorePain — oracle/oracle/codemp/game/g_ICARUScb.c:3727")
}

/// Raven `Q3_SetIgnoreEnemies`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3740-3744`
pub fn Q3_SetIgnoreEnemies(
    entID: c_int,
    data: qboolean,
) {
    todo!("Port Q3_SetIgnoreEnemies — oracle/oracle/codemp/game/g_ICARUScb.c:3740")
}

/// Raven `Q3_SetIgnoreAlerts`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3753-3757`
pub fn Q3_SetIgnoreAlerts(
    entID: c_int,
    data: qboolean,
) {
    todo!("Port Q3_SetIgnoreAlerts — oracle/oracle/codemp/game/g_ICARUScb.c:3753")
}

/// Raven `Q3_SetNoTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3767-3781`
pub fn Q3_SetNoTarget(
    entID: c_int,
    data: qboolean,
) {
    todo!("Port Q3_SetNoTarget — oracle/oracle/codemp/game/g_ICARUScb.c:3767")
}

/// Raven `Q3_SetDontShoot`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3790-3794`
pub fn Q3_SetDontShoot(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetDontShoot — oracle/oracle/codemp/game/g_ICARUScb.c:3790")
}

/// Raven `Q3_SetDontFire`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3803-3807`
pub fn Q3_SetDontFire(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetDontFire — oracle/oracle/codemp/game/g_ICARUScb.c:3803")
}

/// Raven `Q3_SetFireWeapon`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3816-3820`
pub fn Q3_SetFireWeapon(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetFireWeapon — oracle/oracle/codemp/game/g_ICARUScb.c:3816")
}

/// Raven `Q3_SetInactive`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3830-3848`
pub fn Q3_SetInactive(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetInactive — oracle/oracle/codemp/game/g_ICARUScb.c:3830")
}

/// Raven `Q3_SetFuncUsableVisible`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3857-3880`
pub fn Q3_SetFuncUsableVisible(
    entID: c_int,
    visible: qboolean,
) {
    todo!("Port Q3_SetFuncUsableVisible — oracle/oracle/codemp/game/g_ICARUScb.c:3857")
}

/// Raven `Q3_SetLockedEnemy`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3889-3893`
pub fn Q3_SetLockedEnemy(
    entID: c_int,
    locked: qboolean,
) {
    todo!("Port Q3_SetLockedEnemy — oracle/oracle/codemp/game/g_ICARUScb.c:3889")
}

/// Raven `Q3_SetCinematicSkipScript`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3903-3907`
pub fn Q3_SetCinematicSkipScript(
    scriptname: *mut c_char,
) {
    todo!("Port Q3_SetCinematicSkipScript — oracle/oracle/codemp/game/g_ICARUScb.c:3903")
}

/// Raven `Q3_SetNoMindTrick`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3916-3920`
pub fn Q3_SetNoMindTrick(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetNoMindTrick — oracle/oracle/codemp/game/g_ICARUScb.c:3916")
}

/// Raven `Q3_SetCrouched`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3929-3933`
pub fn Q3_SetCrouched(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetCrouched — oracle/oracle/codemp/game/g_ICARUScb.c:3929")
}

/// Raven `Q3_SetWalking`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3942-3967`
pub fn Q3_SetWalking(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetWalking — oracle/oracle/codemp/game/g_ICARUScb.c:3942")
}

/// Raven `Q3_SetRunning`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3976-3980`
pub fn Q3_SetRunning(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetRunning — oracle/oracle/codemp/game/g_ICARUScb.c:3976")
}

/// Raven `Q3_SetForcedMarch`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:3989-3993`
pub fn Q3_SetForcedMarch(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetForcedMarch — oracle/oracle/codemp/game/g_ICARUScb.c:3989")
}

/// Raven `Q3_SetChaseEnemies`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4001-4005`
pub fn Q3_SetChaseEnemies(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetChaseEnemies — oracle/oracle/codemp/game/g_ICARUScb.c:4001")
}

/// Raven `Q3_SetLookForEnemies`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4015-4019`
pub fn Q3_SetLookForEnemies(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetLookForEnemies — oracle/oracle/codemp/game/g_ICARUScb.c:4015")
}

/// Raven `Q3_SetFaceMoveDir`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4027-4031`
pub fn Q3_SetFaceMoveDir(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetFaceMoveDir — oracle/oracle/codemp/game/g_ICARUScb.c:4027")
}

/// Raven `Q3_SetAltFire`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4040-4044`
pub fn Q3_SetAltFire(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetAltFire — oracle/oracle/codemp/game/g_ICARUScb.c:4040")
}

/// Raven `Q3_SetDontFlee`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4053-4057`
pub fn Q3_SetDontFlee(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetDontFlee — oracle/oracle/codemp/game/g_ICARUScb.c:4053")
}

/// Raven `Q3_SetNoResponse`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4066-4070`
pub fn Q3_SetNoResponse(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetNoResponse — oracle/oracle/codemp/game/g_ICARUScb.c:4066")
}

/// Raven `Q3_SetCombatTalk`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4079-4083`
pub fn Q3_SetCombatTalk(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetCombatTalk — oracle/oracle/codemp/game/g_ICARUScb.c:4079")
}

/// Raven `Q3_SetAlertTalk`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4092-4096`
pub fn Q3_SetAlertTalk(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetAlertTalk — oracle/oracle/codemp/game/g_ICARUScb.c:4092")
}

/// Raven `Q3_SetUseCpNearest`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4105-4109`
pub fn Q3_SetUseCpNearest(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetUseCpNearest — oracle/oracle/codemp/game/g_ICARUScb.c:4105")
}

/// Raven `Q3_SetNoForce`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4118-4122`
pub fn Q3_SetNoForce(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetNoForce — oracle/oracle/codemp/game/g_ICARUScb.c:4118")
}

/// Raven `Q3_SetNoAcrobatics`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4131-4135`
pub fn Q3_SetNoAcrobatics(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetNoAcrobatics — oracle/oracle/codemp/game/g_ICARUScb.c:4131")
}

/// Raven `Q3_SetUseSubtitles`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4144-4148`
pub fn Q3_SetUseSubtitles(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetUseSubtitles — oracle/oracle/codemp/game/g_ICARUScb.c:4144")
}

/// Raven `Q3_SetNoFallToDeath`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4157-4161`
pub fn Q3_SetNoFallToDeath(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetNoFallToDeath — oracle/oracle/codemp/game/g_ICARUScb.c:4157")
}

/// Raven `Q3_SetDismemberable`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4170-4174`
pub fn Q3_SetDismemberable(
    entID: c_int,
    dismemberable: qboolean,
) {
    todo!("Port Q3_SetDismemberable — oracle/oracle/codemp/game/g_ICARUScb.c:4170")
}

/// Raven `Q3_SetMoreLight`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4184-4188`
pub fn Q3_SetMoreLight(
    entID: c_int,
    add: qboolean,
) {
    todo!("Port Q3_SetMoreLight — oracle/oracle/codemp/game/g_ICARUScb.c:4184")
}

/// Raven `Q3_SetUndying`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4197-4201`
pub fn Q3_SetUndying(
    entID: c_int,
    undying: qboolean,
) {
    todo!("Port Q3_SetUndying — oracle/oracle/codemp/game/g_ICARUScb.c:4197")
}

/// Raven `Q3_SetInvincible`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4210-4214`
pub fn Q3_SetInvincible(
    entID: c_int,
    invincible: qboolean,
) {
    todo!("Port Q3_SetInvincible — oracle/oracle/codemp/game/g_ICARUScb.c:4210")
}

/// Raven `Q3_SetForceInvincible`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4224-4228`
pub fn Q3_SetForceInvincible(
    entID: c_int,
    forceInv: qboolean,
) {
    todo!("Port Q3_SetForceInvincible — oracle/oracle/codemp/game/g_ICARUScb.c:4224")
}

/// Raven `Q3_SetNoAvoid`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4237-4261`
pub fn Q3_SetNoAvoid(
    entID: c_int,
    noAvoid: qboolean,
) {
    todo!("Port Q3_SetNoAvoid — oracle/oracle/codemp/game/g_ICARUScb.c:4237")
}

/// Raven `SolidifyOwner`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4271-4295`
pub fn SolidifyOwner(
    self_: *mut gentity_t,
) {
    todo!("Port SolidifyOwner — oracle/oracle/codemp/game/g_ICARUScb.c:4271")
}

/// Raven `Q3_SetSolid`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4305-4345`
pub fn Q3_SetSolid(
    entID: c_int,
    solid: qboolean,
) -> qboolean {
    todo!("Port Q3_SetSolid — oracle/oracle/codemp/game/g_ICARUScb.c:4305")
}

/// Raven `Q3_SetForwardMove`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4354-4372`
pub fn Q3_SetForwardMove(
    entID: c_int,
    fmoveVal: c_int,
) {
    todo!("Port Q3_SetForwardMove — oracle/oracle/codemp/game/g_ICARUScb.c:4354")
}

/// Raven `Q3_SetRightMove`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4381-4399`
pub fn Q3_SetRightMove(
    entID: c_int,
    rmoveVal: c_int,
) {
    todo!("Port Q3_SetRightMove — oracle/oracle/codemp/game/g_ICARUScb.c:4381")
}

/// Raven `Q3_SetLockAngle`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4408-4445`
pub fn Q3_SetLockAngle(
    entID: c_int,
    lockAngle: *const c_char,
) {
    todo!("Port Q3_SetLockAngle — oracle/oracle/codemp/game/g_ICARUScb.c:4408")
}

/// Raven `Q3_CameraGroup`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4455-4459`
pub fn Q3_CameraGroup(
    entID: c_int,
    camG: *mut c_char,
) {
    todo!("Port Q3_CameraGroup — oracle/oracle/codemp/game/g_ICARUScb.c:4455")
}

/// Raven `Q3_CameraGroupZOfs`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4468-4472`
pub fn Q3_CameraGroupZOfs(
    camGZOfs: f32,
) {
    todo!("Port Q3_CameraGroupZOfs — oracle/oracle/codemp/game/g_ICARUScb.c:4468")
}

/// Raven `Q3_CameraGroupTag`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4480-4484`
pub fn Q3_CameraGroupTag(
    camGTag: *mut c_char,
) {
    todo!("Port Q3_CameraGroupTag — oracle/oracle/codemp/game/g_ICARUScb.c:4480")
}

/// Raven `Q3_RemoveRHandModel`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4491-4494`
pub fn Q3_RemoveRHandModel(
    entID: c_int,
    addModel: *mut c_char,
) {
    todo!("Port Q3_RemoveRHandModel — oracle/oracle/codemp/game/g_ICARUScb.c:4491")
}

/// Raven `Q3_AddRHandModel`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4501-4504`
pub fn Q3_AddRHandModel(
    entID: c_int,
    addModel: *mut c_char,
) {
    todo!("Port Q3_AddRHandModel — oracle/oracle/codemp/game/g_ICARUScb.c:4501")
}

/// Raven `Q3_AddLHandModel`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4511-4514`
pub fn Q3_AddLHandModel(
    entID: c_int,
    addModel: *mut c_char,
) {
    todo!("Port Q3_AddLHandModel — oracle/oracle/codemp/game/g_ICARUScb.c:4511")
}

/// Raven `Q3_RemoveLHandModel`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4521-4524`
pub fn Q3_RemoveLHandModel(
    entID: c_int,
    addModel: *mut c_char,
) {
    todo!("Port Q3_RemoveLHandModel — oracle/oracle/codemp/game/g_ICARUScb.c:4521")
}

/// Raven `Q3_LookTarget`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4533-4537`
pub fn Q3_LookTarget(
    entID: c_int,
    targetName: *mut c_char,
) {
    todo!("Port Q3_LookTarget — oracle/oracle/codemp/game/g_ICARUScb.c:4533")
}

/// Raven `Q3_Face`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4546-4549`
pub fn Q3_Face(
    entID: c_int,
    expression: c_int,
    holdtime: f32,
) {
    todo!("Port Q3_Face — oracle/oracle/codemp/game/g_ICARUScb.c:4546")
}

/// Raven `Q3_SetLocation`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4560-4564`
pub fn Q3_SetLocation(
    entID: c_int,
    location: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetLocation — oracle/oracle/codemp/game/g_ICARUScb.c:4560")
}

/// Raven `Q3_SetPlayerLocked`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4576-4579`
pub fn Q3_SetPlayerLocked(
    entID: c_int,
    locked: qboolean,
) {
    todo!("Port Q3_SetPlayerLocked — oracle/oracle/codemp/game/g_ICARUScb.c:4576")
}

/// Raven `Q3_SetLockPlayerWeapons`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4590-4593`
pub fn Q3_SetLockPlayerWeapons(
    entID: c_int,
    locked: qboolean,
) {
    todo!("Port Q3_SetLockPlayerWeapons — oracle/oracle/codemp/game/g_ICARUScb.c:4590")
}

/// Raven `Q3_SetNoImpactDamage`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4605-4608`
pub fn Q3_SetNoImpactDamage(
    entID: c_int,
    noImp: qboolean,
) {
    todo!("Port Q3_SetNoImpactDamage — oracle/oracle/codemp/game/g_ICARUScb.c:4605")
}

/// Raven `Q3_SetBehaviorSet`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4617-4708`
pub fn Q3_SetBehaviorSet(
    entID: c_int,
    toSet: c_int,
    scriptname: *const c_char,
) -> qboolean {
    todo!("Port Q3_SetBehaviorSet — oracle/oracle/codemp/game/g_ICARUScb.c:4617")
}

/// Raven `Q3_SetDelayScriptTime`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4717-4720`
pub fn Q3_SetDelayScriptTime(
    entID: c_int,
    delayTime: c_int,
) {
    todo!("Port Q3_SetDelayScriptTime — oracle/oracle/codemp/game/g_ICARUScb.c:4717")
}

/// Raven `Q3_SetPlayerUsable`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4734-4752`
pub fn Q3_SetPlayerUsable(
    entID: c_int,
    usable: qboolean,
) {
    todo!("Port Q3_SetPlayerUsable — oracle/oracle/codemp/game/g_ICARUScb.c:4734")
}

/// Raven `Q3_SetDisableShaderAnims`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4763-4767`
pub fn Q3_SetDisableShaderAnims(
    entID: c_int,
    disabled: c_int,
) {
    todo!("Port Q3_SetDisableShaderAnims — oracle/oracle/codemp/game/g_ICARUScb.c:4763")
}

/// Raven `Q3_SetShaderAnim`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4778-4782`
pub fn Q3_SetShaderAnim(
    entID: c_int,
    disabled: c_int,
) {
    todo!("Port Q3_SetShaderAnim — oracle/oracle/codemp/game/g_ICARUScb.c:4778")
}

/// Raven `Q3_SetStartFrame`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4793-4796`
pub fn Q3_SetStartFrame(
    entID: c_int,
    startFrame: c_int,
) {
    todo!("Port Q3_SetStartFrame — oracle/oracle/codemp/game/g_ICARUScb.c:4793")
}

/// Raven `Q3_SetEndFrame`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4808-4811`
pub fn Q3_SetEndFrame(
    entID: c_int,
    endFrame: c_int,
) {
    todo!("Port Q3_SetEndFrame — oracle/oracle/codemp/game/g_ICARUScb.c:4808")
}

/// Raven `Q3_SetAnimFrame`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4822-4825`
pub fn Q3_SetAnimFrame(
    entID: c_int,
    animFrame: c_int,
) {
    todo!("Port Q3_SetAnimFrame — oracle/oracle/codemp/game/g_ICARUScb.c:4822")
}

/// Raven `Q3_SetLoopAnim`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4836-4839`
pub fn Q3_SetLoopAnim(
    entID: c_int,
    loopAnim: qboolean,
) {
    todo!("Port Q3_SetLoopAnim — oracle/oracle/codemp/game/g_ICARUScb.c:4836")
}

/// Raven `Q3_SetShields`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4851-4855`
pub fn Q3_SetShields(
    entID: c_int,
    shields: qboolean,
) {
    todo!("Port Q3_SetShields — oracle/oracle/codemp/game/g_ICARUScb.c:4851")
}

/// Raven `Q3_SetSaberActive`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4866-4889`
pub fn Q3_SetSaberActive(
    entID: c_int,
    active: qboolean,
) {
    todo!("Port Q3_SetSaberActive — oracle/oracle/codemp/game/g_ICARUScb.c:4866")
}

/// Raven `Q3_SetNoKnockback`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4900-4918`
pub fn Q3_SetNoKnockback(
    entID: c_int,
    noKnockback: qboolean,
) {
    todo!("Port Q3_SetNoKnockback — oracle/oracle/codemp/game/g_ICARUScb.c:4900")
}

/// Raven `Q3_SetCleanDamagingEnts`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4927-4931`
pub fn Q3_SetCleanDamagingEnts() {
    todo!("Port Q3_SetCleanDamagingEnts — oracle/oracle/codemp/game/g_ICARUScb.c:4927")
}

/// Raven `SetTextColor`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4942-4946`
pub fn SetTextColor(
    textcolor: vec4_t,
    color: *const c_char,
) {
    todo!("Port SetTextColor — oracle/oracle/codemp/game/g_ICARUScb.c:4942")
}

/// Raven `Q3_SetCaptionTextColor`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4955-4958`
pub fn Q3_SetCaptionTextColor(
    color: *const c_char,
) {
    todo!("Port Q3_SetCaptionTextColor — oracle/oracle/codemp/game/g_ICARUScb.c:4955")
}

/// Raven `Q3_SetCenterTextColor`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4967-4970`
pub fn Q3_SetCenterTextColor(
    color: *const c_char,
) {
    todo!("Port Q3_SetCenterTextColor — oracle/oracle/codemp/game/g_ICARUScb.c:4967")
}

/// Raven `Q3_SetScrollTextColor`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4979-4982`
pub fn Q3_SetScrollTextColor(
    color: *const c_char,
) {
    todo!("Port Q3_SetScrollTextColor — oracle/oracle/codemp/game/g_ICARUScb.c:4979")
}

/// Raven `Q3_ScrollText`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:4991-4997`
pub fn Q3_ScrollText(
    id: *const c_char,
) {
    todo!("Port Q3_ScrollText — oracle/oracle/codemp/game/g_ICARUScb.c:4991")
}

/// Raven `Q3_LCARSText`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:5006-5012`
pub fn Q3_LCARSText(
    id: *const c_char,
) {
    todo!("Port Q3_LCARSText — oracle/oracle/codemp/game/g_ICARUScb.c:5006")
}

/// Raven `Q3_Set`.
///
/// Source: `oracle/oracle/codemp/game/g_ICARUScb.c:5018-6074`
pub fn Q3_Set(
    taskID: c_int,
    entID: c_int,
    type_name: *const c_char,
    data: *const c_char,
) -> qboolean {
    todo!("Port Q3_Set — oracle/oracle/codemp/game/g_ICARUScb.c:5018")
}
