//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/g_items.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `adjustRespawnTime`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:47-88`
pub fn adjustRespawnTime(
    preRespawnTime: f32,
    itemType: c_int,
    itemTag: c_int,
) -> c_int {
    todo!("Port adjustRespawnTime — oracle/oracle/codemp/game/g_items.c:47")
}

/// Raven `ShieldRemove`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:108-119`
pub fn ShieldRemove(
    self_: *mut gentity_t,
) {
    todo!("Port ShieldRemove — oracle/oracle/codemp/game/g_items.c:108")
}

/// Raven `ShieldThink`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:123-141`
pub fn ShieldThink(
    self_: *mut gentity_t,
) {
    todo!("Port ShieldThink — oracle/oracle/codemp/game/g_items.c:123")
}

/// Raven `ShieldDie`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:145-151`
pub fn ShieldDie(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    todo!("Port ShieldDie — oracle/oracle/codemp/game/g_items.c:145")
}

/// Raven `ShieldPain`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:155-167`
pub fn ShieldPain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    todo!("Port ShieldPain — oracle/oracle/codemp/game/g_items.c:155")
}

/// Raven `ShieldGoSolid`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:171-207`
pub fn ShieldGoSolid(
    self_: *mut gentity_t,
) {
    todo!("Port ShieldGoSolid — oracle/oracle/codemp/game/g_items.c:171")
}

/// Raven `ShieldGoNotSolid`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:211-226`
pub fn ShieldGoNotSolid(
    self_: *mut gentity_t,
) {
    todo!("Port ShieldGoNotSolid — oracle/oracle/codemp/game/g_items.c:211")
}

/// Raven `ShieldTouch`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:230-250`
pub fn ShieldTouch(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port ShieldTouch — oracle/oracle/codemp/game/g_items.c:230")
}

/// Raven `CreateShield`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:254-380`
pub fn CreateShield(
    ent: *mut gentity_t,
) {
    todo!("Port CreateShield — oracle/oracle/codemp/game/g_items.c:254")
}

/// Raven `PlaceShield`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:382-470`
pub fn PlaceShield(
    playerent: *mut gentity_t,
) -> qboolean {
    todo!("Port PlaceShield — oracle/oracle/codemp/game/g_items.c:382")
}

/// Raven `ItemUse_Binoculars`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:472-502`
pub fn ItemUse_Binoculars(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_Binoculars — oracle/oracle/codemp/game/g_items.c:472")
}

/// Raven `ItemUse_Shield`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:504-507`
pub fn ItemUse_Shield(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_Shield — oracle/oracle/codemp/game/g_items.c:504")
}

/// Raven `SentryTouch`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:515-518`
pub fn SentryTouch(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port SentryTouch — oracle/oracle/codemp/game/g_items.c:515")
}

/// Raven `pas_fire`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:521-542`
pub fn pas_fire(
    ent: *mut gentity_t,
) {
    todo!("Port pas_fire — oracle/oracle/codemp/game/g_items.c:521")
}

/// Raven `pas_find_enemies`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:547-639`
pub fn pas_find_enemies(
    self_: *mut gentity_t,
) -> qboolean {
    todo!("Port pas_find_enemies — oracle/oracle/codemp/game/g_items.c:547")
}

/// Raven `pas_adjust_enemy`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:642-695`
pub fn pas_adjust_enemy(
    ent: *mut gentity_t,
) {
    todo!("Port pas_adjust_enemy — oracle/oracle/codemp/game/g_items.c:642")
}

/// Raven `sentryExpire`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:702-705`
pub fn sentryExpire(
    self_: *mut gentity_t,
) {
    todo!("Port sentryExpire — oracle/oracle/codemp/game/g_items.c:702")
}

/// Raven `pas_think`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:708-937`
pub fn pas_think(
    ent: *mut gentity_t,
) {
    todo!("Port pas_think — oracle/oracle/codemp/game/g_items.c:708")
}

/// Raven `turret_die`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:940-973`
pub fn turret_die(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    todo!("Port turret_die — oracle/oracle/codemp/game/g_items.c:940")
}

/// Raven `SP_PAS`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:978-1011`
pub fn SP_PAS(
    base: *mut gentity_t,
) {
    todo!("Port SP_PAS — oracle/oracle/codemp/game/g_items.c:978")
}

/// Raven `ItemUse_Sentry`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1014-1093`
pub fn ItemUse_Sentry(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_Sentry — oracle/oracle/codemp/game/g_items.c:1014")
}

/// Raven `ItemUse_Seeker`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1096-1125`
pub fn ItemUse_Seeker(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_Seeker — oracle/oracle/codemp/game/g_items.c:1096")
}

/// Raven `MedPackGive`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1127-1152`
pub fn MedPackGive(
    ent: *mut gentity_t,
    amount: c_int,
) {
    todo!("Port MedPackGive — oracle/oracle/codemp/game/g_items.c:1127")
}

/// Raven `ItemUse_MedPack_Big`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1154-1157`
pub fn ItemUse_MedPack_Big(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_MedPack_Big — oracle/oracle/codemp/game/g_items.c:1154")
}

/// Raven `ItemUse_MedPack`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1159-1162`
pub fn ItemUse_MedPack(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_MedPack — oracle/oracle/codemp/game/g_items.c:1159")
}

/// Raven `Jetpack_Off`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1165-1175`
pub fn Jetpack_Off(
    ent: *mut gentity_t,
) {
    todo!("Port Jetpack_Off — oracle/oracle/codemp/game/g_items.c:1165")
}

/// Raven `Jetpack_On`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1177-1199`
pub fn Jetpack_On(
    ent: *mut gentity_t,
) {
    todo!("Port Jetpack_On — oracle/oracle/codemp/game/g_items.c:1177")
}

/// Raven `ItemUse_Jetpack`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1201-1234`
pub fn ItemUse_Jetpack(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_Jetpack — oracle/oracle/codemp/game/g_items.c:1201")
}

/// Raven `ItemUse_UseCloak`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1239-1272`
pub fn ItemUse_UseCloak(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_UseCloak — oracle/oracle/codemp/game/g_items.c:1239")
}

/// Raven `SpecialItemThink`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1277-1293`
pub fn SpecialItemThink(
    ent: *mut gentity_t,
) {
    todo!("Port SpecialItemThink — oracle/oracle/codemp/game/g_items.c:1277")
}

/// Raven `G_SpecialSpawnItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1295-1331`
pub fn G_SpecialSpawnItem(
    ent: *mut gentity_t,
    item: *mut gitem_t,
) {
    todo!("Port G_SpecialSpawnItem — oracle/oracle/codemp/game/g_items.c:1295")
}

/// Raven `G_PrecacheDispensers`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1336-1351`
pub fn G_PrecacheDispensers() {
    todo!("Port G_PrecacheDispensers — oracle/oracle/codemp/game/g_items.c:1336")
}

/// Raven `ItemUse_UseDisp`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1353-1410`
pub fn ItemUse_UseDisp(
    ent: *mut gentity_t,
    r#type: c_int,
) {
    todo!("Port ItemUse_UseDisp — oracle/oracle/codemp/game/g_items.c:1353")
}

/// Raven `EWebDisattach`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1417-1431`
pub fn EWebDisattach(
    owner: *mut gentity_t,
    eweb: *mut gentity_t,
) {
    todo!("Port EWebDisattach — oracle/oracle/codemp/game/g_items.c:1417")
}

/// Raven `EWebPrecache`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1434-1439`
pub fn EWebPrecache() {
    todo!("Port EWebPrecache — oracle/oracle/codemp/game/g_items.c:1434")
}

/// Raven `EWebDie`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1449-1481`
pub fn EWebDie(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    todo!("Port EWebDie — oracle/oracle/codemp/game/g_items.c:1449")
}

/// Raven `EWebPain`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1484-1496`
pub fn EWebPain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    todo!("Port EWebPain — oracle/oracle/codemp/game/g_items.c:1484")
}

/// Raven `EWeb_SetBoneAngles`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1499-1598`
pub fn EWeb_SetBoneAngles(
    ent: *mut gentity_t,
    bone: *mut c_char,
    angles: vec3_t,
) {
    todo!("Port EWeb_SetBoneAngles — oracle/oracle/codemp/game/g_items.c:1499")
}

/// Raven `EWeb_SetBoneAnim`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1601-1620`
pub fn EWeb_SetBoneAnim(
    eweb: *mut gentity_t,
    startFrame: c_int,
    endFrame: c_int,
) {
    todo!("Port EWeb_SetBoneAnim — oracle/oracle/codemp/game/g_items.c:1601")
}

/// Raven `EWebFire`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1624-1664`
pub fn EWebFire(
    owner: *mut gentity_t,
    eweb: *mut gentity_t,
) {
    todo!("Port EWebFire — oracle/oracle/codemp/game/g_items.c:1624")
}

/// Raven `EWebPositionUser`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1667-1732`
pub fn EWebPositionUser(
    owner: *mut gentity_t,
    eweb: *mut gentity_t,
) {
    todo!("Port EWebPositionUser — oracle/oracle/codemp/game/g_items.c:1667")
}

/// Raven `EWebUpdateBoneAngles`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1735-1769`
pub fn EWebUpdateBoneAngles(
    owner: *mut gentity_t,
    eweb: *mut gentity_t,
) {
    todo!("Port EWebUpdateBoneAngles — oracle/oracle/codemp/game/g_items.c:1735")
}

/// Raven `EWebThink`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1776-1854`
pub fn EWebThink(
    self_: *mut gentity_t,
) {
    todo!("Port EWebThink — oracle/oracle/codemp/game/g_items.c:1776")
}

/// Raven `EWeb_Create`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1859-1980`
pub fn EWeb_Create(
    spawner: *mut gentity_t,
) -> *mut gentity_t {
    todo!("Port EWeb_Create — oracle/oracle/codemp/game/g_items.c:1859")
}

/// Raven `ItemUse_UseEWeb`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:1984-2018`
pub fn ItemUse_UseEWeb(
    ent: *mut gentity_t,
) {
    todo!("Port ItemUse_UseEWeb — oracle/oracle/codemp/game/g_items.c:1984")
}

/// Raven `Pickup_Powerup`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2024-2100`
pub fn Pickup_Powerup(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Powerup — oracle/oracle/codemp/game/g_items.c:2024")
}

/// Raven `Pickup_Holdable`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2104-2113`
pub fn Pickup_Holdable(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Holdable — oracle/oracle/codemp/game/g_items.c:2104")
}

/// Raven `Add_Ammo`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2118-2128`
pub fn Add_Ammo(
    ent: *mut gentity_t,
    weapon: c_int,
    count: c_int,
) {
    todo!("Port Add_Ammo — oracle/oracle/codemp/game/g_items.c:2118")
}

/// Raven `Pickup_Ammo`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2130-2175`
pub fn Pickup_Ammo(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Ammo — oracle/oracle/codemp/game/g_items.c:2130")
}

/// Raven `Pickup_Weapon`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2180-2232`
pub fn Pickup_Weapon(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Weapon — oracle/oracle/codemp/game/g_items.c:2180")
}

/// Raven `Pickup_Health`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2237-2266`
pub fn Pickup_Health(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Health — oracle/oracle/codemp/game/g_items.c:2237")
}

/// Raven `Pickup_Armor`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2270-2279`
pub fn Pickup_Armor(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) -> c_int {
    todo!("Port Pickup_Armor — oracle/oracle/codemp/game/g_items.c:2270")
}

/// Raven `RespawnItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2288-2334`
pub fn RespawnItem(
    ent: *mut gentity_t,
) {
    todo!("Port RespawnItem — oracle/oracle/codemp/game/g_items.c:2288")
}

/// Raven `CheckItemCanBePickedUpByNPC`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2336-2355`
pub fn CheckItemCanBePickedUpByNPC(
    item: *mut gentity_t,
    pickerupper: *mut gentity_t,
) -> qboolean {
    todo!("Port CheckItemCanBePickedUpByNPC — oracle/oracle/codemp/game/g_items.c:2336")
}

/// Raven `Touch_Item`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2362-2646`
pub fn Touch_Item(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_Item — oracle/oracle/codemp/game/g_items.c:2362")
}

/// Raven `LaunchItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2658-2733`
pub fn LaunchItem(
    item: *mut gitem_t,
    origin: vec3_t,
    velocity: vec3_t,
) -> *mut gentity_t {
    todo!("Port LaunchItem — oracle/oracle/codemp/game/g_items.c:2658")
}

/// Raven `Drop_Item`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2742-2755`
pub fn Drop_Item(
    ent: *mut gentity_t,
    item: *mut gitem_t,
    angle: f32,
) -> *mut gentity_t {
    todo!("Port Drop_Item — oracle/oracle/codemp/game/g_items.c:2742")
}

/// Raven `Use_Item`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2765-2767`
pub fn Use_Item(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port Use_Item — oracle/oracle/codemp/game/g_items.c:2765")
}

/// Raven `FinishSpawningItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2779-2963`
pub fn FinishSpawningItem(
    ent: *mut gentity_t,
) {
    todo!("Port FinishSpawningItem — oracle/oracle/codemp/game/g_items.c:2779")
}

/// Raven `G_CheckTeamItems`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2973-2991`
pub fn G_CheckTeamItems() {
    todo!("Port G_CheckTeamItems — oracle/oracle/codemp/game/g_items.c:2973")
}

/// Raven `ClearRegisteredItems`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:2998-3011`
pub fn ClearRegisteredItems() {
    todo!("Port ClearRegisteredItems — oracle/oracle/codemp/game/g_items.c:2998")
}

/// Raven `RegisterItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3020-3025`
pub fn RegisterItem(
    item: *mut gitem_t,
) {
    todo!("Port RegisterItem — oracle/oracle/codemp/game/g_items.c:3020")
}

/// Raven `SaveRegisteredItems`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3036-3054`
pub fn SaveRegisteredItems() {
    todo!("Port SaveRegisteredItems — oracle/oracle/codemp/game/g_items.c:3036")
}

/// Raven `G_ItemDisabled`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3061-3067`
pub fn G_ItemDisabled(
    item: *mut gitem_t,
) -> c_int {
    todo!("Port G_ItemDisabled — oracle/oracle/codemp/game/g_items.c:3061")
}

/// Raven `G_SpawnItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3079-3121`
pub fn G_SpawnItem(
    ent: *mut gentity_t,
    item: *mut gitem_t,
) {
    todo!("Port G_SpawnItem — oracle/oracle/codemp/game/g_items.c:3079")
}

/// Raven `G_BounceItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3130-3174`
pub fn G_BounceItem(
    ent: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port G_BounceItem — oracle/oracle/codemp/game/g_items.c:3130")
}

/// Raven `G_RunItem`.
///
/// Source: `oracle/oracle/codemp/game/g_items.c:3183-3242`
pub fn G_RunItem(
    ent: *mut gentity_t,
) {
    todo!("Port G_RunItem — oracle/oracle/codemp/game/g_items.c:3183")
}
