// PORT-COMPLETE: g_main.c 0/49
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/g_main.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
//!
//! Every function in this file reads or writes Raven's file-scope game
//! state (`level`, `g_entities`, `g_clients`, the ~136 `vmCvar_t` handles
//! now grouped as `GameCvars`, or other g_main.c file-scope globals like
//! `gDoSlowMoDuel`/`g_LastFrameTime`) per fork ruling 1
//! (`docs/handoffs/jampgame-fork-discovery.md`: "GameWorld fields, cvars
//! grouped in GameCvars"). The staged raw-pointer skeleton below gives
//! none of these bodies a `&mut GameWorld`/engine handle to reach that
//! state through, so — exactly the `raw-ptr-skeleton-no-world-handle`
//! precedent already used file-wide in `g_combat.rs`/others — every
//! function here is parked on that same escalation. A handful
//! (`G_Printf`/`G_Error`/`Com_Error`/`Com_Printf`/`G_LogPrintf`) are
//! additionally variadic (`variadic-c-abi`, per `g_ICARUScb.rs`
//! precedent). None can be ported before that seam question is settled.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

// The QVM entry (`vmMain`) and `G_InitGame` / `G_ShutdownGame` are the
// slice-0 live code, kept as-is: `vmMain` is the shell + the
// `impl Dispatch<C> for GameContext` seam (`world/game_context.rs`);
// the two commands dispatch to `crate::g_init_game::g_init_game` and
// `crate::g_shutdown_game::g_shutdown_game`. The skeleton duplicates
// were dropped here (SEAM-D8 / slice-0).
// Source: `oracle/oracle/codemp/game/g_main.c:515-696,897,1128`

// PORT-ESCALATION(variadic-c-abi): G_Printf takes C varargs (`...`); the
// skeleton itself flags "seam decision pending" — what Rust shape represents
// a variadic printf-style entry point at the ABI seam? Additionally reaches
// no GameWorld handle to thread `com_developer`/etc. through
// (raw-ptr-skeleton-no-world-handle).
/// Raven `G_Printf`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:703-712`
pub fn G_Printf(
    ctx: GameContext<'_>,
    fmt: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port G_Printf — parked (variadic-c-abi): oracle/oracle/codemp/game/g_main.c:703")
}

// PORT-ESCALATION(variadic-c-abi): same as G_Printf — variadic + no world
// handle to reach `trap_Error`/level state through.
/// Raven `G_Error`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:714-723`
pub fn G_Error(
    ctx: GameContext<'_>,
    fmt: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port G_Error — parked (variadic-c-abi): oracle/oracle/codemp/game/g_main.c:714")
}

/// Raven `G_FindTeams`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:736-781`
pub fn G_FindTeams(ctx: GameContext<'_>) {
    use std::ffi::CStr;
    // Raw-pointer walk (fork ruling 4: audited unsafe seam helper for the
    // disjoint-but-aliasing-shaped `e`/`e2` double loop over the same array).
    unsafe {
        let world = &mut *ctx.world;
        let num_entities = world.level.num_entities;
        let base: *mut gentity_t = world.entities.as_mut_ptr();
        let mut i: c_int = 1;
        while i < num_entities {
            let e = &mut *base.add(i as usize);
            if e.inuse != QFALSE && !e.team.is_null() && e.flags & FL_TEAMSLAVE == 0 {
                // CONTENTS_TRIGGER not yet ported as a const anywhere in this
                // crate graph (precedent: g_mover.rs `G_FindDoorTrigger`,
                // g_nav.rs) — the "triggers never link up in teams" skip is
                // therefore omitted.
                //TODO: Port CONTENTS_TRIGGER
                // Source: oracle/oracle/codemp/game/q_shared.h (CONTENTS_* bitmask)
                e.teammaster = e as *mut gentity_t;
                let mut j = i + 1;
                while j < num_entities {
                    let e2 = &mut *base.add(j as usize);
                    if e2.inuse != QFALSE
                        && !e2.team.is_null()
                        && e2.flags & FL_TEAMSLAVE == 0
                        && CStr::from_ptr(e.team).to_bytes() == CStr::from_ptr(e2.team).to_bytes()
                    {
                        e2.teamchain = e.teamchain;
                        e.teamchain = e2 as *mut gentity_t;
                        e2.teammaster = e as *mut gentity_t;
                        e2.flags |= FL_TEAMSLAVE;
                        // make sure that targets only point at the master
                        if !e2.targetname.is_null() {
                            e.targetname = e2.targetname;
                            e2.targetname = std::ptr::null_mut();
                        }
                    }
                    j += 1;
                }
            }
            i += 1;
        }
    }
    // G_Printf ("%i teams with %i entities\n", c, c2); — commented out in oracle.
}

/// Raven `G_RemapTeamShaders`.
///
/// Raven's whole body is `#if 0`-guarded dead code (team-shader remap via
/// `AddRemap`/`BuildShaderStateConfig`, neither ported) — the live function
/// faithfully does nothing.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:783-795`
pub fn G_RemapTeamShaders() {}

// PORT-ESCALATION(unresolved-cvar-flags): `GAME_CVAR_TABLE` (game_cvars.rs)
// carries each row's `CVAR_*` registration flags as a symbolic expression
// string ("CVAR_SERVERINFO | CVAR_LATCH", …) — the `CVAR_*` bit constants
// themselves are not yet ported anywhere in the crate graph, so the
// per-field `vmCvar_t` pointer + numeric-flags call this loop needs to make
// to `trap::Cvar_Register` cannot be built without inventing flag values.
/// Raven `G_RegisterCvars`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:803-845`
pub fn G_RegisterCvars(ctx: GameContext<'_>) {
    todo!("Port G_RegisterCvars — parked (unresolved-cvar-flags: CVAR_* consts): oracle/oracle/codemp/game/g_main.c:803")
}

// PORT-ESCALATION(unresolved-cvar-flags): same table dependency as
// `G_RegisterCvars` — `cv->vmCvar` field dispatch needs a per-row typed
// accessor into `GameCvars` (the table's `field: Option<&'static str>` is a
// name, not a `&mut vmCvar_t` — no reflection in Rust) plus the unported
// `CVAR_*` flags for the `teamShader`/`trackChange` branches' downstream use.
/// Raven `G_UpdateCvars`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:852-879`
pub fn G_UpdateCvars(ctx: GameContext<'_>) {
    todo!("Port G_UpdateCvars — parked (unresolved-cvar-flags / no-field-reflection): oracle/oracle/codemp/game/g_main.c:852")
}

// PORT-ESCALATION(variadic-c-abi): variadic + no world/engine handle to route
// through `trap_Error`.
/// Raven `Com_Error`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1208-1217`
pub fn Com_Error(
    level: c_int,
    error: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port Com_Error — parked (variadic-c-abi): oracle/oracle/codemp/game/g_main.c:1208")
}

// PORT-ESCALATION(variadic-c-abi): variadic + no world/engine handle to route
// through `trap_Print`.
/// Raven `Com_Printf`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1219-1228`
pub fn Com_Printf(
    msg: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port Com_Printf — parked (variadic-c-abi): oracle/oracle/codemp/game/g_main.c:1219")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// building the tournament queue (`level.sortedClients`); the zero-param
// skeleton signature has no GameWorld handle to reach `level`/`g_clients`
// through.
/// Raven `AddTournamentPlayer`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1248-1295`
pub fn AddTournamentPlayer(ctx: GameContext<'_>) {
    todo!("Port AddTournamentPlayer — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1248")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): same as
// AddTournamentPlayer — walks `level.clients`/`SetTeam` with no world handle.
/// Raven `RemoveTournamentLoser`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1304-1319`
pub fn RemoveTournamentLoser(ctx: GameContext<'_>) {
    todo!("Port RemoveTournamentLoser — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1304")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// counting power-duel participants; out-params are fine (`*mut c_int`) but
// there is no GameWorld handle to reach `level` through.
/// Raven `G_PowerDuelCount`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1321-1343`
pub fn G_PowerDuelCount(
    ctx: GameContext<'_>,
    loners: *mut c_int,
    doubles: *mut c_int,
    countSpec: qboolean,
) {
    todo!("Port G_PowerDuelCount — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1321")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// building power-duel pairs; no world handle.
/// Raven `AddPowerDuelPlayers`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1346-1425`
pub fn AddPowerDuelPlayers(ctx: GameContext<'_>) {
    todo!("Port AddPowerDuelPlayers — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1346")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`; no
// world handle.
/// Raven `RemovePowerDuelLosers`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1429-1471`
pub fn RemovePowerDuelLosers(ctx: GameContext<'_>) {
    todo!("Port RemovePowerDuelLosers — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1429")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`; no
// world handle.
/// Raven `RemoveDuelDrawLoser`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1473-1512`
pub fn RemoveDuelDrawLoser(ctx: GameContext<'_>) {
    todo!("Port RemoveDuelDrawLoser — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1473")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`; no
// world handle.
/// Raven `RemoveTournamentWinner`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1519-1534`
pub fn RemoveTournamentWinner(ctx: GameContext<'_>) {
    todo!("Port RemoveTournamentWinner — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1519")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// adjusting tournament scores; no world handle.
/// Raven `AdjustTournamentScores`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1541-1616`
pub fn AdjustTournamentScores(ctx: GameContext<'_>) {
    todo!("Port AdjustTournamentScores — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1541")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): qsort comparator over
// `level.clients` reached through opaque `*const c_void` indices; needs
// `level` to resolve the comparison and there is no world handle in scope
// (also fn-pointer-param: this is the qsort callback itself, address-compared
// / registered as a C function pointer, which the trait-table ruling doesn't
// cover for bare comparator callbacks).
/// Raven `SortRanks`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1624-1689`
pub fn SortRanks(
    ctx: GameContext<'_>,
    a: *const c_void,
    b: *const c_void,
) -> c_int {
    todo!("Port SortRanks — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1624")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.clients`; no
// world handle.
/// Raven `G_CanResetDuelists`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1695-1715`
pub fn G_CanResetDuelists(ctx: GameContext<'_>) -> qboolean {
    todo!("Port G_CanResetDuelists — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1695")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `g_entities`/
// `level.clients`; no world handle.
/// Raven `G_ResetDuelists`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1718-1740`
pub fn G_ResetDuelists(ctx: GameContext<'_>) {
    todo!("Port G_ResetDuelists — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1718")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the central ranking pass
// over `level.clients`/`g_entities`, plus the `qsort`/`SortRanks` fn-pointer
// dependency above; no world handle.
/// Raven `CalculateRanks`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1751-1906`
pub fn CalculateRanks(ctx: GameContext<'_>) {
    todo!("Port CalculateRanks — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1751")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`; no
// world handle.
/// Raven `SendScoreboardMessageToAllClients`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1925-1933`
pub fn SendScoreboardMessageToAllClients(ctx: GameContext<'_>) {
    todo!("Port SendScoreboardMessageToAllClients — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1925")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.intermission_origin`
// / calls `FindIntermissionPoint`/`trap_LinkEntity`; the raw `*mut gentity_t`
// param covers `ent` but there is still no handle to reach `level` through.
/// Raven `MoveClientToIntermission`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1943-1967`
pub fn MoveClientToIntermission(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port MoveClientToIntermission — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1943")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `g_entities`
// looking for `info_player_intermission`/deathmatch spots and writes
// `level.intermission_origin/angle`; no world handle.
/// Raven `FindIntermissionPoint`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:1979-2026`
pub fn FindIntermissionPoint(ctx: GameContext<'_>) {
    todo!("Port FindIntermissionPoint — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:1979")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): sets
// `level.intermissiontime`, walks `g_entities`; no world handle.
/// Raven `BeginIntermission`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2035-2092`
pub fn BeginIntermission(ctx: GameContext<'_>) {
    todo!("Port BeginIntermission — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2035")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `GameCvars`
// (`g_duel_fraglimit`) and `level` duel win/loss counters; no world handle.
/// Raven `DuelLimitHit`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2094-2112`
pub fn DuelLimitHit(ctx: GameContext<'_>) -> qboolean {
    todo!("Port DuelLimitHit — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2094")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// resetting duel win/loss counters; no world handle.
/// Raven `DuelResetWinsLosses`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2114-2128`
pub fn DuelResetWinsLosses(ctx: GameContext<'_>) {
    todo!("Port DuelResetWinsLosses — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2114")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the map-exit/`level.changemap`
// logic reads and writes `level` and `GameCvars`; no world handle.
/// Raven `ExitLevel`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2141-2204`
pub fn ExitLevel(ctx: GameContext<'_>) {
    todo!("Port ExitLevel — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2141")
}

// PORT-ESCALATION(variadic-c-abi): variadic + no world handle to reach the
// `g_log`/level.time-stamped log file through.
/// Raven `G_LogPrintf`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2213-2240`
pub fn G_LogPrintf(
    ctx: GameContext<'_>,
    fmt: *const c_char,
    // variadic `...` — C varargs, seam decision pending
) {
    todo!("Port G_LogPrintf — parked (variadic-c-abi): oracle/oracle/codemp/game/g_main.c:2213")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level`/`g_clients`
// building an exit-reason log line; no world handle.
/// Raven `LogExit`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2249-2303`
pub fn LogExit(
    ctx: GameContext<'_>,
    string: *const c_char,
) {
    todo!("Port LogExit — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2249")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the intermission-exit
// vote/ready-check pass over `level.clients`; no world handle.
/// Raven `CheckIntermissionExit`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2317-2554`
pub fn CheckIntermissionExit(ctx: GameContext<'_>) {
    todo!("Port CheckIntermissionExit — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2317")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.teamScores`;
// no world handle.
/// Raven `ScoreIsTied`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2561-2576`
pub fn ScoreIsTied(ctx: GameContext<'_>) -> qboolean {
    todo!("Port ScoreIsTied — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2561")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the fraglimit/timelimit/
// capturelimit end-of-match decision reads `level`/`GameCvars` extensively; no
// world handle.
/// Raven `CheckExitRules`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2588-2911`
pub fn CheckExitRules(ctx: GameContext<'_>) {
    todo!("Port CheckExitRules — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2588")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`; no
// world handle.
/// Raven `G_RemoveDuelist`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2923-2938`
pub fn G_RemoveDuelist(
    ctx: GameContext<'_>,
    team: c_int,
) {
    todo!("Port G_RemoveDuelist — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2923")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the tournament-restart
// state machine over `level`/`GameCvars`; no world handle.
/// Raven `CheckTournament`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:2948-3216`
pub fn CheckTournament(ctx: GameContext<'_>) {
    todo!("Port CheckTournament — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:2948")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `g_entities`/
// `level.clients` dropping bot clients; no world handle.
/// Raven `G_KickAllBots`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3218-3239`
pub fn G_KickAllBots(ctx: GameContext<'_>) {
    todo!("Port G_KickAllBots — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3218")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the map/kick/ban vote
// timeout/tally reads `level`; no world handle.
/// Raven `CheckVote`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3246-3326`
pub fn CheckVote(ctx: GameContext<'_>) {
    todo!("Port CheckVote — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3246")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`
// filtering by `sess.sessionTeam`; no world handle.
/// Raven `PrintTeam`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3333-3341`
pub fn PrintTeam(
    ctx: GameContext<'_>,
    team: c_int,
    message: *mut c_char,
) {
    todo!("Port PrintTeam — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3333")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads/writes
// `level.clients[..].sess.teamLeader`, calls `PrintTeam`/`ClientUserinfoChanged`
// (also unported in this crate); no world handle.
/// Raven `SetLeader`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3348-3370`
pub fn SetLeader(
    ctx: GameContext<'_>,
    team: c_int,
    client: c_int,
) {
    todo!("Port SetLeader — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3348")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): walks `level.clients`/
// `g_entities` looking for a team leader; no world handle.
/// Raven `CheckTeamLeader`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3377-3402`
pub fn CheckTeamLeader(
    ctx: GameContext<'_>,
    team: c_int,
) {
    todo!("Port CheckTeamLeader — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3377")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads/writes
// `level.teamVoteTime`/`teamVoteYes`/`teamVoteNo`/`teamVoteString`; no world
// handle.
/// Raven `CheckTeamVote`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3409-3447`
pub fn CheckTeamVote(
    ctx: GameContext<'_>,
    team: c_int,
) {
    todo!("Port CheckTeamVote — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3409")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `GameCvars`
// (`g_password`) and a function-scope static (`lastMod`, fork ruling 5 — a
// genuine cross-frame static, which itself wants a GameWorld field); no world
// handle.
/// Raven `CheckCvars`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3455-3480`
pub fn CheckCvars(ctx: GameContext<'_>) {
    todo!("Port CheckCvars — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3455")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// dispatches through the `EntThink` fn-ID enum (fork ruling 2); the raw `ent`
// param is fine but there is no world handle to compare `level.time` through,
// and the think dispatch needs the central match table's threaded shape.
/// Raven `G_RunThink`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3489-3512`
pub fn G_RunThink(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port G_RunThink — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3489")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads/writes the
// file-static `navCalcPathTime` (fork ruling 5, a genuine cross-frame static
// wanting a GameWorld field) and `level.time`; no world handle.
/// Raven `NAV_CheckCalcPaths`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3522-3555`
pub fn NAV_CheckCalcPaths(ctx: GameContext<'_>) {
    todo!("Port NAV_CheckCalcPaths — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3522")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): returns `level.time`; the
// zero-param skeleton signature has no world handle to reach `level` through.
/// Raven `BG_GetTime`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3559-3562`
pub fn BG_GetTime() -> c_int {
    todo!("Port BG_GetTime — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3559")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the whole-frame driver —
// walks `g_entities`, dispatches `ent->think`/`ent->s.eType`-keyed subsystem
// calls, updates `level`/`GameCvars`/several g_main.c file-scope globals
// (`gDoSlowMoDuel`, `g_LastFrameTime`, `g_siegeRespawnCheck`, …); no world
// handle.
/// Raven `G_RunFrame`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:3582-4102`
pub fn G_RunFrame(
    ctx: GameContext<'_>,
    levelTime: c_int,
) {
    todo!("Port G_RunFrame — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:3582")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the C body's
// `static char text[1024]` rotating scratch return buffer (fork ruling 5:
// va/vtos idiom → owned return value) plus its `Com_sprintf` call is itself
// unported (`q_shared.rs::Com_sprintf`, parked `variadic-c-abi`) — this
// function cannot be finished until that seam lands.
/// Raven `G_GetStringEdString`.
///
/// Source: `oracle/oracle/codemp/game/g_main.c:4104-4120`
pub fn G_GetStringEdString(
    ctx: GameContext<'_>,
    refSection: *mut c_char,
    refName: *mut c_char,
) -> *const c_char {
    todo!("Port G_GetStringEdString — parked (raw-ptr-skeleton-no-world-handle): oracle/oracle/codemp/game/g_main.c:4104")
}
