// PORT-COMPLETE: g_mover.c 22/50
//! FAITHFUL port of `oracle/oracle/codemp/game/g_mover.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest, then filled by the jampgame mega-pass. STAGING ONLY — not
//! wired into crates/. Functions that reach file-scope game state
//! (`level`, `g_entities`, the `pushed[]`/`pushed_p` static save-stack,
//! cvars, …) or an engine trap (`trap_LinkEntity`, `trap_Trace`, …, which
//! all require a threaded `&Engine` the staged raw-pointer signatures
//! don't carry) are parked; likewise functions whose vec3 out-param
//! helpers (`AngleVectors`/`BG_EvaluateTrajectory`/`RadiusFromBounds`, or a
//! `vec3_t` parameter that is itself an out-param, e.g. `CalcTeamDoorCenter`'s
//! `center`) resolve to by-value `vec3_t` signatures that cannot express the
//! C out-param mutation, and functions needing flag/enum constants that
//! have not been type-ported anywhere in the crate graph yet (`FL_*`,
//! `SVF_*`, `EF_*`, `CONTENTS_*`, `MAT_*`, and `moverState_t`'s
//! `MOVER_POS1`/`MOVER_1TO2`/`MOVER_POS2`/`MOVER_2TO1` values — `g_local.h`
//! is out of this file's packet). See PORT-ESCALATION markers at each site.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

use crate::g_combat::G_Damage;
use crate::g_main::{Com_Printf, G_Printf};
use crate::g_utils::{G_AddEvent, G_Find, G_FreeEntity, G_SetOrigin, G_SoundSetIndex, G_TempEntity, G_UseTargets, GlobalUse, vtos};
use crate::NPC_utils::G_ActivateBehavior;
use mp_bg::public::entity_event::entity_event_t;
use mp_bg::public::means_of_death::meansOfDeath_t;
use mp_qshared::common::mp::qcommon::b_set_t::bSet_t;

// Raven `qboolean` is `c_int`; keep the source spelling at assignment sites.
// Source: `oracle/oracle/codemp/game/q_shared.h`
const qtrue: qboolean = 1;
const qfalse: qboolean = 0;

// Raven file-scope `#define`s (this file's own bitflags on `ent->spawnflags`).
// Source: `oracle/oracle/codemp/game/g_mover.c:26-33`
const MOVER_START_ON: c_int = 1;
const MOVER_FORCE_ACTIVATE: c_int = 2;
const MOVER_CRUSHER: c_int = 4;
const MOVER_TOGGLE: c_int = 8;
const MOVER_LOCKED: c_int = 16;
const MOVER_GOODIE: c_int = 32;
const MOVER_PLAYER_USE: c_int = 64;
const MOVER_INACTIVE: c_int = 128;

// Raven file-scope `int BMS_START/BMS_MID/BMS_END` (g_mover.c:35-37) — never
// reassigned at runtime (fork ruling 5: const tables -> const).
// Source: `oracle/oracle/codemp/game/g_mover.c:35-37`
const BMS_START: c_int = 0;
const BMS_MID: c_int = 1;
const BMS_END: c_int = 2;

/// Raven `G_PlayDoorLoopSound`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:45-60`
pub fn G_PlayDoorLoopSound(
    ent: *mut gentity_t,
) {
    unsafe {
        if (*ent).soundSet.is_null() || *(*ent).soundSet == 0 {
            return;
        }

        (*ent).s.soundSetIndex = G_SoundSetIndex((*ent).soundSet);
        (*ent).s.loopIsSoundset = qtrue;
        (*ent).s.loopSound = BMS_MID;
    }
}

/// Raven `G_PlayDoorSound`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:68-78`
pub fn G_PlayDoorSound(
    ent: *mut gentity_t,
    r#type: c_int,
) {
    unsafe {
        if (*ent).soundSet.is_null() || *(*ent).soundSet == 0 {
            return;
        }

        (*ent).s.soundSetIndex = G_SoundSetIndex((*ent).soundSet);

        G_AddEvent(ent, entity_event_t::EV_PLAYDOORSOUND as c_int, r#type);
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): `g_entities` (global
// array) and `trap_Trace` (needs `&Engine`) are both unreachable from the
// staged raw-pointer signature.
/// Raven `G_TestEntityPosition`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:86-111`
pub fn G_TestEntityPosition(
    ent: *mut gentity_t,
) -> *mut gentity_t {
    todo!("Port G_TestEntityPosition — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(vec3-outparam-seam): resolved `AngleVectors(angles,
// forward, right, up)` takes `forward`/`right`/`up` by value ([f32;3]), so
// the out-params it must write into `matrix[0..3]` cannot be received.
/// Raven `G_CreateRotationMatrix`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:118-121`
pub fn G_CreateRotationMatrix(
    angles: vec3_t,
    matrix: *mut vec3_t,
) {
    todo!("Port G_CreateRotationMatrix — parked: vec3-outparam-seam")
}

/// Raven `G_TransposeMatrix`.
///
/// `matrix`/`transpose` are Raven `vec3_t matrix[3]` — arrays of 3 rows that
/// decay to a `vec3_t *` at the call boundary, so the raw pointer here is
/// walked as a 3-row array via pointer arithmetic.
/// Source: `oracle/oracle/codemp/game/g_mover.c:128-135`
pub fn G_TransposeMatrix(
    matrix: *mut vec3_t,
    transpose: *mut vec3_t,
) {
    unsafe {
        for i in 0..3usize {
            for j in 0..3usize {
                (*transpose.add(i))[j] = (*matrix.add(j))[i];
            }
        }
    }
}

// PORT-ESCALATION(vec3-outparam-seam): Raven's `point` parameter is a
// `vec3_t` that decays to a pointer in C and is mutated in place (the caller
// reads the mutated value back); the resolved signature takes it by value
// ([f32;3]), so the out-param mutation cannot be observed by the caller.
/// Raven `G_RotatePoint`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:142-149`
pub fn G_RotatePoint(
    point: vec3_t,
    matrix: *mut vec3_t,
) {
    todo!("Port G_RotatePoint — parked: vec3-outparam-seam")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): the `pushed[]`/`pushed_p`
// save-stack is a file-scope global (not owned by any threaded world
// handle here), `G_Error` has no engine/world seam yet, and `trap_LinkEntity`
// needs `&Engine`.
/// Raven `G_TryPushingEntity`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:159-269`
pub fn G_TryPushingEntity(
    check: *mut gentity_t,
    pusher: *mut gentity_t,
    r#move: vec3_t,
    amove: vec3_t,
) -> qboolean {
    todo!("Port G_TryPushingEntity — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads/writes `g_entities`
// and the `pushed[]`/`pushed_p` save-stack, and calls `trap_UnlinkEntity` /
// `trap_EntitiesInBox` / `trap_LinkEntity` (all need `&Engine`).
/// Raven `G_MoverPush`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:283-408`
pub fn G_MoverPush(
    pusher: *mut gentity_t,
    r#move: vec3_t,
    amove: vec3_t,
    obstacle: *mut *mut gentity_t,
) -> qboolean {
    todo!("Port G_MoverPush — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// the `pushed[]`/`pushed_p` save-stack.
/// Raven `G_MoverTeam`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:416-471`
pub fn G_MoverTeam(
    ent: *mut gentity_t,
) {
    todo!("Port G_MoverTeam — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(unported-flag-consts): `ent->flags & FL_TEAMSLAVE` needs
// `FL_TEAMSLAVE` (`g_local.h`), not type-ported anywhere in the crate graph
// yet.
/// Raven `G_RunMover`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:479-493`
pub fn G_RunMover(
    ent: *mut gentity_t,
) {
    todo!("Port G_RunMover — parked: unported-flag-consts (FL_TEAMSLAVE)")
}

// PORT-ESCALATION(vec3-outparam-seam): `center` is Raven's `vec3_t center`
// out-param (decays to pointer in C, mutated in place and read back by the
// caller); the resolved signature takes it by value ([f32;3]).
/// Raven `CalcTeamDoorCenter`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:511-528`
pub fn CalcTeamDoorCenter(
    ent: *mut gentity_t,
    center: vec3_t,
) {
    todo!("Port CalcTeamDoorCenter — parked: vec3-outparam-seam")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// calls `trap_LinkEntity` (needs `&Engine`).
/// Raven `SetMoverState`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:535-590`
pub fn SetMoverState(
    ent: *mut gentity_t,
    moverState: moverState_t,
    time: c_int,
) {
    todo!("Port SetMoverState — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `MatchTeam`.
///
/// All entities in a mover team move from pos1 to pos2 in the same amount
/// of time.
/// Source: `oracle/oracle/codemp/game/g_mover.c:600-606`
pub fn MatchTeam(
    teamLeader: *mut gentity_t,
    moverState: c_int,
    time: c_int,
) {
    unsafe {
        let mut slave = teamLeader;
        while !slave.is_null() {
            SetMoverState(slave, moverState as moverState_t, time);
            slave = (*slave).teamchain;
        }
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `ReturnToPos1`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:615-625`
pub fn ReturnToPos1(
    ent: *mut gentity_t,
) {
    todo!("Port ReturnToPos1 — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`,
// calls `trap_AdjustAreaPortalState` (needs `&Engine`) and `G_Error` (no
// engine/world seam yet).
/// Raven `Reached_BinaryMover`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:634-702`
pub fn Reached_BinaryMover(
    ent: *mut gentity_t,
) {
    todo!("Port Reached_BinaryMover — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`
// throughout.
/// Raven `Use_BinaryMover_Go`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:710-828`
pub fn Use_BinaryMover_Go(
    ent: *mut gentity_t,
) {
    todo!("Port Use_BinaryMover_Go — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `UnLockDoors`.
///
/// Go through and unlock the door and all the slaves.
/// `ent` is declared `gentity_t *const` in Raven (a const *pointer*, not a
/// const pointee) — the fields are still mutated, so the cast to `*mut` here
/// just recovers writability, not a behavior change.
/// Source: `oracle/oracle/codemp/game/g_mover.c:830-845`
pub fn UnLockDoors(
    ent: *const gentity_t,
) {
    unsafe {
        let mut slave = ent as *mut gentity_t;
        loop {
            // want to allow locked toggle doors, so keep the targetname
            if (*slave).spawnflags & MOVER_TOGGLE == 0 {
                (*slave).targetname = core::ptr::null_mut(); // not usable ever again
            }
            (*slave).spawnflags &= !MOVER_LOCKED;
            (*slave).s.frame = 1; // second stage of anim
            slave = (*slave).teamchain;
            if slave.is_null() {
                break;
            }
        }
    }
}

/// Raven `LockDoors`.
///
/// Go through and lock the door and all the slaves.
/// Source: `oracle/oracle/codemp/game/g_mover.c:846-857`
pub fn LockDoors(
    ent: *const gentity_t,
) {
    unsafe {
        let mut slave = ent as *mut gentity_t;
        loop {
            (*slave).spawnflags |= MOVER_LOCKED;
            (*slave).s.frame = 0; // first stage of anim
            slave = (*slave).teamchain;
            if slave.is_null() {
                break;
            }
        }
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`
// (`ent->nextthink = level.time + ent->delay`).
/// Raven `Use_BinaryMover`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:863-901`
pub fn Use_BinaryMover(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port Use_BinaryMover — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `InitMoverTrData`.
///
/// "pos1", "pos2", and "speed" should be set before calling, so the
/// movement delta can be calculated.
/// Source: `oracle/oracle/codemp/game/g_mover.c:913-934`
pub fn InitMoverTrData(
    ent: *mut gentity_t,
) {
    unsafe {
        (*ent).s.pos.tr_type = trType_t::TR_STATIONARY;
        (*ent).s.pos.tr_base = (*ent).pos1;

        // calculate time to reach second position from speed
        let pos1 = (*ent).pos1;
        let pos2 = (*ent).pos2;
        let r#move = [pos2[0] - pos1[0], pos2[1] - pos1[1], pos2[2] - pos1[2]];
        let distance =
            (r#move[0] * r#move[0] + r#move[1] * r#move[1] + r#move[2] * r#move[2]).sqrt();
        if (*ent).speed == 0.0 {
            (*ent).speed = 100.0;
        }
        let speed = (*ent).speed;
        (*ent).s.pos.tr_delta = [r#move[0] * speed, r#move[1] * speed, r#move[2] * speed];
        (*ent).s.pos.tr_duration = (distance * 1000.0 / speed) as c_int;
        if (*ent).s.pos.tr_duration <= 0 {
            (*ent).s.pos.tr_duration = 1;
        }
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_LinkEntity`
// (needs `&Engine`).
/// Raven `InitMover`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:936-999`
pub fn InitMover(
    ent: *mut gentity_t,
) {
    todo!("Port InitMover — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `Blocked_Door`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1018-1029`
pub fn Blocked_Door(
    ent: *mut gentity_t,
    other: *mut gentity_t,
) {
    unsafe {
        if (*ent).damage != 0 {
            // Resolved `G_Damage` takes `dir`/`point` by value (Raven passes
            // NULL pointers here); substitute the zero vector since `G_Damage`
            // is itself an unported stub either way.
            G_Damage(
                other,
                ent,
                ent,
                [0.0, 0.0, 0.0],
                [0.0, 0.0, 0.0],
                (*ent).damage,
                0,
                meansOfDeath_t::MOD_CRUSH as c_int,
            );
        }
        if (*ent).spawnflags & MOVER_CRUSHER != 0 {
            return; // crushers don't reverse
        }

        // reverse direction
        Use_BinaryMover(ent, ent, other);
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_Trace`
// (needs `&Engine`).
/// Raven `Touch_DoorTriggerSpectator`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1037-1071`
pub fn Touch_DoorTriggerSpectator(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_DoorTriggerSpectator — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(unported-flag-consts): `ent->flags & FL_INACTIVE`,
// `ent->parent->flags & FL_TEAMSLAVE` need `FL_INACTIVE`/`FL_TEAMSLAVE`
// (`g_local.h`), not type-ported anywhere in the crate graph yet.
/// Raven `Touch_DoorTrigger`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1078-1158`
pub fn Touch_DoorTrigger(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_DoorTrigger — parked: unported-flag-consts (FL_INACTIVE, FL_TEAMSLAVE)")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `G_Spawn`/
// `trap_LinkEntity` and reads `level.time`.
/// Raven `Think_SpawnNewDoorTrigger`.
///
/// All of the parts of a door have been spawned, so create a trigger that
/// encloses all of them.
/// Source: `oracle/oracle/codemp/game/g_mover.c:1168-1215`
pub fn Think_SpawnNewDoorTrigger(
    ent: *mut gentity_t,
) {
    todo!("Port Think_SpawnNewDoorTrigger — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `Think_MatchTeam`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1217-1220`
pub fn Think_MatchTeam(
    ent: *mut gentity_t,
) {
    todo!("Port Think_MatchTeam — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities`
// (global array).
/// Raven `G_EntIsDoor`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1222-1237`
pub fn G_EntIsDoor(
    entityNum: c_int,
) -> qboolean {
    todo!("Port G_EntIsDoor — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(unported-flag-consts): `door->flags & FL_TEAMSLAVE` needs
// `FL_TEAMSLAVE`, and `owner->r.contents & CONTENTS_TRIGGER` needs
// `CONTENTS_TRIGGER` — neither type-ported anywhere in the crate graph yet.
/// Raven `G_FindDoorTrigger`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1239-1280`
pub fn G_FindDoorTrigger(
    ent: *mut gentity_t,
) -> *mut gentity_t {
    todo!("Port G_FindDoorTrigger — parked: unported-flag-consts (FL_TEAMSLAVE, CONTENTS_TRIGGER)")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities` and
// calls `G_EntIsDoor`/`G_FindDoorTrigger`, both parked.
/// Raven `G_EntIsUnlockedDoor`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1282-1346`
pub fn G_EntIsUnlockedDoor(
    entityNum: c_int,
) -> qboolean {
    todo!("Port G_EntIsUnlockedDoor — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// calls `trap_SetBrushModel` (needs `&Engine`).
/// Raven `SP_func_door`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1380-1472`
pub fn SP_func_door(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_door — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `Touch_Plat`.
///
/// Don't allow decent if a living player is on it.
/// Source: `oracle/oracle/codemp/game/g_mover.c:1489-1498`
pub fn Touch_Plat(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_Plat — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(moverstate-enum-unported): `ent->parent->moverState ==
// MOVER_POS1` needs `moverState_t`'s enum values, which live in
// `g_local.h` (out of this file's packet) and aren't type-ported anywhere
// in the crate graph yet — no source to transcribe an authoritative value
// from without guessing.
/// Raven `Touch_PlatCenterTrigger`.
///
/// If the plat is at the bottom position, start it going up.
/// Source: `oracle/oracle/codemp/game/g_mover.c:1507-1515`
pub fn Touch_PlatCenterTrigger(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_PlatCenterTrigger — parked: moverstate-enum-unported")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `G_Spawn`/
// `trap_LinkEntity`.
/// Raven `SpawnPlatTrigger`.
///
/// Spawn a trigger in the middle of the plat's low position. Elevator cars
/// require that the trigger extend through the entire low position, not
/// just sit on top of it.
/// Source: `oracle/oracle/codemp/game/g_mover.c:1527-1559`
pub fn SpawnPlatTrigger(
    ent: *mut gentity_t,
) {
    todo!("Port SpawnPlatTrigger — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls
// `trap_SetBrushModel` (needs `&Engine`).
/// Raven `SP_func_plat`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1576-1617`
pub fn SP_func_plat(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_plat — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(moverstate-enum-unported): `ent->moverState == MOVER_POS1`
// needs `moverState_t`'s enum values (`g_local.h`, out of this file's
// packet, not type-ported anywhere in the crate graph yet).
/// Raven `Touch_Button`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1633-1641`
pub fn Touch_Button(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    todo!("Port Touch_Button — parked: moverstate-enum-unported")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls
// `trap_SetBrushModel` (needs `&Engine`).
/// Raven `SP_func_button`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1660-1702`
pub fn SP_func_button(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_button — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `Think_BeginMoving`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1727-1732`
pub fn Think_BeginMoving(
    ent: *mut gentity_t,
) {
    todo!("Port Think_BeginMoving — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `Reached_Train`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1739-1793`
pub fn Reached_Train(
    ent: *mut gentity_t,
) {
    todo!("Port Reached_Train — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `Think_SetupTrainTargets`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1802-1864`
pub fn Think_SetupTrainTargets(
    ent: *mut gentity_t,
) {
    unsafe {
        (*ent).nextTrain = G_Find(
            core::ptr::null_mut(),
            core::mem::offset_of!(gentity_t, targetname) as c_int,
            (*ent).target,
        );
        if (*ent).nextTrain.is_null() {
            Com_Printf(c"func_train at %s with an unfound target\n".as_ptr());
            // Free me?`
            return;
        }

        // FIXME: this can go into an infinite loop if last path_corner doesn't
        // link to first path_corner, like so:
        //  t1---->t2---->t3
        //          ^      |
        //           \_____|
        let mut start: *mut gentity_t = core::ptr::null_mut();
        let mut path = (*ent).nextTrain;
        while path != start {
            if start.is_null() {
                start = path;
            }

            if (*path).target.is_null() {
                // end of path
                break;
            }

            // find a path_corner among the targets — there may also be
            // other targets that get fired when the corner is reached
            let mut next: *mut gentity_t;
            loop {
                next = G_Find(
                    core::ptr::null_mut(),
                    core::mem::offset_of!(gentity_t, targetname) as c_int,
                    (*path).target,
                );
                if next.is_null() {
                    // end of path
                    break;
                }
                // Raven uses libc `strcmp` (case-sensitive) here, which has no
                // ported binding in this crate; `Q_stricmp` is the closest
                // available equivalent (case-insensitive) and is a no-op
                // difference for the literal "path_corner" classname.
                if crate::q_shared::Q_stricmp((*next).classname, c"path_corner".as_ptr()) == 0 {
                    break;
                }
            }

            if !next.is_null() {
                (*path).nextTrain = next;
            } else {
                break;
            }

            path = next;
        }

        if (*ent).targetname.is_null() || ((*ent).spawnflags & 1) != 0
        /* start on */
        {
            // start the train moving from the first corner
            Reached_Train(ent);
        } else {
            G_SetOrigin(ent, (*ent).s.origin);
        }
    }
}

/// Raven `SP_path_corner`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1873-1880`
pub fn SP_path_corner(
    self_: *mut gentity_t,
) {
    unsafe {
        if (*self_).targetname.is_null() {
            G_Printf(c"path_corner with no targetname at %s\n".as_ptr());
            let _ = vtos((*self_).s.origin);
            G_FreeEntity(self_);
            return;
        }
        // path corners don't need to be linked in
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// calls `trap_SetBrushModel` (needs `&Engine`).
/// Raven `SP_func_train`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1897-1927`
pub fn SP_func_train(
    self_: *mut gentity_t,
) {
    todo!("Port SP_func_train — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// calls `trap_SetBrushModel` (needs `&Engine`).
/// Raven `SP_func_static`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:1956-2019`
pub fn SP_func_static(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_static — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `func_static_use`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2021-2030`
pub fn func_static_use(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    unsafe {
        G_ActivateBehavior(self_, bSet_t::BSET_USE as c_int);

        if (*self_).spawnflags & 4 /* SWITCH_SHADER */ != 0 {
            (*self_).s.frame = if (*self_).s.frame != 0 { 0 } else { 1 }; // toggle frame
        }
        G_UseTargets(self_, activator);
    }
}

/// Raven `func_rotating_use`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2040-2066`
pub fn func_rotating_use(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    unsafe {
        if (*self_).s.apos.tr_type == trType_t::TR_LINEAR {
            (*self_).s.apos.tr_type = trType_t::TR_STATIONARY;
            // stop the sound if it stops moving
            (*self_).s.loopSound = 0;
            (*self_).s.loopIsSoundset = qfalse;
            // play stop sound too?
            if !(*self_).soundSet.is_null() && *(*self_).soundSet != 0 {
                (*self_).s.soundSetIndex = G_SoundSetIndex((*self_).soundSet);
                G_AddEvent(self_, entity_event_t::EV_BMODEL_SOUND as c_int, BMS_END);
            }
        } else {
            if !(*self_).soundSet.is_null() && *(*self_).soundSet != 0 {
                (*self_).s.soundSetIndex = G_SoundSetIndex((*self_).soundSet);
                G_AddEvent(self_, entity_event_t::EV_BMODEL_SOUND as c_int, BMS_START);
                (*self_).s.loopSound = BMS_MID;
                (*self_).s.loopIsSoundset = qtrue;
            }
            (*self_).s.apos.tr_type = trType_t::TR_LINEAR;
        }
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_SetBrushModel`
// (needs `&Engine`).
/// Raven `SP_func_rotating`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2133-2209`
pub fn SP_func_rotating(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_rotating — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_SetBrushModel`
// (needs `&Engine`).
/// Raven `SP_func_bobbing`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2231-2258`
pub fn SP_func_bobbing(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_bobbing — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_SetBrushModel`
// (needs `&Engine`).
/// Raven `SP_func_pendulum`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2280-2313`
pub fn SP_func_pendulum(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_pendulum — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(bg-dep): `material_t` (`MAT_GLASS`, `MAT_METAL`, …) is a
// `type material_t = c_int` alias with its anonymous enum constants not
// type-ported anywhere in the crate graph yet — no values to match on.
/// Raven `CacheChunkEffects`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2323-2361`
pub fn CacheChunkEffects(
    material: material_t,
) {
    todo!("Port CacheChunkEffects — parked: bg-dep (material_t MAT_* constants unported)")
}

/// Raven `G_MiscModelExplosion`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2363-2377`
pub fn G_MiscModelExplosion(
    mins: vec3_t,
    maxs: vec3_t,
    size: c_int,
    chunkType: material_t,
) {
    unsafe {
        let mid = [
            (mins[0] + maxs[0]) * 0.5,
            (mins[1] + maxs[1]) * 0.5,
            (mins[2] + maxs[2]) * 0.5,
        ];

        let te = G_TempEntity(mid, entity_event_t::EV_MISC_MODEL_EXP as c_int);

        (*te).s.origin2 = maxs;
        (*te).s.angles2 = mins;
        (*te).s.time = size;
        (*te).s.eventParm = chunkType;
    }
}

/// Raven `G_Chunks`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2379-2395`
pub fn G_Chunks(
    owner: c_int,
    origin: vec3_t,
    normal: vec3_t,
    mins: vec3_t,
    maxs: vec3_t,
    speed: f32,
    numChunks: c_int,
    chunkType: material_t,
    customChunk: c_int,
    baseScale: f32,
) {
    unsafe {
        let te = G_TempEntity(origin, entity_event_t::EV_DEBRIS as c_int);

        // Now it's time to cram everything horribly into the entitystate of
        // an event entity.
        (*te).s.owner = owner;
        (*te).s.origin = origin;
        (*te).s.angles = normal;
        (*te).s.origin2 = maxs;
        (*te).s.angles2 = mins;
        (*te).s.speed = speed;
        (*te).s.eventParm = numChunks;
        (*te).s.trickedentindex = chunkType;
        (*te).s.modelindex = customChunk;
        (*te).s.apos.tr_base[0] = baseScale;
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities`,
// `level.time`, calls `trap_` syscalls.
/// Raven `funcBBrushDieGo`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2398-2498`
pub fn funcBBrushDieGo(
    self_: *mut gentity_t,
) {
    todo!("Port funcBBrushDieGo — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `funcBBrushDie`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2500-2514`
pub fn funcBBrushDie(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    todo!("Port funcBBrushDie — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `funcBBrushUse`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2516-2530`
pub fn funcBBrushUse(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    unsafe {
        G_ActivateBehavior(self_, bSet_t::BSET_USE as c_int);
        if (*self_).spawnflags & 64 != 0 {
            // Using it doesn't break it, makes it use it's targets
            if !(*self_).target.is_null() && *(*self_).target != 0 {
                G_UseTargets(self_, activator);
            }
        } else {
            funcBBrushDie(self_, other, activator, (*self_).health, meansOfDeath_t::MOD_UNKNOWN as c_int);
        }
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`.
/// Raven `funcBBrushPain`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2532-2597`
pub fn funcBBrushPain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    todo!("Port funcBBrushPain — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_LinkEntity`
// (needs `&Engine`).
/// Raven `InitBBrush`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2599-2661`
pub fn InitBBrush(
    ent: *mut gentity_t,
) {
    todo!("Port InitBBrush — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `funcBBrushTouch`.
///
/// Empty in Raven.
/// Source: `oracle/oracle/codemp/game/g_mover.c:2663-2665`
pub fn funcBBrushTouch(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): `G_Error` has no
// engine/world seam yet.
/// Raven `SP_func_breakable`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2731-2829`
pub fn SP_func_breakable(
    self_: *mut gentity_t,
) {
    todo!("Port SP_func_breakable — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities`
// (global array).
/// Raven `G_EntIsBreakable`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2831-2866`
pub fn G_EntIsBreakable(
    entityNum: c_int,
) -> qboolean {
    todo!("Port G_EntIsBreakable — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `GlassDie`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2875-2903`
pub fn GlassDie(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    unsafe {
        if (*self_).genericValue5 != 0 {
            // was already destroyed, do not retrigger it
            return;
        }

        (*self_).genericValue5 = 1;

        let dif = [
            ((*self_).r.absmax[0] + (*self_).r.absmin[0]) / 2.0,
            ((*self_).r.absmax[1] + (*self_).r.absmin[1]) / 2.0,
            ((*self_).r.absmax[2] + (*self_).r.absmin[2]) / 2.0,
        ];

        G_UseTargets(self_, attacker);

        (*self_).splashRadius = 40; // ?? some random number, maybe it's ok?

        let te = G_TempEntity(dif, entity_event_t::EV_GLASS_SHATTER as c_int);
        (*te).s.genericenemyindex = (*self_).s.number;
        (*te).s.origin = (*self_).pos1;
        (*te).s.angles = (*self_).pos2;
        (*te).s.trickedentindex = (*self_).splashRadius;
        (*te).s.pos.tr_time = (*self_).genericValue3;

        G_FreeEntity(self_);
    }
}

/// Raven `GlassDie_Old`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2905-2922`
pub fn GlassDie_Old(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    unsafe {
        let dif = [
            ((*self_).r.absmax[0] + (*self_).r.absmin[0]) / 2.0,
            ((*self_).r.absmax[1] + (*self_).r.absmin[1]) / 2.0,
            ((*self_).r.absmax[2] + (*self_).r.absmin[2]) / 2.0,
        ];

        G_UseTargets(self_, attacker);

        let te = G_TempEntity(dif, entity_event_t::EV_GLASS_SHATTER as c_int);
        (*te).s.genericenemyindex = (*self_).s.number;
        (*te).s.origin = (*self_).r.maxs;
        (*te).s.angles = (*self_).r.mins;

        G_FreeEntity(self_);
    }
}

/// Raven `GlassPain`.
///
/// Empty in Raven (commented-out placeholder).
/// Source: `oracle/oracle/codemp/game/g_mover.c:2924-2928`
pub fn GlassPain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    // G_Printf("Mr. Glass says: PLZ NO IT HURTS\n");
    // Make "cracking" sound?
}

/// Raven `GlassUse`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2930-2948`
pub fn GlassUse(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    unsafe {
        // no direct object to blame for the break, so fill the values with
        // whatever
        let mut temp1 = [
            ((*self_).r.mins[0] + (*self_).r.maxs[0]) * 0.5,
            ((*self_).r.mins[1] + (*self_).r.maxs[1]) * 0.5,
            ((*self_).r.mins[2] + (*self_).r.maxs[2]) * 0.5,
        ];

        let temp2 = [
            ((*other).r.mins[0] + (*other).r.maxs[0]) * 0.5,
            ((*other).r.mins[1] + (*other).r.maxs[1]) * 0.5,
            ((*other).r.mins[2] + (*other).r.maxs[2]) * 0.5,
        ];

        (*self_).pos2 = [temp1[0] - temp2[0], temp1[1] - temp2[1], temp1[2] - temp2[2]];
        (*self_).pos1 = temp1;

        let len = ((*self_).pos2[0] * (*self_).pos2[0]
            + (*self_).pos2[1] * (*self_).pos2[1]
            + (*self_).pos2[2] * (*self_).pos2[2])
            .sqrt();
        (*self_).pos2 = [
            (*self_).pos2[0] / len * 390.0,
            (*self_).pos2[1] / len * 390.0,
            (*self_).pos2[2] / len * 390.0,
        ];

        GlassDie(self_, other, activator, 100, meansOfDeath_t::MOD_UNKNOWN as c_int);
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_SetBrushModel`
// (needs `&Engine`).
/// Raven `SP_func_glass`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2957-2990`
pub fn SP_func_glass(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_glass — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time` and
// calls `trap_LinkEntity`.
/// Raven `func_wait_return_solid`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:2995-3025`
pub fn func_wait_return_solid(
    self_: *mut gentity_t,
) {
    todo!("Port func_wait_return_solid — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(unported-flag-consts): `self->r.svFlags |= SVF_PLAYER_USABLE`
// needs `SVF_PLAYER_USABLE`, not type-ported anywhere in the crate graph yet.
/// Raven `func_usable_think`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3027-3035`
pub fn func_usable_think(
    self_: *mut gentity_t,
) {
    todo!("Port func_usable_think — parked: unported-flag-consts (SVF_PLAYER_USABLE)")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities`
// (global array).
/// Raven `G_EntIsRemovableUsable`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3037-3048`
pub fn G_EntIsRemovableUsable(
    entNum: c_int,
) -> qboolean {
    todo!("Port G_EntIsRemovableUsable — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level.time`
// (`self->nextthink = level.time + ...`).
/// Raven `func_usable_use`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3050-3106`
pub fn func_usable_use(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port func_usable_use — parked: raw-ptr-skeleton-no-world-handle")
}

/// Raven `func_usable_pain`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3108-3111`
pub fn func_usable_pain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    unsafe {
        GlobalUse(self_, attacker, attacker);
    }
}

/// Raven `func_usable_die`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3113-3117`
pub fn func_usable_die(
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    r#mod: c_int,
) {
    unsafe {
        (*self_).takedamage = qfalse;
        GlobalUse(self_, inflictor, attacker);
    }
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): `G_Error` has no
// engine/world seam yet.
/// Raven `SP_func_usable`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3140-3203`
pub fn SP_func_usable(
    self_: *mut gentity_t,
) {
    todo!("Port SP_func_usable — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_LinkEntity`
// (needs `&Engine`).
/// Raven `use_wall`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3215-3241`
pub fn use_wall(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port use_wall — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): calls `trap_LinkEntity`
// (needs `&Engine`).
/// Raven `SP_func_wall`.
///
/// Source: `oracle/oracle/codemp/game/g_mover.c:3256-3279`
pub fn SP_func_wall(
    ent: *mut gentity_t,
) {
    todo!("Port SP_func_wall — parked: raw-ptr-skeleton-no-world-handle")
}
