// PORT-COMPLETE: g_saga.c 15/33
//! FAITHFUL port of `oracle/oracle/codemp/game/g_saga.c` — Siege gametype
//! game-side module.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep manifest,
//! then filled by the jampgame mega-pass (pass 2). STAGING ONLY — not wired
//! into crates/. Two remaining park classes:
//!
//! - **bg-boundary**: fns that read/write the bg-tier siege globals
//!   (`team1`/`team2`/`siege_info`/`gParseObjectives`/`gObjectiveCfgStr`/
//!   `siege_valid`/`bgSiegeClasses`/`bgNumSiegeClasses`/`bgNumSiegeTeams`/
//!   `weaponData`) — these are not `GameWorld` fields yet (fork 8a: still
//!   parked file-scope statics in `bg_saga.rs`, not threaded into
//!   `GameContext`).
//! - **unported-const**: fns that need a `#define`/enum value not present
//!   anywhere in the crate graph and not in the packet (`CS_SIEGE_*`,
//!   `SIEGE_POINTS_*`, `SIEGE_ROUND_BEGIN_TIME`, `SIEGE_ITEM_RESPAWN_TIME`,
//!   `MAX_SIEGE_INFO_SIZE`, `SIEGEITEM_STARTOFFRADAR`, `EF_RADAROBJECT`,
//!   `SIEGETEAM_TEAM1`/`SIEGETEAM_TEAM2`, `MAX_EXDATA_ENTS_TO_SEND`) — a
//!   placeholder value would silently diverge from the oracle, so these stay
//!   `todo!()` rather than guessing.
//!
//! `ENTITYNUM_NONE`/`SVF_BROADCAST` ARE resolvable (`mp_qshared::shared::
//! limits::ENTITYNUM_NONE`; `SVF_BROADCAST` locally defined per the
//! `g_team.rs` precedent) and used by the fns ported this pass.
//! See PORT-ESCALATION markers.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

use crate::bg_misc::{BG_FindItemForHoldable, BG_FindItemForWeapon};
use crate::bg_saga::BG_SiegeFindThemeForTeam;
use crate::client::gclient::gclient_t;
use crate::client::spectator_state::spectatorState_t;
use crate::client::player_team_state::playerTeamStateState_t;
use crate::client::CON_CONNECTED;
use crate::g_client::{ClientBegin, ClientSpawn, ClientUserinfoChanged};
use crate::g_combat::AddScore;
use crate::g_items::RegisterItem;
use crate::g_main::LogExit;
use crate::g_utils::{
    G_Find, G_PlayEffectID, G_RunExPhys, G_SetOrigin, G_Sound, G_TempEntity, G_UseTargets2,
    GlobalUse,
};
use crate::q_math::Q_irand;
use crate::q_shared::Info_SetValueForKey;
use mp_bg::public::entity_event::entity_event_t;
use mp_bg::public::holdable::HI_NUM_HOLDABLE;
use mp_bg::weapons::weapon_t::WP_NUM_WEAPONS;

// Raven `qboolean` is `c_int`; keep the source spelling at call sites.
// Source: `oracle/oracle/codemp/game/q_shared.h`
const qtrue: qboolean = 1;
const qfalse: qboolean = 0;

/// Raven `G_SiegeRegisterWeaponsAndHoldables` — go through all classes on a
/// team and register their weapons/items for precaching.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:51-87`
pub fn G_SiegeRegisterWeaponsAndHoldables(
    ctx: GameContext<'_>,
    team: c_int,
) {
    unsafe {
        let stm = BG_SiegeFindThemeForTeam(team);

        if !stm.is_null() {
            let mut i = 0;
            while i < (*stm).numClasses {
                let scl = (*stm).classes[i as usize];

                if !scl.is_null() {
                    let mut j = 0;
                    while j < WP_NUM_WEAPONS {
                        if (*scl).weapons & (1 << j) != 0 {
                            // we use this weapon so register it.
                            RegisterItem(ctx, BG_FindItemForWeapon(j));
                        }
                        j += 1;
                    }
                    j = 0;
                    while j < HI_NUM_HOLDABLE {
                        if (*scl).invenItems & (1 << j) != 0 {
                            // we use this item so register it.
                            RegisterItem(ctx, BG_FindItemForHoldable(j));
                        }
                        j += 1;
                    }
                }
                i += 1;
            }
        }
    }
}

// PORT-ESCALATION(unported-const): `trap_SetConfigstring(CS_SIEGE_WINTEAM, …)` —
// `CS_SIEGE_WINTEAM` is not ported anywhere in the crate graph and its value
// is not in the packet (only the fork-10 const/enum backfill list, which does
// not include the `CS_SIEGE_*` configstring-index family).
/// Raven `SiegeSetCompleteData` — tell clients this team won for their
/// intermission scoreboard.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:91-94`
pub fn SiegeSetCompleteData(
    ctx: GameContext<'_>,
    team: c_int,
) {
    todo!("Port SiegeSetCompleteData — parked: unported-const: CS_SIEGE_WINTEAM")
}

// PORT-ESCALATION(bg-boundary): reads/writes the bg-tier siege globals
// (`team1`/`team2`/`siege_info`/`gParseObjectives`/`bgSiegeClasses`/
// `bgNumSiegeClasses`/`bgNumSiegeTeams`/`gObjectiveCfgStr`) — none of these are
// GameWorld fields yet (fork 8a: bg-tier state, still parked in `bg_saga.rs`)
// — and several `CS_SIEGE_*`/`MAX_SIEGE_INFO_SIZE` consts are unported too.
/// Raven `InitSiegeMode`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:96-373`
pub fn InitSiegeMode(ctx: GameContext<'_>) {
    todo!("Port InitSiegeMode — parked: bg-boundary (team1/team2/siege_info/gParseObjectives/bgSiegeClasses) + unported-const (CS_SIEGE_*/MAX_SIEGE_INFO_SIZE)")
}

// PORT-ESCALATION(bg-boundary): parses/mutates `gObjectiveCfgStr`, a bg-tier
// siege global not yet a GameWorld field (fork 8a), and calls
// `trap_SetConfigstring(CS_SIEGE_OBJECTIVES, …)` — `CS_SIEGE_OBJECTIVES` is
// also unported.
/// Raven `G_SiegeSetObjectiveComplete`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:375-427`
pub fn G_SiegeSetObjectiveComplete(
    ctx: GameContext<'_>,
    team: c_int,
    objective: c_int,
    failIt: qboolean,
) {
    todo!("Port G_SiegeSetObjectiveComplete — parked: bg-boundary (gObjectiveCfgStr) + unported-const (CS_SIEGE_OBJECTIVES)")
}

// PORT-ESCALATION(bg-boundary): reads `gObjectiveCfgStr`, a bg-tier siege
// global not yet a GameWorld field (fork 8a).
/// Raven `G_SiegeGetCompletionStatus` — qtrue if objective is currently complete.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:430-480`
pub fn G_SiegeGetCompletionStatus(
    ctx: GameContext<'_>,
    team: c_int,
    objective: c_int,
) -> qboolean {
    todo!("Port G_SiegeGetCompletionStatus — parked: bg-boundary (gObjectiveCfgStr)")
}

/// Raven `UseSiegeTarget` — use the player who triggered the object to fire the
/// objective's target.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:482-526`
pub fn UseSiegeTarget(
    ctx: GameContext<'_>,
    other: *mut gentity_t,
    en: *mut gentity_t,
    target: *mut c_char,
) {
    unsafe {
        // Raven: "looks like we don't have access to a player, so just use
        // the activating entity" — `ent` is computed but Raven's own body
        // never reads it (only `en`/`other` below); kept for parity with the
        // oracle's dead local.
        let _ent: *mut gentity_t = if en.is_null() || (*en).client.is_null() {
            other
        } else {
            en
        };

        if en.is_null() {
            return;
        }
        if target.is_null() {
            return;
        }

        let targetname_ofs = core::mem::offset_of!(gentity_t, targetname) as c_int;

        let mut t: *mut gentity_t = core::ptr::null_mut();
        loop {
            t = G_Find(ctx, t, targetname_ofs, target as *const c_char);
            if t.is_null() {
                break;
            }
            if t == en {
                // G_Printf("WARNING: Entity used itself.\n") — no format args.
                crate::g_main::G_Printf(ctx, b"WARNING: Entity used itself.\n\0".as_ptr() as *const c_char);
            } else if !(*t).use_.is_none() {
                GlobalUse(t, en, en);
            }
            if (*en).inuse == 0 {
                crate::g_main::G_Printf(ctx, b"entity was removed while using targets\n\0".as_ptr() as *const c_char);
                return;
            }
        }
    }
}

// Raven's `SVF_BROADCAST` svflags `#define` is not yet ported anywhere in the
// crate graph; defined locally, verbatim, following the `g_team.rs` precedent.
// Source: `oracle/oracle/codemp/game/g_public.h:20`
const SVF_BROADCAST: c_int = 0x00000020;

/// Raven `SiegeBroadcast_OBJECTIVECOMPLETE`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:528-540`
pub fn SiegeBroadcast_OBJECTIVECOMPLETE(
    ctx: GameContext<'_>,
    team: c_int,
    client: c_int,
    objective: c_int,
) {
    unsafe {
        let nomatter: vec3_t = [0.0, 0.0, 0.0];

        let te = G_TempEntity(ctx, nomatter, entity_event_t::EV_SIEGE_OBJECTIVECOMPLETE as c_int);
        (*te).r.svFlags |= SVF_BROADCAST;
        (*te).s.eventParm = team;
        (*te).s.weapon = client;
        (*te).s.trickedentindex = objective;
    }
}

/// Raven `SiegeBroadcast_ROUNDOVER`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:542-553`
pub fn SiegeBroadcast_ROUNDOVER(
    ctx: GameContext<'_>,
    winningteam: c_int,
    winningclient: c_int,
) {
    unsafe {
        let nomatter: vec3_t = [0.0, 0.0, 0.0];

        let te = G_TempEntity(ctx, nomatter, entity_event_t::EV_SIEGE_ROUNDOVER as c_int);
        (*te).r.svFlags |= SVF_BROADCAST;
        (*te).s.eventParm = winningteam;
        (*te).s.weapon = winningclient;
    }
}

// PORT-ESCALATION(unported-const): `AddScore(…, SIEGE_POINTS_OBJECTIVECOMPLETED)`
// — the `SIEGE_POINTS_*` score-award consts are not ported anywhere in the
// crate graph and their values are not in the packet (only the fork-10
// backfill list, which does not include them); a placeholder value would
// silently diverge from the oracle's actual scoring.
/// Raven `BroadcastObjectiveCompletion`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:555-564`
pub fn BroadcastObjectiveCompletion(
    ctx: GameContext<'_>,
    team: c_int,
    objective: c_int,
    r#final: c_int,
    client: c_int,
) {
    todo!("Port BroadcastObjectiveCompletion — parked: unported-const (SIEGE_POINTS_OBJECTIVECOMPLETED)")
}

/// Raven `AddSiegeWinningTeamPoints`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:566-589`
pub fn AddSiegeWinningTeamPoints(
    ctx: GameContext<'_>,
    team: c_int,
    winner: c_int,
) {
    todo!("Port AddSiegeWinningTeamPoints — parked: unported-const (SIEGE_POINTS_TEAMWONROUND/SIEGE_POINTS_FINALOBJECTIVECOMPLETED)")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): memsets the file-scope
// `g_siegePersistant` global and calls `trap_SiegePersSet` — both need the
// GameWorld/engine handle.
/// Raven `SiegeClearSwitchData`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:591-595`
pub fn SiegeClearSwitchData(ctx: GameContext<'_>) {
    unsafe {
        (*ctx.world).globals.g_siegePersistant = Default::default();
        trap::SiegePersSet(
            ctx.engine,
            mp_abi::game::syscalls::G_SIEGEPERSSET::GSiegeperssetArgs::new(
                &(*ctx.world).globals.g_siegePersistant as *const siegePers_t,
            ),
        );
    }
}

// PORT-ESCALATION(unported-const): compares/writes `SIEGETEAM_TEAM1`/
// `SIEGETEAM_TEAM2` — neither is ported anywhere in the crate graph (not even
// as a raw value in a comment) and their values are not in the packet; a
// placeholder would silently diverge from the oracle's actual team-index
// scheme.
/// Raven `SiegeDoTeamAssign` — yeah, this is great...
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:597-630`
pub fn SiegeDoTeamAssign(ctx: GameContext<'_>) {
    todo!("Port SiegeDoTeamAssign — parked: unported-const (SIEGETEAM_TEAM1/SIEGETEAM_TEAM2)")
}

/// Raven `SiegeTeamSwitch`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:632-652`
pub fn SiegeTeamSwitch(
    ctx: GameContext<'_>,
    winTeam: c_int,
    winTime: c_int,
) {
    unsafe {
        trap::SiegePersGet(
            ctx.engine,
            mp_abi::game::syscalls::G_SIEGEPERSGET::GSiegepersgetArgs::new(
                &mut (*ctx.world).globals.g_siegePersistant as *mut siegePers_t,
            ),
        );
        if (*ctx.world).globals.g_siegePersistant.beatingTime != 0 {
            // was already in "switched" mode, change back. announce the
            // winning team. either the first team won again, or the second
            // team beat the time set by the initial team. In any case the
            // winTeam here is the overall winning team.
            SiegeSetCompleteData(ctx, winTeam);
            SiegeClearSwitchData(ctx);
        } else {
            // go into "beat their time" mode
            (*ctx.world).globals.g_siegePersistant.beatingTime = qtrue;
            (*ctx.world).globals.g_siegePersistant.lastTeam = winTeam;
            (*ctx.world).globals.g_siegePersistant.lastTime = winTime;

            trap::SiegePersSet(
                ctx.engine,
                mp_abi::game::syscalls::G_SIEGEPERSSET::GSiegeperssetArgs::new(
                    &(*ctx.world).globals.g_siegePersistant as *const siegePers_t,
                ),
            );
        }
    }
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier siege globals (`team1`/
// `team2`/`siege_info`/`gParseObjectives`), not yet GameWorld fields (fork
// 8a), and calls `trap_SetConfigstring(CS_SIEGE_STATE, …)` —
// `CS_SIEGE_STATE` is also unported.
/// Raven `SiegeRoundComplete`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:654-742`
pub fn SiegeRoundComplete(
    ctx: GameContext<'_>,
    winningteam: c_int,
    winningclient: c_int,
) {
    todo!("Port SiegeRoundComplete — parked: bg-boundary (team1/team2/siege_info/gParseObjectives) + unported-const (CS_SIEGE_STATE)")
}

// PORT-ESCALATION(bg-boundary): indexes `bgSiegeClasses`/`bgNumSiegeClasses`
// (bg-tier siege globals, not yet GameWorld fields — fork 8a, still parked in
// `bg_saga.rs`).
/// Raven `G_ValidateSiegeClassForTeam`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:744-784`
pub fn G_ValidateSiegeClassForTeam(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    team: c_int,
) {
    todo!("Port G_ValidateSiegeClassForTeam — parked: bg-boundary (bgSiegeClasses/bgNumSiegeClasses)")
}

/// Raven `SetTeamQuick` — bypass most of the normal checks in SetTeam.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:787-834`
pub fn SetTeamQuick(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    team: c_int,
    doBegin: qboolean,
) {
    unsafe {
        // Raven's `MAX_INFO_STRING` is not yet a ported const (see
        // `q_shared.rs`'s `Info_SetValueForKey` precedent); hardcoded 1024
        // matching that precedent.
        let mut userinfo: [c_char; 1024] = [0; 1024];

        trap::GetUserinfo(
            ctx.engine,
            mp_abi::game::syscalls::G_GET_USERINFO::GGetUserinfoArgs::new(
                (*ent).s.number,
                userinfo.as_mut_ptr(),
                userinfo.len() as c_int,
            ),
        );

        if (*ctx.world).cvars.g_gametype.integer == GT_SIEGE {
            G_ValidateSiegeClassForTeam(ctx, ent, team);
        }

        let cl = (*ent).client as *mut gclient_t;
        (*cl).sess.sessionTeam = team;

        if team == TEAM_SPECTATOR {
            (*cl).sess.spectatorState = spectatorState_t::SPECTATOR_FREE;
            Info_SetValueForKey(userinfo.as_mut_ptr(), b"team\0".as_ptr() as *const c_char, b"s\0".as_ptr() as *const c_char);
        } else {
            (*cl).sess.spectatorState = spectatorState_t::SPECTATOR_NOT;
            if team == TEAM_RED {
                Info_SetValueForKey(userinfo.as_mut_ptr(), b"team\0".as_ptr() as *const c_char, b"r\0".as_ptr() as *const c_char);
            } else if team == TEAM_BLUE {
                Info_SetValueForKey(userinfo.as_mut_ptr(), b"team\0".as_ptr() as *const c_char, b"b\0".as_ptr() as *const c_char);
            } else {
                Info_SetValueForKey(userinfo.as_mut_ptr(), b"team\0".as_ptr() as *const c_char, b"?\0".as_ptr() as *const c_char);
            }
        }

        let info_cstring = std::ffi::CString::new(
            core::ffi::CStr::from_ptr(userinfo.as_ptr()).to_bytes(),
        )
        .unwrap();
        trap::SetUserinfo(
            ctx.engine,
            mp_abi::game::syscalls::G_SET_USERINFO::GSetUserinfoArgs::new((*ent).s.number, info_cstring),
        );

        (*cl).sess.spectatorClient = 0;

        (*cl).pers.teamState.state = playerTeamStateState_t::TEAM_BEGIN;

        ClientUserinfoChanged(ctx, (*ent).s.number);

        if doBegin != 0 {
            ClientBegin(ctx, (*ent).s.number, qfalse);
        }
    }
}

/// Raven `SiegeRespawn` — respawn a siege player, honoring a pending team switch.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:836-851`
pub fn SiegeRespawn(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    unsafe {
        let client = (*ent).client as *mut gclient_t;

        if (*client).sess.sessionTeam != (*client).sess.siegeDesiredTeam {
            SetTeamQuick(ctx, ent, (*client).sess.siegeDesiredTeam, qtrue);
        } else {
            ClientSpawn(ctx, ent);
            // add a teleportation effect
            let tent = G_TempEntity(ctx, 
                (*client).ps.origin,
                entity_event_t::EV_PLAYER_TELEPORT_IN as c_int,
            );
            (*tent).s.clientNum = (*ent).s.clientNum;
        }
    }
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_info` global (not yet
// a GameWorld field — fork 8a) and calls `trap_SetConfigstring(CS_SIEGE_STATE,
// …)` — `CS_SIEGE_STATE` is also unported.
/// Raven `SiegeBeginRound` — entNum is just used as something to fire targets
/// from.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:853-903`
pub fn SiegeBeginRound(
    ctx: GameContext<'_>,
    entNum: c_int,
) {
    todo!("Port SiegeBeginRound — parked: bg-boundary (siege_info) + unported-const (CS_SIEGE_STATE)")
}

// PORT-ESCALATION(unported-const): the `SIEGE_ROUND_BEGIN_TIME` timing const
// and `trap_SetConfigstring(CS_SIEGE_STATE, …)` — neither `CS_SIEGE_STATE` nor
// `SIEGE_ROUND_BEGIN_TIME` is ported anywhere in the crate graph and their
// values are not in the packet.
/// Raven `SiegeCheckTimers`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:905-1013`
pub fn SiegeCheckTimers(ctx: GameContext<'_>) {
    todo!("Port SiegeCheckTimers — parked: unported-const (SIEGE_ROUND_BEGIN_TIME/CS_SIEGE_STATE)")
}

// PORT-ESCALATION(unported-const): compares `team == SIEGETEAM_TEAM1` — not
// ported anywhere in the crate graph and its value is not in the packet.
/// Raven `SiegeObjectiveCompleted`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1015-1058`
pub fn SiegeObjectiveCompleted(
    ctx: GameContext<'_>,
    team: c_int,
    objective: c_int,
    r#final: c_int,
    client: c_int,
) {
    todo!("Port SiegeObjectiveCompleted — parked: unported-const (SIEGETEAM_TEAM1)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier siege globals (`siege_valid`/
// `team1`/`team2`/`siege_info`/`gParseObjectives`), none of which are GameWorld
// fields yet (fork 8a, still parked in `bg_saga.rs`).
/// Raven `siegeTriggerUse`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1060-1128`
pub fn siegeTriggerUse(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port siegeTriggerUse — parked: bg-boundary (siege_valid/team1/team2/siege_info/gParseObjectives)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_valid` global (not
// yet a GameWorld field — fork 8a); also uses the unported
// `SIEGEITEM_STARTOFFRADAR` spawnflag const.
/// Raven `SP_info_siege_objective`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1137-1179`
pub fn SP_info_siege_objective(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SP_info_siege_objective — parked: bg-boundary (siege_valid) + unported-const (SIEGEITEM_STARTOFFRADAR)")
}

// PORT-ESCALATION(unported-const): toggles `s.eFlags & EF_RADAROBJECT`; the
// `EF_RADAROBJECT` eflags bit is not ported anywhere in the crate graph and
// its value is not in the packet (same blocker as `g_turret_G2.rs`'s
// `SP_misc_turretG2` park — no committed value exists anywhere to reuse).
/// Raven `SiegeIconUse` — toggle it on and off.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1182-1194`
pub fn SiegeIconUse(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port SiegeIconUse — parked: unported-const (EF_RADAROBJECT)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_valid` global (not
// yet a GameWorld field — fork 8a); also calls `Com_Error` (variadic — the
// call site here passes no format args, so that part is not itself blocking)
// and uses the unported `EF_RADAROBJECT` eflags bit.
/// Raven `SP_info_siege_radaricon`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1203-1234`
pub fn SP_info_siege_radaricon(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SP_info_siege_radaricon — parked: bg-boundary (siege_valid) + unported-const (EF_RADAROBJECT)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier siege globals (`team1`/
// `team2`/`siege_info`/`gParseObjectives`), not yet GameWorld fields (fork 8a).
/// Raven `decompTriggerUse`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1236-1291`
pub fn decompTriggerUse(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port decompTriggerUse — parked: bg-boundary (team1/team2/siege_info/gParseObjectives)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_valid` global, not
// yet a GameWorld field (fork 8a).
/// Raven `SP_info_siege_decomplete`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1297-1315`
pub fn SP_info_siege_decomplete(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SP_info_siege_decomplete — parked: bg-boundary (siege_valid)")
}

/// Raven `siegeEndUse` — do a LogExit for siege when used.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1317-1320`
pub fn siegeEndUse(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    LogExit(ctx, b"Round ended\0".as_ptr() as *const c_char);
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_valid` global, not
// yet a GameWorld field (fork 8a).
/// Raven `SP_target_siege_end`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1325-1334`
pub fn SP_target_siege_end(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SP_target_siege_end — parked: bg-boundary (siege_valid)")
}

/// Raven `SiegeItemRemoveOwner`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1338-1349`
pub fn SiegeItemRemoveOwner(
    ent: *mut gentity_t,
    carrier: *mut gentity_t,
) {
    unsafe {
        (*ent).genericValue2 = 0; // Remove picked-up flag
        (*ent).genericValue8 = ENTITYNUM_NONE; // Mark entity carrying us as none

        if !carrier.is_null() {
            let cl = (*carrier).client as *mut gclient_t;
            (*cl).holdingObjectiveItem = 0; // The carrier is no longer carrying us
            (*carrier).r.svFlags &= !SVF_BROADCAST;
        }
    }
}

/// Raven `SiegeItemRespawnEffect` — play the objective-item respawn effect and
/// fire its respawn target.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1351-1370`
pub fn SiegeItemRespawnEffect(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    newOrg: vec3_t,
) {
    unsafe {
        if !(*ent).target5.is_null() && *(*ent).target5 != 0 {
            G_UseTargets2(ctx, ent, ent, (*ent).target5 as *const c_char);
        }

        if (*ent).genericValue10 == 0 {
            // no respawn effect
            return;
        }

        let upAng: vec3_t = [0.0, 0.0, 1.0];

        // Play it once on the current origin, and once on the origin we're
        // respawning to.
        G_PlayEffectID((*ent).genericValue10, (*ent).r.currentOrigin, upAng);
        G_PlayEffectID((*ent).genericValue10, newOrg, upAng);
    }
}

/// Raven `SiegeItemRespawnOnOriginalSpot`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1372-1380`
pub fn SiegeItemRespawnOnOriginalSpot(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    carrier: *mut gentity_t,
) {
    unsafe {
        SiegeItemRespawnEffect(ctx, ent, (*ent).pos1);
        G_SetOrigin(ent, (*ent).pos1);
        SiegeItemRemoveOwner(ent, carrier);

        // Stop the item from flashing on the radar
        (*ent).s.time2 = 0;
    }
}

// PORT-ESCALATION(unported-const): reads/writes `genericValue9` against a
// `SIEGE_ITEM_RESPAWN_TIME` timer const not ported anywhere in the crate graph
// (its value is not in the packet); everything else in this body (bolt-to-
// player, physics via `G_RunExPhys`, `trap_PointContents`/`CONTENTS_NODROP`
// carrier-loss handling) is otherwise portable against the current state.
/// Raven `SiegeItemThink`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1382-1475`
pub fn SiegeItemThink(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SiegeItemThink — parked: unported-const (SIEGE_ITEM_RESPAWN_TIME)")
}

/// Raven `SiegeItemTouch`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1477-1545`
pub fn SiegeItemTouch(
    ctx: GameContext<'_>,
    self_: *mut gentity_t,
    other: *mut gentity_t,
    trace: *mut trace_t,
) {
    unsafe {
        if other.is_null()
            || (*other).inuse == 0
            || (*other).client.is_null()
            || (*other).s.eType == entityType_t::ET_NPC as c_int
        {
            if !trace.is_null() && (*trace).startsolid != 0 {
                // let me out! (ideally this should not happen, but such is life)
                let mut escapePos = (*self_).r.currentOrigin;
                escapePos[2] += 1.0;

                // I hope you weren't stuck in the ceiling.
                G_SetOrigin(self_, escapePos);
            }
            return;
        }

        if (*other).health < 1 {
            // dead people can't pick us up.
            return;
        }

        let ocl = (*other).client as *mut gclient_t;

        if (*ocl).holdingObjectiveItem != 0 {
            // this guy's already carrying a siege item
            return;
        }

        if (*ocl).ps.pm_type == pmtype_t::PM_SPECTATOR as c_int {
            // spectators don't pick stuff up
            return;
        }

        if (*self_).genericValue2 != 0 {
            // Am I already picked up?
            return;
        }

        if (*self_).genericValue6 == (*ocl).sess.sessionTeam {
            // Set to not be touchable by players on this team.
            return;
        }

        if (*ctx.world).globals.gSiegeRoundBegun == 0 {
            // can't pick it up if round hasn't started yet
            return;
        }

        if (*self_).noise_index != 0 {
            // play the pickup noise.
            G_Sound(ctx, other, CHAN_AUTO, (*self_).noise_index);
        }

        (*self_).genericValue2 = 1; // Mark it as picked up.

        (*ocl).holdingObjectiveItem = (*other).s.number;
        (*other).r.svFlags |= SVF_BROADCAST; // broadcast player while he carries this
        (*self_).genericValue8 = (*other).s.number; // Keep the index so we know who is "carrying" us

        (*self_).genericValue9 = 0; // So it doesn't think it has to respawn.

        if !(*self_).target2.is_null()
            && *(*self_).target2 != 0
            && ((*self_).genericValue4 == 0 || (*self_).genericValue5 == 0)
        {
            // fire the target for pickup, if it's set to fire every time, or
            // set to only fire the first time and the first time has not yet
            // occured.
            G_UseTargets2(ctx, self_, self_, (*self_).target2 as *const c_char);
            (*self_).genericValue5 = 1; // mark it as having been picked up
        }

        // time2 set to -1 will blink the item on the radar indefinately
        (*self_).s.time2 = -1;
    }
}

/// Raven `SiegeItemPain` — pulse the radar icon to show the item is under attack.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1547-1551`
pub fn SiegeItemPain(
    ctx: GameContext<'_>,
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    unsafe {
        (*self_).s.time2 = (*ctx.world).level.time;
    }
}

/// Raven `SiegeItemDie`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1553-1574`
pub fn SiegeItemDie(
    ctx: GameContext<'_>,
    self_: *mut gentity_t,
    inflictor: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
    meansOfDeath: c_int,
) {
    unsafe {
        (*self_).takedamage = qfalse; // don't die more than once

        if (*self_).genericValue3 != 0 {
            // An indexed effect to play on death
            let upAng: vec3_t = [0.0, 0.0, 1.0];
            G_PlayEffectID((*self_).genericValue3, (*self_).r.currentOrigin, upAng);
        }

        (*self_).neverFree = qfalse;
        (*self_).think = Some(EntThink::G_FreeEntity);
        (*self_).nextthink = (*ctx.world).level.time;

        // Fire off the death target if we've got one.
        if !(*self_).target4.is_null() && *(*self_).target4 != 0 {
            G_UseTargets2(ctx, self_, self_, (*self_).target4 as *const c_char);
        }
    }
}

// PORT-ESCALATION(unported-const): sets `s.eFlags |= EF_RADAROBJECT` — the
// `EF_RADAROBJECT` eflags bit is not ported anywhere in the crate graph and
// its value is not in the packet.
/// Raven `SiegeItemUse` — once used, become active.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1576-1623`
pub fn SiegeItemUse(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port SiegeItemUse — parked: unported-const (EF_RADAROBJECT)")
}

// PORT-ESCALATION(bg-boundary): reads the bg-tier `siege_valid` global (not
// yet a GameWorld field — fork 8a); also uses the unported
// `SIEGEITEM_STARTOFFRADAR`/`EF_RADAROBJECT` consts.
/// Raven `SP_misc_siege_item`.
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1676-1835`
pub fn SP_misc_siege_item(
    ctx: GameContext<'_>,
    ent: *mut gentity_t,
) {
    todo!("Port SP_misc_siege_item — parked: bg-boundary (siege_valid) + unported-const (SIEGEITEM_STARTOFFRADAR, EF_RADAROBJECT)")
}

// PORT-ESCALATION(bg-boundary): reads the `weaponData` bg-tier weapon-data
// table (not a GameWorld field — fork 8a, a const table, not threaded here)
// and the unported `MAX_EXDATA_ENTS_TO_SEND` const; its value is not in the
// packet.
/// Raven `G_SiegeClientExData` — send extra data about other clients in this
/// client's PVS (support guy, etc.).
///
/// Source: `oracle/oracle/codemp/game/g_saga.c:1845-1886`
pub fn G_SiegeClientExData(
    ctx: GameContext<'_>,
    msgTarg: *mut gentity_t,
) {
    todo!("Port G_SiegeClientExData — parked: bg-boundary (weaponData) + unported-const (MAX_EXDATA_ENTS_TO_SEND)")
}
