// PORT-COMPLETE: g_svcmds.c 1/14
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/g_svcmds.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

// IP filter type: holds mask and compare value for IP filtering.
// Source: oracle/oracle/codemp/game/g_svcmds.c:41-45
#[repr(C)]
#[derive(Clone, Copy)]
struct ipFilter_t {
    mask: c_uint,
    compare: c_uint,
}

// Raven `qboolean` is `c_int`; keep the source spelling at assignment sites.
// Source: `oracle/oracle/codemp/game/q_shared.h`
const qtrue: qboolean = 1;
const qfalse: qboolean = 0;

// Constants from the Raven source.
const MAX_IPFILTERS: usize = 1024;

// File-scope globals: IP filtering state.
// Source: oracle/oracle/codemp/game/g_svcmds.c:54-55
static mut IP_FILTERS: [ipFilter_t; MAX_IPFILTERS] = [ipFilter_t {
    mask: 0,
    compare: 0xffffffff,
}; MAX_IPFILTERS];
static mut NUM_IP_FILTERS: c_int = 0;

/// Raven `StringToFilter`.
///
/// Parse an IP address string into mask and compare values for IP filtering.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:62-102`
pub fn StringToFilter(s: *mut c_char, f: *mut c_void) -> qboolean {
    let f = f as *mut ipFilter_t;

    unsafe {
        let mut b: [u8; 4] = [0; 4];
        let mut m: [u8; 4] = [0; 4];

        let mut i = 0;
        let mut s_ptr = s;

        // Parse up to 4 octets
        while i < 4 {
            // Check first character is a digit
            if *s_ptr < b'0' as c_char || *s_ptr > b'9' as c_char {
                G_Printf(
                    b"Bad filter address: %s\n\0".as_ptr() as *const c_char,
                    s,
                );
                return qfalse;
            }

            // Parse the number: accumulate decimal digits
            let mut num: u32 = 0;
            while *s_ptr >= b'0' as c_char && *s_ptr <= b'9' as c_char {
                num = num * 10 + ((*s_ptr as u8 - b'0') as u32);
                s_ptr = s_ptr.add(1);
            }
            b[i] = (num & 0xff) as u8;
            if b[i] != 0 {
                m[i] = 255;
            }

            // Check for end or next octet
            if *s_ptr == 0 {
                break;
            }
            if *s_ptr == b':' as c_char {
                break;
            }
            s_ptr = s_ptr.add(1); // skip the dot
            i += 1;
        }

        // Set mask and compare from bytes
        (*f).mask = (m[0] as c_uint)
            | ((m[1] as c_uint) << 8)
            | ((m[2] as c_uint) << 16)
            | ((m[3] as c_uint) << 24);
        (*f).compare = (b[0] as c_uint)
            | ((b[1] as c_uint) << 8)
            | ((b[2] as c_uint) << 16)
            | ((b[3] as c_uint) << 24);

        return qtrue;
    }
}

// PORT-ESCALATION(file-scope-globals-ip-filters): reads/writes `ipFilters`,
// `numIPFilters` file-scope globals not available in skeleton signature.
/// Raven `UpdateIPBans`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:109-127`
pub fn UpdateIPBans() {
    todo!("Port UpdateIPBans — parked: file-scope-globals-ip-filters")
}

// PORT-ESCALATION(file-scope-globals-ip-filters): reads `g_filterBan`,
// `ipFilters`, `numIPFilters` file-scope globals not available in skeleton signature.
/// Raven `G_FilterPacket`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:134-166`
pub fn G_FilterPacket(from: *mut c_char) -> qboolean {
    todo!("Port G_FilterPacket — parked: file-scope-globals-ip-filters")
}

// PORT-ESCALATION(file-scope-globals-ip-filters): reads/writes `ipFilters`,
// `numIPFilters` file-scope globals not available in skeleton signature.
/// Raven `AddIP`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:173-194`
pub fn AddIP(str: *mut c_char) {
    todo!("Port AddIP — parked: file-scope-globals-ip-filters")
}

// PORT-ESCALATION(file-scope-globals-cvar): reads `g_banIPs` cvar field
// not available in skeleton signature.
/// Raven `G_ProcessIPBans`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:201-218`
pub fn G_ProcessIPBans() {
    todo!("Port G_ProcessIPBans — parked: file-scope-globals-cvar")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_Argc,
// trap_Argv requiring an &Engine handle not available in skeleton signature.
/// Raven `Svcmd_AddIP_f`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:226-239`
pub fn Svcmd_AddIP_f() {
    todo!("Port Svcmd_AddIP_f — parked: raw-ptr-skeleton-no-engine-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_Argc,
// trap_Argv requiring an &Engine handle not available in skeleton signature.
/// Raven `Svcmd_RemoveIP_f`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:246-274`
pub fn Svcmd_RemoveIP_f() {
    todo!("Port Svcmd_RemoveIP_f — parked: raw-ptr-skeleton-no-engine-handle")
}

// PORT-ESCALATION(file-scope-globals-ip-filters): reads `ipFilters`,
// `numIPFilters` file-scope globals not available in skeleton signature.
/// Raven `Svcmd_ListIPs_f`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:276-297`
pub fn Svcmd_ListIPs_f() {
    todo!("Port Svcmd_ListIPs_f — parked: file-scope-globals-ip-filters")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_FS_*,
// trap_FS_Write requiring an &Engine handle not available in skeleton signature.
/// Raven `G_SaveBanIP`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:299-331`
pub fn G_SaveBanIP() {
    todo!("Port G_SaveBanIP — parked: raw-ptr-skeleton-no-engine-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_FS_*
// requiring an &Engine handle not available in skeleton signature.
/// Raven `G_LoadIPBans`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:333-379`
pub fn G_LoadIPBans() {
    todo!("Port G_LoadIPBans — parked: raw-ptr-skeleton-no-engine-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `g_entities`,
// `level` globals not available in skeleton signature.
/// Raven `Svcmd_EntityList_f`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:386-443`
pub fn Svcmd_EntityList_f() {
    todo!("Port Svcmd_EntityList_f — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-world-handle): reads `level`
// global not available in skeleton signature.
/// Raven `ClientForString`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:445-480`
pub fn ClientForString(s: *const c_char) -> *mut gclient_t {
    todo!("Port ClientForString — parked: raw-ptr-skeleton-no-world-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_Argv
// requiring an &Engine handle not available in skeleton signature.
/// Raven `Svcmd_ForceTeam_f`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:489-503`
pub fn Svcmd_ForceTeam_f() {
    todo!("Port Svcmd_ForceTeam_f — parked: raw-ptr-skeleton-no-engine-handle")
}

// PORT-ESCALATION(raw-ptr-skeleton-no-engine-handle): calls trap_Argv,
// trap_SendServerCommand requiring an &Engine handle not available in skeleton signature.
/// Raven `ConsoleCommand`.
///
/// Source: `oracle/oracle/codemp/game/g_svcmds.c:513-575`
pub fn ConsoleCommand() -> qboolean {
    todo!("Port ConsoleCommand — parked: raw-ptr-skeleton-no-engine-handle")
}
