//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_stats.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

// Unported types referenced in this file (need porting before this compiles):
// rank_t


/// Raven `NPC_ReactionTime`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:220-223`
pub fn NPC_ReactionTime() -> c_int {
    todo!("Port NPC_ReactionTime — oracle/oracle/codemp/game/NPC_stats.c:220")
}

/// Raven `TranslateRankName`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:287-330`
pub fn TranslateRankName(
    name: *const c_char,
) -> c_int {
    //TODO: Port rank_t (unported return enum; C int-width)
    todo!("Port TranslateRankName — oracle/oracle/codemp/game/NPC_stats.c:287")
}

/// Raven `G_ParseAnimFileSet`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:424-437`
pub fn G_ParseAnimFileSet(
    filename: *const c_char,
    animCFG: *const c_char,
    animFileIndex: *mut c_int,
) -> qboolean {
    todo!("Port G_ParseAnimFileSet — oracle/oracle/codemp/game/NPC_stats.c:424")
}

/// Raven `NPC_PrecacheAnimationCFG`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:439-548`
pub fn NPC_PrecacheAnimationCFG(
    NPC_type: *const c_char,
) {
    todo!("Port NPC_PrecacheAnimationCFG — oracle/oracle/codemp/game/NPC_stats.c:439")
}

/// Raven `NPC_PrecacheWeapons`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:551-591`
pub fn NPC_PrecacheWeapons(
    playerTeam: team_t,
    spawnflags: c_int,
    NPCtype: *mut c_char,
) {
    todo!("Port NPC_PrecacheWeapons — oracle/oracle/codemp/game/NPC_stats.c:551")
}

/// Raven `NPC_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:599-873`
pub fn NPC_Precache(
    spawner: *mut gentity_t,
) {
    todo!("Port NPC_Precache — oracle/oracle/codemp/game/NPC_stats.c:599")
}

/// Raven `NPC_ParseParms`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:974-3233`
pub fn NPC_ParseParms(
    NPCName: *const c_char,
    NPC: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_ParseParms — oracle/oracle/codemp/game/NPC_stats.c:974")
}

/// Raven `NPC_LoadParms`.
///
/// Source: `oracle/oracle/codemp/game/NPC_stats.c:3241-3302`
pub fn NPC_LoadParms() {
    todo!("Port NPC_LoadParms — oracle/oracle/codemp/game/NPC_stats.c:3241")
}
