// PORT-COMPLETE: NPC_move.c 2/11
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_move.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;
use crate::q_math::{AngleVectors, VectorNormalize};

/// File-scope static for `NPC_move.c` navigation state (oracle/oracle/codemp/game/NPC_move.c:14).
/// Zeroed initially, written by NPC_GetMoveDirection and similar functions (all parked).
/// Read by NAV_GetLastMove.
static mut FRAME_NAV_INFO: navInfo_t = navInfo_t {
    blocker: std::ptr::null_mut(),
    direction: [0.0; 3],
    pathDirection: [0.0; 3],
    distance: 0.0,
    trace: trace_t {
        allsolid: 0,
        startsolid: 0,
        entityNum: 0,
        fraction: 0.0,
        endpos: [0.0; 3],
        plane: cplane_t {
            normal: [0.0; 3],
            dist: 0.0,
            r#type: 0,
            signbits: 0,
            pad: [0; 2],
        },
        surfaceFlags: 0,
        contents: 0,
    },
    flags: 0,
};

/// Raven `NPC_ClearPathToGoal`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:27-70`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`NPCInfo` globals
// set by ai_main.c think-loop; no channel to reach them from this
// context-free faithful signature.
pub fn NPC_ClearPathToGoal(
    ctx: GameContext<'_>,
    dir: vec3_t,
    goal: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_ClearPathToGoal — parked: ai-context")
}

/// Raven `NPC_CheckCombatMove`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:78-95`
// PORT-ESCALATION(ai-context): reads ambient `NPC`/`NPCInfo` globals;
// no channel to reach them from this context-free faithful signature.
pub fn NPC_CheckCombatMove(ctx: GameContext<'_>) -> qboolean {
    todo!("Port NPC_CheckCombatMove — parked: ai-context")
}

/// Raven `NPC_LadderMove`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:103-118`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`ucmd` globals;
// no channel to reach them from this context-free faithful signature.
pub fn NPC_LadderMove(
    ctx: GameContext<'_>,
    dir: vec3_t,
) {
    todo!("Port NPC_LadderMove — parked: ai-context")
}

/// Raven `NPC_GetMoveInformation`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:126-141`
// PORT-ESCALATION(ai-context): reads ambient `NPC`/`NPCInfo` globals;
// no channel to reach them from this context-free faithful signature.
pub fn NPC_GetMoveInformation(
    ctx: GameContext<'_>,
    dir: vec3_t,
    distance: *mut f32,
) -> qboolean {
    todo!("Port NPC_GetMoveInformation — parked: ai-context")
}

/// Raven `NAV_GetLastMove`.
///
/// Copies the file-scope `frameNavInfo` to the caller's buffer. Called after
/// navigation functions have populated `frameNavInfo` in the same frame.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:149-152`
pub fn NAV_GetLastMove(
    ctx: GameContext<'_>,
    info: *mut navInfo_t,
) {
    unsafe {
        *info = FRAME_NAV_INFO;
    }
}

/// Raven `NPC_GetMoveDirection`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:160-230`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`NPCInfo` globals
// and file-scope `frameNavInfo`; calls navigation functions that need
// these; no channel to reach them from this context-free faithful signature.
pub fn NPC_GetMoveDirection(
    ctx: GameContext<'_>,
    out: vec3_t,
    distance: *mut f32,
) -> qboolean {
    todo!("Port NPC_GetMoveDirection — parked: ai-context")
}

/// Raven `NPC_GetMoveDirectionAltRoute`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:239-322`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`NPCInfo` globals,
// file-scope `frameNavInfo`, and accesses `d_altRoutes` cvar; calls
// navigation functions; no channel to reach them from this context-free
// faithful signature.
pub fn NPC_GetMoveDirectionAltRoute(
    ctx: GameContext<'_>,
    out: vec3_t,
    distance: *mut f32,
    tryStraight: qboolean,
) -> qboolean {
    todo!("Port NPC_GetMoveDirectionAltRoute — parked: ai-context")
}

/// Raven `G_UcmdMoveForDir`.
///
/// Converts a direction vector into forward/right movement commands for a
/// usercmd. Normalizes the direction, computes dot products with the entity's
/// facing angles, and clamps movement values to [-127, 127]. NPCs cheat by
/// storing the precise direction in playerstate to avoid precision loss from
/// the ucmd conversion.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:324-370`
pub fn G_UcmdMoveForDir(
    self_: *mut gentity_t,
    cmd: *mut usercmd_t,
    dir: vec3_t,
) {
    unsafe {
        let mut forward = [0.0f32; 3];
        let mut right = [0.0f32; 3];

        // Get forward and right vectors from entity's current angles.
        AngleVectors((*self_).r.currentAngles, Some(&mut forward), Some(&mut right), None);

        // Zero out vertical component of movement direction.
        let mut move_dir = dir;
        move_dir[2] = 0.0;

        // Normalize the direction.
        VectorNormalize(&mut move_dir);

        // Store the movement direction in playerstate for NPC cheating
        // (preserves precision lost in ucmd conversion).
        (*((*self_).client as *mut gclient_t)).ps.moveDir = move_dir;

        // Compute dot products with forward and right vectors, scaled to [-127, 127].
        let mut fDot = (forward[0] * move_dir[0] + forward[1] * move_dir[1] + forward[2] * move_dir[2]) * 127.0f32;
        let mut rDot = (right[0] * move_dir[0] + right[1] * move_dir[1] + right[2] * move_dir[2]) * 127.0f32;

        // Clamp values to [-127, 127] to avoid overflow in signed byte.
        // DotProduct is not guaranteed to return [-1, 1] due to floating-point errors.
        if fDot > 127.0f32 {
            fDot = 127.0f32;
        }
        if fDot < -127.0f32 {
            fDot = -127.0f32;
        }
        if rDot > 127.0f32 {
            rDot = 127.0f32;
        }
        if rDot < -127.0f32 {
            rDot = -127.0f32;
        }

        // Store in usercmd as signed bytes.
        (*cmd).forwardmove = fDot.floor() as c_schar;
        (*cmd).rightmove = rDot.floor() as c_schar;
    }
}

/// Raven `NPC_MoveToGoal`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:382-467`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`NPCInfo`/`ucmd`
// globals set by the AI think loop; calls movement functions that read these;
// no channel to reach them from this context-free faithful signature.
pub fn NPC_MoveToGoal(
    ctx: GameContext<'_>,
    tryStraight: qboolean,
) -> qboolean {
    todo!("Port NPC_MoveToGoal — parked: ai-context")
}

/// Raven `NPC_SlideMoveToGoal`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:476-488`
// PORT-ESCALATION(ai-context): reads/writes ambient `NPC`/`NPCInfo` globals;
// calls NPC_MoveToGoal which also needs ai-context; no channel to reach them
// from this context-free faithful signature.
pub fn NPC_SlideMoveToGoal(ctx: GameContext<'_>) -> qboolean {
    todo!("Port NPC_SlideMoveToGoal — parked: ai-context")
}

/// Raven `NPC_ApplyRoff`.
///
/// Source: `oracle/oracle/codemp/game/NPC_move.c:497-505`
// PORT-ESCALATION(ai-context): reads ambient `NPC` global and calls
// `trap_LinkEntity` (needs Engine/GameContext); no channel to reach them from
// this context-free faithful signature.
pub fn NPC_ApplyRoff(ctx: GameContext<'_>) {
    todo!("Port NPC_ApplyRoff — parked: ai-context")
}
