//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_AI_Sentry.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `NPC_Sentry_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:37-57`
pub fn NPC_Sentry_Precache() {
    todo!("Port NPC_Sentry_Precache — oracle/oracle/codemp/game/NPC_AI_Sentry.c:37")
}

/// Raven `sentry_use`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:64-72`
pub fn sentry_use(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    todo!("Port sentry_use — oracle/oracle/codemp/game/NPC_AI_Sentry.c:64")
}

/// Raven `NPC_Sentry_Pain`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:79-105`
pub fn NPC_Sentry_Pain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    todo!("Port NPC_Sentry_Pain — oracle/oracle/codemp/game/NPC_AI_Sentry.c:79")
}

/// Raven `Sentry_Fire`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:112-203`
pub fn Sentry_Fire() {
    todo!("Port Sentry_Fire — oracle/oracle/codemp/game/NPC_AI_Sentry.c:112")
}

/// Raven `Sentry_MaintainHeight`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:210-304`
pub fn Sentry_MaintainHeight() {
    todo!("Port Sentry_MaintainHeight — oracle/oracle/codemp/game/NPC_AI_Sentry.c:210")
}

/// Raven `Sentry_Idle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:311-331`
pub fn Sentry_Idle() {
    todo!("Port Sentry_Idle — oracle/oracle/codemp/game/NPC_AI_Sentry.c:311")
}

/// Raven `Sentry_Strafe`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:338-365`
pub fn Sentry_Strafe() {
    todo!("Port Sentry_Strafe — oracle/oracle/codemp/game/NPC_AI_Sentry.c:338")
}

/// Raven `Sentry_Hunt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:372-411`
pub fn Sentry_Hunt(
    visible: qboolean,
    advance: qboolean,
) {
    todo!("Port Sentry_Hunt — oracle/oracle/codemp/game/NPC_AI_Sentry.c:372")
}

/// Raven `Sentry_RangedAttack`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:418-448`
pub fn Sentry_RangedAttack(
    visible: qboolean,
    advance: qboolean,
) {
    todo!("Port Sentry_RangedAttack — oracle/oracle/codemp/game/NPC_AI_Sentry.c:418")
}

/// Raven `Sentry_AttackDecision`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:455-510`
pub fn Sentry_AttackDecision() {
    todo!("Port Sentry_AttackDecision — oracle/oracle/codemp/game/NPC_AI_Sentry.c:455")
}

/// Raven `NPC_Sentry_Patrol`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:519-550`
pub fn NPC_Sentry_Patrol() {
    todo!("Port NPC_Sentry_Patrol — oracle/oracle/codemp/game/NPC_AI_Sentry.c:519")
}

/// Raven `NPC_BSSentry_Default`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Sentry.c:557-577`
pub fn NPC_BSSentry_Default() {
    todo!("Port NPC_BSSentry_Default — oracle/oracle/codemp/game/NPC_AI_Sentry.c:557")
}
