// PORT-COMPLETE: NPC_AI_Droid.c 14/14
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_AI_Droid.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unported
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

/// Local state enums.
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:10-17`
const LSTATE_NONE: c_int = 0;
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:12`
const LSTATE_BACKINGUP: c_int = 1;
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:13`
const LSTATE_SPINNING: c_int = 2;
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:14`
const LSTATE_PAIN: c_int = 3;
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:15`
const LSTATE_DROP: c_int = 4;

/// Surface render status flag: turn off.
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:84`
const TURN_OFF: c_int = 0x00000100;

/// Raven `R2D2_PartsMove`.
///
/// Raven: Front 'eye' lense animation.
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:24-46`
pub fn R2D2_PartsMove() {
    unsafe {
        // SAFETY: NPC pointer accessed through game context (global AI state).
        if TIMER_Done(NPC, b"eyeDelay\0".as_ptr() as *const c_char) != 0 {
            (*NPC).pos1[1] = AngleNormalize360((*NPC).pos1[1]);

            (*NPC).pos1[0] += Q_irand(-20, 20);  // Roll
            (*NPC).pos1[1] = Q_irand(-20, 20) as f32;
            (*NPC).pos1[2] = Q_irand(-20, 20) as f32;

            NPC_SetBoneAngles(NPC, b"f_eye\0".as_mut_ptr() as *mut c_char, (*NPC).pos1);

            TIMER_Set(NPC, b"eyeDelay\0".as_ptr() as *const c_char, Q_irand(100, 1000));
        }
    }
}

/// Raven `Droid_Idle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:53-58`
pub fn Droid_Idle() {
    // Empty function — Raven code has only commented-out code
}

/// Raven `R2D2_TurnAnims`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:65-95`
pub fn R2D2_TurnAnims() {
    unsafe {
        // SAFETY: NPC, NPCInfo accessed through game context.
        let turndelta = AngleDelta((*NPC).r.currentAngles[crate::prelude::YAW as usize], (*NPCInfo).desiredYaw);

        if (turndelta.abs() > 20.0)
            && ((*(*NPC).client).NPC_class == crate::prelude::CLASS_R2D2
                || (*(*NPC).client).NPC_class == crate::prelude::CLASS_R5D2)
        {
            let anim = (*(*NPC).client).ps.legsAnim;
            if turndelta < 0.0 {
                if anim != crate::prelude::BOTH_TURN_LEFT1 {
                    NPC_SetAnim(
                        NPC,
                        crate::prelude::SETANIM_BOTH,
                        crate::prelude::BOTH_TURN_LEFT1,
                        crate::prelude::SETANIM_FLAG_OVERRIDE | crate::prelude::SETANIM_FLAG_HOLD,
                    );
                }
            } else {
                if anim != crate::prelude::BOTH_TURN_RIGHT1 {
                    NPC_SetAnim(
                        NPC,
                        crate::prelude::SETANIM_BOTH,
                        crate::prelude::BOTH_TURN_RIGHT1,
                        crate::prelude::SETANIM_FLAG_OVERRIDE | crate::prelude::SETANIM_FLAG_HOLD,
                    );
                }
            }
        } else {
            NPC_SetAnim(
                NPC,
                crate::prelude::SETANIM_BOTH,
                crate::prelude::BOTH_RUN1,
                crate::prelude::SETANIM_FLAG_OVERRIDE | crate::prelude::SETANIM_FLAG_HOLD,
            );
        }
    }
}

/// Raven `Droid_Patrol`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:102-168`
pub fn Droid_Patrol() {
    unsafe {
        // SAFETY: NPC, NPCInfo, level, ucmd accessed through game context.
        (*NPC).pos1[1] = AngleNormalize360((*NPC).pos1[1]);

        if !(*NPC).client.is_null()
            && (*(*NPC).client).NPC_class != crate::prelude::CLASS_GONK
        {
            if (*(*NPC).client).NPC_class != crate::prelude::CLASS_R5D2 {
                R2D2_PartsMove();  // Get his eye moving.
            }
            R2D2_TurnAnims();
        }

        // If we have somewhere to go, then do that
        if !UpdateGoal().is_null() {
            ucmd.buttons |= crate::prelude::BUTTON_WALKING;
            NPC_MoveToGoal(qtrue);

            if !(*NPC).client.is_null()
                && (*(*NPC).client).NPC_class == crate::prelude::CLASS_MOUSE
            {
                (*NPCInfo).desiredYaw += ((*level).time * 0.5).sin() * 25.0;  // Weaves side to side

                if TIMER_Done(NPC, b"patrolNoise\0".as_ptr() as *const c_char) != 0 {
                    G_SoundOnEnt(
                        NPC,
                        crate::prelude::CHAN_AUTO,
                        va(
                            b"sound/chars/mouse/misc/mousego%d.wav\0".as_ptr() as *const c_char,
                            Q_irand(1, 3),
                        ),
                    );
                    TIMER_Set(NPC, b"patrolNoise\0".as_ptr() as *const c_char, Q_irand(2000, 4000));
                }
            } else if !(*NPC).client.is_null()
                && (*(*NPC).client).NPC_class == crate::prelude::CLASS_R2D2
            {
                if TIMER_Done(NPC, b"patrolNoise\0".as_ptr() as *const c_char) != 0 {
                    G_SoundOnEnt(
                        NPC,
                        crate::prelude::CHAN_AUTO,
                        va(
                            b"sound/chars/r2d2/misc/r2d2talk0%d.wav\0".as_ptr() as *const c_char,
                            Q_irand(1, 3),
                        ),
                    );
                    TIMER_Set(NPC, b"patrolNoise\0".as_ptr() as *const c_char, Q_irand(2000, 4000));
                }
            } else if !(*NPC).client.is_null()
                && (*(*NPC).client).NPC_class == crate::prelude::CLASS_R5D2
            {
                if TIMER_Done(NPC, b"patrolNoise\0".as_ptr() as *const c_char) != 0 {
                    G_SoundOnEnt(
                        NPC,
                        crate::prelude::CHAN_AUTO,
                        va(
                            b"sound/chars/r5d2/misc/r5talk%d.wav\0".as_ptr() as *const c_char,
                            Q_irand(1, 4),
                        ),
                    );
                    TIMER_Set(NPC, b"patrolNoise\0".as_ptr() as *const c_char, Q_irand(2000, 4000));
                }
            }
            if !(*NPC).client.is_null()
                && (*(*NPC).client).NPC_class == crate::prelude::CLASS_GONK
            {
                if TIMER_Done(NPC, b"patrolNoise\0".as_ptr() as *const c_char) != 0 {
                    G_SoundOnEnt(
                        NPC,
                        crate::prelude::CHAN_AUTO,
                        va(
                            b"sound/chars/gonk/misc/gonktalk%d.wav\0".as_ptr() as *const c_char,
                            Q_irand(1, 2),
                        ),
                    );
                    TIMER_Set(NPC, b"patrolNoise\0".as_ptr() as *const c_char, Q_irand(2000, 4000));
                }
            }
        }

        NPC_UpdateAngles(qtrue, qtrue);
    }
}

/// Raven `Droid_Run`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:175-200`
pub fn Droid_Run() {
    unsafe {
        // SAFETY: NPC, NPCInfo, level, ucmd accessed through game context.
        R2D2_PartsMove();

        if (*NPCInfo).localState == LSTATE_BACKINGUP {
            ucmd.forwardmove = -127;
            (*NPCInfo).desiredYaw += 5.0;

            (*NPCInfo).localState = LSTATE_NONE;  // So he doesn't constantly backup.
        } else {
            ucmd.forwardmove = 64;
            // If we have somewhere to go, then do that
            if !UpdateGoal().is_null() {
                if NPC_MoveToGoal(qfalse) != 0 {
                    (*NPCInfo).desiredYaw += ((*level).time * 0.5).sin() * 5.0;  // Weaves side to side
                }
            }
        }

        NPC_UpdateAngles(qtrue, qtrue);
    }
}

/// Raven `Droid_Spin`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:207-266`
pub fn Droid_Spin() {
    unsafe {
        // SAFETY: NPC, NPCInfo accessed through game context; trap called through seam.
        let mut dir: vec3_t = [0.0, 0.0, 1.0];

        R2D2_TurnAnims();

        // Head is gone, spin and spark
        if (*(*NPC).client).NPC_class == crate::prelude::CLASS_R5D2
            || (*(*NPC).client).NPC_class == crate::prelude::CLASS_R2D2
        {
            // No head?
            if trap::G2API_GetSurfaceRenderStatus(&mut (*NPC).ghoul2, 0, b"head\0".as_ptr() as *const c_char) > 0 {
                if TIMER_Done(NPC, b"smoke\0".as_ptr() as *const c_char) != 0
                    && TIMER_Done(NPC, b"droidsmoketotal\0".as_ptr() as *const c_char) == 0
                {
                    TIMER_Set(NPC, b"smoke\0".as_ptr() as *const c_char, 100);
                    G_PlayEffectID(
                        G_EffectIndex(b"volumetric/droid_smoke\0".as_ptr() as *const c_char),
                        (*NPC).r.currentOrigin,
                        dir,
                    );
                }

                if TIMER_Done(NPC, b"droidspark\0".as_ptr() as *const c_char) != 0 {
                    TIMER_Set(NPC, b"droidspark\0".as_ptr() as *const c_char, Q_irand(100, 500));
                    G_PlayEffectID(
                        G_EffectIndex(b"sparks/spark\0".as_ptr() as *const c_char),
                        (*NPC).r.currentOrigin,
                        dir,
                    );
                }

                ucmd.forwardmove = Q_irand(-64, 64);

                if TIMER_Done(NPC, b"roam\0".as_ptr() as *const c_char) != 0 {
                    TIMER_Set(NPC, b"roam\0".as_ptr() as *const c_char, Q_irand(250, 1000));
                    (*NPCInfo).desiredYaw = Q_irand(0, 360) as f32;  // Go in random directions
                }
            } else {
                if TIMER_Done(NPC, b"roam\0".as_ptr() as *const c_char) != 0 {
                    (*NPCInfo).localState = LSTATE_NONE;
                } else {
                    (*NPCInfo).desiredYaw = AngleNormalize360((*NPCInfo).desiredYaw + 40.0);  // Spin around
                }
            }
        } else {
            if TIMER_Done(NPC, b"roam\0".as_ptr() as *const c_char) != 0 {
                (*NPCInfo).localState = LSTATE_NONE;
            } else {
                (*NPCInfo).desiredYaw = AngleNormalize360((*NPCInfo).desiredYaw + 40.0);  // Spin around
            }
        }

        NPC_UpdateAngles(qtrue, qtrue);
    }
}

/// Raven `NPC_Droid_Pain`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:273-434`
pub fn NPC_Droid_Pain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    unsafe {
        // SAFETY: pointers from caller; level, gPainMOD, vec3_origin accessed via game context.
        let other = attacker;
        let anim: c_int;
        let mod_ = gPainMOD;
        let pain_chance: f32;

        // Copy last path angles to entity angles
        let npc_info = (*self_).NPC;
        let src_angles = (*npc_info).lastPathAngles;
        (*self_).s.angles[0] = src_angles[0];
        (*self_).s.angles[1] = src_angles[1];
        (*self_).s.angles[2] = src_angles[2];

        if (*(*self_).client).NPC_class == crate::prelude::CLASS_R5D2 {
            pain_chance = NPC_GetPainChance(self_, damage);

            // Put it in pain
            if mod_ == crate::prelude::MOD_DEMP2
                || mod_ == crate::prelude::MOD_DEMP2_ALT
                || (rand() as f32 / 2147483647.0) < pain_chance
            {
                // Health is between 0-30 or was hit by a DEMP2 so pop his head
                if (*self_).s.m_iVehicleNum == 0
                    && ((*self_).health < 30
                        || mod_ == crate::prelude::MOD_DEMP2
                        || mod_ == crate::prelude::MOD_DEMP2_ALT)
                {
                    if ((*self_).spawnflags & 2) == 0 {
                        // Doesn't have to ALWAYSDIE
                        if (*npc_info).localState != LSTATE_SPINNING
                            && trap::G2API_GetSurfaceRenderStatus(
                                &mut (*self_).ghoul2,
                                0,
                                b"head\0".as_ptr() as *const c_char,
                            ) <= 0
                        {
                            NPC_SetSurfaceOnOff(self_, b"head\0".as_ptr() as *const c_char, TURN_OFF);

                            if (*(*self_).client).ps.m_iVehicleNum != 0 {
                                let mut up: vec3_t = [0.0; 3];
                                AngleVectors((*self_).r.currentAngles, [0.0; 3], [0.0; 3], up);
                                G_PlayEffectID(
                                    G_EffectIndex(
                                        b"chunks/r5d2head_veh\0".as_ptr() as *const c_char,
                                    ),
                                    (*self_).r.currentOrigin,
                                    up,
                                );
                            } else {
                                G_PlayEffectID(
                                    G_EffectIndex(b"small_chunks\0".as_ptr() as *const c_char),
                                    (*self_).r.currentOrigin,
                                    vec3_origin,
                                );
                                G_PlayEffectID(
                                    G_EffectIndex(b"chunks/r5d2head\0".as_ptr() as *const c_char),
                                    (*self_).r.currentOrigin,
                                    vec3_origin,
                                );
                            }

                            (*(*self_).client).ps.electrifyTime = (*level).time + 3000;

                            TIMER_Set(self_, b"droidsmoketotal\0".as_ptr() as *const c_char, 5000);
                            TIMER_Set(self_, b"droidspark\0".as_ptr() as *const c_char, 100);
                            (*npc_info).localState = LSTATE_SPINNING;
                        }
                    }
                } else {
                    // Just give him normal pain for a little while
                    let legsAnim = (*(*self_).client).ps.legsAnim;

                    if legsAnim == crate::prelude::BOTH_STAND2 {
                        // On two legs?
                        anim = crate::prelude::BOTH_PAIN1;
                    } else {
                        // On three legs
                        anim = crate::prelude::BOTH_PAIN2;
                    }

                    NPC_SetAnim(
                        self_,
                        crate::prelude::SETANIM_BOTH,
                        anim,
                        crate::prelude::SETANIM_FLAG_OVERRIDE | crate::prelude::SETANIM_FLAG_HOLD,
                    );

                    // Spin around in pain
                    (*npc_info).localState = LSTATE_SPINNING;
                    TIMER_Set(self_, b"roam\0".as_ptr() as *const c_char, Q_irand(1000, 2000));
                }
            }
        } else if (*(*self_).client).NPC_class == crate::prelude::CLASS_MOUSE {
            if mod_ == crate::prelude::MOD_DEMP2 || mod_ == crate::prelude::MOD_DEMP2_ALT {
                (*npc_info).localState = LSTATE_SPINNING;
                (*(*self_).client).ps.electrifyTime = (*level).time + 3000;
            } else {
                (*npc_info).localState = LSTATE_BACKINGUP;
            }

            (*npc_info).scriptFlags &= !crate::prelude::SCF_LOOK_FOR_ENEMIES;
        } else if (*(*self_).client).NPC_class == crate::prelude::CLASS_R2D2 {
            pain_chance = NPC_GetPainChance(self_, damage);

            if mod_ == crate::prelude::MOD_DEMP2
                || mod_ == crate::prelude::MOD_DEMP2_ALT
                || (rand() as f32 / 2147483647.0) < pain_chance
            {
                // Health is between 0-30 or was hit by a DEMP2 so pop his head
                if (*self_).s.m_iVehicleNum == 0
                    && ((*self_).health < 30
                        || mod_ == crate::prelude::MOD_DEMP2
                        || mod_ == crate::prelude::MOD_DEMP2_ALT)
                {
                    if ((*self_).spawnflags & 2) == 0 {
                        // Doesn't have to ALWAYSDIE
                        if (*npc_info).localState != LSTATE_SPINNING
                            && trap::G2API_GetSurfaceRenderStatus(
                                &mut (*self_).ghoul2,
                                0,
                                b"head\0".as_ptr() as *const c_char,
                            ) <= 0
                        {
                            NPC_SetSurfaceOnOff(self_, b"head\0".as_ptr() as *const c_char, TURN_OFF);

                            if (*(*self_).client).ps.m_iVehicleNum != 0 {
                                let mut up: vec3_t = [0.0; 3];
                                AngleVectors((*self_).r.currentAngles, [0.0; 3], [0.0; 3], up);
                                G_PlayEffectID(
                                    G_EffectIndex(
                                        b"chunks/r2d2head_veh\0".as_ptr() as *const c_char,
                                    ),
                                    (*self_).r.currentOrigin,
                                    up,
                                );
                            } else {
                                G_PlayEffectID(
                                    G_EffectIndex(b"small_chunks\0".as_ptr() as *const c_char),
                                    (*self_).r.currentOrigin,
                                    vec3_origin,
                                );
                                G_PlayEffectID(
                                    G_EffectIndex(b"chunks/r2d2head\0".as_ptr() as *const c_char),
                                    (*self_).r.currentOrigin,
                                    vec3_origin,
                                );
                            }

                            (*(*self_).client).ps.electrifyTime = (*level).time + 3000;

                            TIMER_Set(self_, b"droidsmoketotal\0".as_ptr() as *const c_char, 5000);
                            TIMER_Set(self_, b"droidspark\0".as_ptr() as *const c_char, 100);
                            (*npc_info).localState = LSTATE_SPINNING;
                        }
                    }
                } else {
                    // Just give him normal pain for a little while
                    let legsAnim = (*(*self_).client).ps.legsAnim;

                    if legsAnim == crate::prelude::BOTH_STAND2 {
                        // On two legs?
                        anim = crate::prelude::BOTH_PAIN1;
                    } else {
                        // On three legs
                        anim = crate::prelude::BOTH_PAIN2;
                    }

                    NPC_SetAnim(
                        self_,
                        crate::prelude::SETANIM_BOTH,
                        anim,
                        crate::prelude::SETANIM_FLAG_OVERRIDE | crate::prelude::SETANIM_FLAG_HOLD,
                    );

                    // Spin around in pain
                    (*npc_info).localState = LSTATE_SPINNING;
                    TIMER_Set(self_, b"roam\0".as_ptr() as *const c_char, Q_irand(1000, 2000));
                }
            }
        } else if (*(*self_).client).NPC_class == crate::prelude::CLASS_INTERROGATOR
            && (mod_ == crate::prelude::MOD_DEMP2 || mod_ == crate::prelude::MOD_DEMP2_ALT)
            && !other.is_null()
        {
            let mut dir: vec3_t = [0.0; 3];

            dir[0] = (*self_).r.currentOrigin[0] - (*other).r.currentOrigin[0];
            dir[1] = (*self_).r.currentOrigin[1] - (*other).r.currentOrigin[1];
            dir[2] = (*self_).r.currentOrigin[2] - (*other).r.currentOrigin[2];
            VectorNormalize(dir);

            (*(*self_).client).ps.velocity[0] += 550.0 * dir[0];
            (*(*self_).client).ps.velocity[1] += 550.0 * dir[1];
            (*(*self_).client).ps.velocity[2] += 550.0 * dir[2];
            (*(*self_).client).ps.velocity[2] -= 127.0;
        }

        NPC_Pain(self_, attacker, damage);
    }
}

/// Raven `Droid_Pain`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:442-448`
pub fn Droid_Pain() {
    unsafe {
        // SAFETY: NPC, NPCInfo accessed through game context.
        if TIMER_Done(NPC, b"droidpain\0".as_ptr() as *const c_char) != 0 {
            // He's done jumping around
            (*NPCInfo).localState = LSTATE_NONE;
        }
    }
}

/// Raven `NPC_Mouse_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:455-467`
pub fn NPC_Mouse_Precache() {
    unsafe {
        // SAFETY: va returns valid C string pointer.
        for i in 1..4 {
            G_SoundIndex(va(
                b"sound/chars/mouse/misc/mousego%d.wav\0".as_ptr() as *const c_char,
                i,
            ));
        }

        G_EffectIndex(b"env/small_explode\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/mouse/misc/death1\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/mouse/misc/mouse_lp\0".as_ptr() as *const c_char);
    }
}

/// Raven `NPC_R5D2_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:474-490`
pub fn NPC_R5D2_Precache() {
    unsafe {
        // SAFETY: va returns valid C string pointer.
        for i in 1..5 {
            G_SoundIndex(va(
                b"sound/chars/r5d2/misc/r5talk%d.wav\0".as_ptr() as *const c_char,
                i,
            ));
        }
        G_SoundIndex(b"sound/chars/mark2/misc/mark2_explo\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/r2d2/misc/r2_move_lp2.wav\0".as_ptr() as *const c_char);
        G_EffectIndex(b"env/med_explode\0".as_ptr() as *const c_char);
        G_EffectIndex(b"volumetric/droid_smoke\0".as_ptr() as *const c_char);
        G_EffectIndex(b"sparks/spark\0".as_ptr() as *const c_char);
        G_EffectIndex(b"chunks/r5d2head\0".as_ptr() as *const c_char);
        G_EffectIndex(b"chunks/r5d2head_veh\0".as_ptr() as *const c_char);
    }
}

/// Raven `NPC_R2D2_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:497-513`
pub fn NPC_R2D2_Precache() {
    unsafe {
        // SAFETY: va returns valid C string pointer.
        for i in 1..4 {
            G_SoundIndex(va(
                b"sound/chars/r2d2/misc/r2d2talk0%d.wav\0".as_ptr() as *const c_char,
                i,
            ));
        }
        G_SoundIndex(b"sound/chars/mark2/misc/mark2_explo\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/r2d2/misc/r2_move_lp.wav\0".as_ptr() as *const c_char);
        G_EffectIndex(b"env/med_explode\0".as_ptr() as *const c_char);
        G_EffectIndex(b"volumetric/droid_smoke\0".as_ptr() as *const c_char);
        G_EffectIndex(b"sparks/spark\0".as_ptr() as *const c_char);
        G_EffectIndex(b"chunks/r2d2head\0".as_ptr() as *const c_char);
        G_EffectIndex(b"chunks/r2d2head_veh\0".as_ptr() as *const c_char);
    }
}

/// Raven `NPC_Gonk_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:520-530`
pub fn NPC_Gonk_Precache() {
    unsafe {
        // SAFETY: string literals valid.
        G_SoundIndex(b"sound/chars/gonk/misc/gonktalk1.wav\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/gonk/misc/gonktalk2.wav\0".as_ptr() as *const c_char);

        G_SoundIndex(b"sound/chars/gonk/misc/death1.wav\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/gonk/misc/death2.wav\0".as_ptr() as *const c_char);
        G_SoundIndex(b"sound/chars/gonk/misc/death3.wav\0".as_ptr() as *const c_char);

        G_EffectIndex(b"env/med_explode\0".as_ptr() as *const c_char);
    }
}

/// Raven `NPC_Protocol_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:537-541`
pub fn NPC_Protocol_Precache() {
    unsafe {
        // SAFETY: string literals valid.
        G_SoundIndex(b"sound/chars/mark2/misc/mark2_explo\0".as_ptr() as *const c_char);
        G_EffectIndex(b"env/med_explode\0".as_ptr() as *const c_char);
    }
}

/// Raven `NPC_BSDroid_Default`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Droid.c:597-621`
pub fn NPC_BSDroid_Default() {
    unsafe {
        // SAFETY: NPC, NPCInfo, ucmd accessed through game context.
        if (*NPCInfo).localState == LSTATE_SPINNING {
            Droid_Spin();
        } else if (*NPCInfo).localState == LSTATE_PAIN {
            Droid_Pain();
        } else if (*NPCInfo).localState == LSTATE_DROP {
            NPC_UpdateAngles(qtrue, qtrue);
            ucmd.upmove = crandom() * 64.0;
        } else if ((*NPCInfo).scriptFlags & crate::prelude::SCF_LOOK_FOR_ENEMIES) != 0 {
            Droid_Patrol();
        } else {
            Droid_Run();
        }
    }
}
