// PORT-COMPLETE: NPC_spawn.c 5/85
//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_spawn.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;

// Unported types referenced in this file (need porting before this compiles):
// PAIN_FUNC, TOUCH_FUNC

/// Raven `b_local.h` sound-flag bits (`SFB_*`).
/// Source: `oracle/oracle/codemp/game/b_local.h:139-141`
const SFB_RIFLEMAN: c_int = 2;
const SFB_PHASER: c_int = 4;

// PORT-ESCALATION(packet-contract): this packet's manifest rows list callee
// names (in-module callees / bg_ callees / traps / globals) but never give the
// resolved Rust signature of any out-of-file symbol (no `## RESOLVED` /
// `prelude` section), unlike what the task brief promises. Nearly every
// function in this file (NPC_Begin, NPC_Spawn_Do, the ~60 SP_NPC_* spawn-field
// setters, vehicle/precache plumbing, Cmd_NPC_f, …) reaches `level`,
// `g_entities`, `G_Spawn`/`G_FreeEntity`, NPC.cfg parsing, ICARUS, vehicle
// vtables, and ~213 fn-pointer targets (ruling 2) whose concrete Rust
// shapes/signatures are not given here and this protocol forbids exploring
// the tree to find them. Parking those bodies rather than inventing
// signatures. Only the handful of functions below are fully self-contained
// (pure arithmetic / string compares / no external state) and are ported
// faithfully.

/// Raven `WP_SetSaberModel`.
///
/// Raven: rwwFIXMEFIXME: Do something here, need to let the client know.
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:90-94`
pub fn WP_SetSaberModel(
    client: *mut gclient_t,
    npcClass: class_t,
) -> c_int {
    1
}

/// Raven `NPC_PainFunc`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:103-189`
pub fn NPC_PainFunc(
    ent: *mut gentity_t,
) -> *mut c_void {
    //TODO: Port PAIN_FUNC (unported fn-ptr return; needs an EntPain-style
    // enum per ruling 2 before this can select among NPC_Jedi_Pain/
    // NPC_ST_Pain/NPC_Seeker_Pain/NPC_Remote_Pain/NPC_MineMonster_Pain/
    // NPC_Howler_Pain/NPC_Droid_Pain/NPC_Probe_Pain/NPC_Sentry_Pain/
    // NPC_Mark1_Pain/NPC_Mark2_Pain/NPC_ATST_Pain/NPC_GM_Pain/
    // NPC_Rancor_Pain/NPC_Wampa_Pain/NPC_Pain)
    // PORT-ESCALATION(fn-ptr-enum): no EntPain enum / resolved pain-fn
    // targets were provided in this packet — what enum type does
    // NPC_PainFunc return so callers (NPC_Begin) can assign ent->pain?
    todo!("Port NPC_PainFunc — oracle/oracle/codemp/game/NPC_spawn.c:103")
}

/// Raven `NPC_TouchFunc`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:199-206`
pub fn NPC_TouchFunc(
    ent: *mut gentity_t,
) -> *mut c_void {
    //TODO: Port TOUCH_FUNC (unported fn-ptr return)
    // PORT-ESCALATION(fn-ptr-enum): same as NPC_PainFunc — always returns
    // NPC_Touch here, but the enum/type this should return isn't resolved.
    todo!("Port NPC_TouchFunc — oracle/oracle/codemp/game/NPC_spawn.c:199")
}

/// Raven `NPC_SetMiscDefaultData`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:215-501`
pub fn NPC_SetMiscDefaultData(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): touches g_gametype global, ~10
    // in-module callees (Boba_Precache, Jedi_ClearTimers, WP_InitForcePowers,
    // …) and a trap (trap_G2API_SetSurfaceOnOff), none resolved in packet.
    todo!("Port NPC_SetMiscDefaultData — oracle/oracle/codemp/game/NPC_spawn.c:215")
}

/// Raven `NPC_WeaponsForTeam`.
///
/// Raven: not sure how to handle this, should I pass in class instead of team
/// and go from there? - dmv
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:509-749`
pub fn NPC_WeaponsForTeam(
    team: team_t,
    spawnflags: c_int,
    NPC_type: *const c_char,
) -> c_int {
    // Faithful transcription of the C string-compare cascade. Q_stricmp /
    // Q_strncmp are pure string helpers (bg-shared); NPC_type is a NUL
    // terminated C string handed to us by the (unported) caller — safe to
    // read here since we only borrow it for comparisons.
    let name = unsafe {
        if NPC_type.is_null() {
            std::borrow::Cow::Borrowed("")
        } else {
            std::ffi::CStr::from_ptr(NPC_type).to_string_lossy()
        }
    };
    let name = name.as_ref();

    let stricmp = |a: &str, b: &str| a.eq_ignore_ascii_case(b);
    let strncmp = |a: &str, b: &str, n: usize| {
        let a_pre: String = a.chars().take(n).collect();
        let b_pre: String = b.chars().take(n).collect();
        a_pre.eq_ignore_ascii_case(&b_pre) && a.chars().count() >= n && b.chars().count() >= n
    };

    match team {
        NPCTEAM_ENEMY => {
            if stricmp(name, "tavion")
                || strncmp(name, "reborn", 6)
                || stricmp(name, "desann")
                || strncmp(name, "shadowtrooper", 13)
            {
                return 1 << WP_SABER;
            }
            if strncmp(name, "stofficer", 9) {
                return 1 << WP_FLECHETTE;
            }
            if stricmp(name, "stcommander") {
                return 1 << WP_REPEATER;
            }
            if stricmp(name, "swamptrooper") {
                return 1 << WP_FLECHETTE;
            }
            if stricmp(name, "swamptrooper2") {
                return 1 << WP_REPEATER;
            }
            if stricmp(name, "rockettrooper") {
                return 1 << WP_ROCKET_LAUNCHER;
            }
            if strncmp(name, "shadowtrooper", 13) {
                return 1 << WP_SABER;
            }
            if stricmp(name, "imperial") {
                return 1 << WP_BLASTER;
            }
            if strncmp(name, "impworker", 9) {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "stormpilot") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "galak") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "galak_mech") {
                return 1 << WP_REPEATER;
            }
            if strncmp(name, "ugnaught", 8) {
                return WP_NONE;
            }
            if stricmp(name, "granshooter") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "granboxer") {
                return 1 << WP_STUN_BATON;
            }
            if strncmp(name, "gran", 4) {
                return (1 << WP_THERMAL) | (1 << WP_STUN_BATON);
            }
            if stricmp(name, "rodian") {
                return 1 << WP_DISRUPTOR;
            }
            if stricmp(name, "rodian2") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "interrogator") || stricmp(name, "sentry") || strncmp(name, "protocol", 8) {
                return WP_NONE;
            }
            if strncmp(name, "weequay", 7) {
                return 1 << WP_BOWCASTER;
            }
            if stricmp(name, "impofficer") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "impcommander") {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "probe") || stricmp(name, "seeker") {
                return 0;
            }
            if stricmp(name, "remote") {
                return 0;
            }
            if stricmp(name, "trandoshan") {
                return 1 << WP_REPEATER;
            }
            if stricmp(name, "atst") {
                return 0;
            }
            if stricmp(name, "mark1") {
                return 0;
            }
            if stricmp(name, "mark2") {
                return 0;
            }
            if stricmp(name, "minemonster") {
                return 1 << WP_STUN_BATON;
            }
            if stricmp(name, "howler") {
                return 1 << WP_STUN_BATON;
            }
            // Stormtroopers, etc.
            1 << WP_BLASTER
        }
        NPCTEAM_PLAYER => {
            if spawnflags & SFB_RIFLEMAN != 0 {
                return 1 << WP_REPEATER;
            }
            if spawnflags & SFB_PHASER != 0 {
                return 1 << WP_BLASTER;
            }
            if strncmp(name, "jedi", 4) || stricmp(name, "luke") {
                return 1 << WP_SABER;
            }
            if strncmp(name, "prisoner", 8) {
                return WP_NONE;
            }
            if strncmp(name, "bespincop", 9) {
                return 1 << WP_BLASTER;
            }
            if stricmp(name, "MonMothma") {
                return WP_NONE;
            }
            // rebel
            1 << WP_BLASTER
        }
        NPCTEAM_NEUTRAL => {
            if stricmp(name, "mark1") {
                return WP_NONE;
            }
            if stricmp(name, "mark2") {
                return WP_NONE;
            }
            if strncmp(name, "ugnaught", 8) {
                return WP_NONE;
            }
            if stricmp(name, "bartender") {
                return WP_NONE;
            }
            if stricmp(name, "morgankatarn") {
                return WP_NONE;
            }
            WP_NONE
        }
        _ => WP_NONE,
    }
}

/// Raven `NPC_SetWeapons`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:759-797`
pub fn NPC_SetWeapons(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs `weaponData` global (ammoIndex
    // lookup) and direct field writes on gentity_t/gclient_t not resolved
    // here.
    todo!("Port NPC_SetWeapons — oracle/oracle/codemp/game/NPC_spawn.c:759")
}

/// Raven `NPC_SpawnEffect`.
///
/// Raven: NOTE: Make sure any effects called here have their models, tga's
/// and sounds precached in CG_RegisterNPCEffects in cg_player.cpp.
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:808-810`
pub fn NPC_SpawnEffect(
    ent: *mut gentity_t,
) {
    // Empty body in the oracle (effect hook, never filled in).
}

/// Raven `NPC_SetFX_SpawnStates`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:817-823`
pub fn NPC_SetFX_SpawnStates(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs `g_gravity` cvar float and a
    // field write on ent->client->ps.gravity / ent->NPC->aiFlags, neither
    // resolved here.
    todo!("Port NPC_SetFX_SpawnStates — oracle/oracle/codemp/game/NPC_spawn.c:817")
}

/// Raven `NPC_SpotWouldTelefrag`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:831-859`
pub fn NPC_SpotWouldTelefrag(
    npc: *mut gentity_t,
) -> qboolean {
    // PORT-ESCALATION(packet-contract): needs trap_EntitiesInBox and the
    // g_entities global array, neither resolved here.
    todo!("Port NPC_SpotWouldTelefrag — oracle/oracle/codemp/game/NPC_spawn.c:831")
}

/// Raven `NPC_Begin`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:862-1274`
pub fn NPC_Begin(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): 413-LOC function threading `level`,
    // `g_entities`, ~25 in-module callees, 3 traps, and fn-pointer field
    // writes (ruling 2) — none of the target signatures/enum shapes are
    // resolved in this packet.
    todo!("Port NPC_Begin — oracle/oracle/codemp/game/NPC_spawn.c:862")
}

/// Raven `New_NPC_t`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1278-1297`
pub fn New_NPC_t(
    entNum: c_int,
) -> *mut gNPC_t {
    // PORT-ESCALATION(packet-contract): needs BG_Alloc and the `gNPCPtrs`
    // global array (§B1 GameWorld field), neither resolved here.
    todo!("Port New_NPC_t — oracle/oracle/codemp/game/NPC_spawn.c:1278")
}

/// Raven `NPC_DefaultScriptFlags`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1356-1364`
pub fn NPC_DefaultScriptFlags(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs field access into
    // gentity_t::NPC (gNPC_t*) whose Rust layout/accessor isn't resolved
    // here (this file's own skeleton header lists gNPC_t as resolved but the
    // scriptFlags bitfield name/type on it is not confirmed in this packet).
    todo!("Port NPC_DefaultScriptFlags — oracle/oracle/codemp/game/NPC_spawn.c:1356")
}

/// Raven `NPC_Spawn_Do`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1377-1763`
pub fn NPC_Spawn_Do(
    ent: *mut gentity_t,
) -> *mut gentity_t {
    // PORT-ESCALATION(packet-contract): 387-LOC function creating new
    // entities (G_Spawn), vehicle-type dispatch (ruling 7: enum-over-vehicle-
    // type), NPC.cfg parsing (NPC_ParseParms) — none resolved in this
    // packet.
    todo!("Port NPC_Spawn_Do — oracle/oracle/codemp/game/NPC_spawn.c:1377")
}

/// Raven `NPC_Spawn_Go`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1765-1768`
pub fn NPC_Spawn_Go(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): trivial body (calls NPC_Spawn_Do)
    // but NPC_Spawn_Do itself is parked above.
    todo!("Port NPC_Spawn_Go — oracle/oracle/codemp/game/NPC_spawn.c:1765")
}

/// Raven `NPC_ShySpawn`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1814-1831`
pub fn NPC_ShySpawn(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs level/g_entities globals and
    // InFOV/NPC_ClearLOS2 helpers, not resolved here.
    todo!("Port NPC_ShySpawn — oracle/oracle/codemp/game/NPC_spawn.c:1814")
}

/// Raven `NPC_Spawn`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1839-1873`
pub fn NPC_Spawn(
    ent: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on NPC_Spawn_Do/NPC_ShySpawn
    // (both parked) and fn-pointer field writes not resolved here.
    todo!("Port NPC_Spawn — oracle/oracle/codemp/game/NPC_spawn.c:1839")
}

/// Raven `NPC_PrecacheType`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1961-1971`
pub fn NPC_PrecacheType(
    NPC_type: *mut c_char,
) {
    // PORT-ESCALATION(packet-contract): needs G_Spawn/G_FreeEntity/
    // NPC_Precache, not resolved here.
    todo!("Port NPC_PrecacheType — oracle/oracle/codemp/game/NPC_spawn.c:1961")
}

/// Raven `SP_NPC_spawner`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:1973-2068`
pub fn SP_NPC_spawner(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs g_allowNPC/level globals,
    // G_SpawnInt, NPC_Precache/NPC_PrecacheAnimationCFG, and fn-pointer field
    // writes, not resolved here.
    todo!("Port SP_NPC_spawner — oracle/oracle/codemp/game/NPC_spawn.c:1973")
}

/// Raven `NPC_VehiclePrecache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2103-2173`
pub fn NPC_VehiclePrecache(
    spawner: *mut gentity_t,
) -> qboolean {
    // PORT-ESCALATION(packet-contract): needs G_ModelIndex, several G2API
    // traps, BG_ParseAnimationFile/BG_VehicleGetIndex, `g_vehicleInfo`
    // global — none resolved here.
    todo!("Port NPC_VehiclePrecache — oracle/oracle/codemp/game/NPC_spawn.c:2103")
}

/// Raven `NPC_VehicleSpawnUse`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2175-2186`
pub fn NPC_VehicleSpawnUse(
    self_: *mut gentity_t,
    other: *mut gentity_t,
    activator: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs G_VehicleSpawn + level global +
    // fn-pointer field write, not resolved here.
    todo!("Port NPC_VehicleSpawnUse — oracle/oracle/codemp/game/NPC_spawn.c:2175")
}

/// Raven `SP_NPC_Vehicle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2188-2253`
pub fn SP_NPC_Vehicle(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs G_SpawnFloat/G_SpawnInt/
    // G_VehicleSpawn/NPC_VehiclePrecache (itself parked), not resolved here.
    todo!("Port SP_NPC_Vehicle — oracle/oracle/codemp/game/NPC_spawn.c:2188")
}

/// Raven `SP_NPC_Kyle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2338-2345`
pub fn SP_NPC_Kyle(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs SP_NPC_spawner (parked) plus
    // field writes on gentity_t::NPC_type not resolved here.
    todo!("Port SP_NPC_Kyle — oracle/oracle/codemp/game/NPC_spawn.c:2338")
}

/// Raven `SP_NPC_Lando`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2354-2359`
pub fn SP_NPC_Lando(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Lando — oracle/oracle/codemp/game/NPC_spawn.c:2354")
}

/// Raven `SP_NPC_Jan`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2368-2373`
pub fn SP_NPC_Jan(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Jan — oracle/oracle/codemp/game/NPC_spawn.c:2368")
}

/// Raven `SP_NPC_Luke`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2382-2389`
pub fn SP_NPC_Luke(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Luke — oracle/oracle/codemp/game/NPC_spawn.c:2382")
}

/// Raven `SP_NPC_MonMothma`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2398-2403`
pub fn SP_NPC_MonMothma(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_MonMothma — oracle/oracle/codemp/game/NPC_spawn.c:2398")
}

/// Raven `SP_NPC_Tavion`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2412-2419`
pub fn SP_NPC_Tavion(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Tavion — oracle/oracle/codemp/game/NPC_spawn.c:2412")
}

/// Raven `SP_NPC_Tavion_New`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2432-2448`
pub fn SP_NPC_Tavion_New(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Tavion_New — oracle/oracle/codemp/game/NPC_spawn.c:2432")
}

/// Raven `SP_NPC_Alora`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2460-2472`
pub fn SP_NPC_Alora(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Alora — oracle/oracle/codemp/game/NPC_spawn.c:2460")
}

/// Raven `SP_NPC_Reborn_New`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2487-2524`
pub fn SP_NPC_Reborn_New(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Reborn_New — oracle/oracle/codemp/game/NPC_spawn.c:2487")
}

/// Raven `SP_NPC_Cultist_Saber`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2542-2593`
pub fn SP_NPC_Cultist_Saber(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Cultist_Saber — oracle/oracle/codemp/game/NPC_spawn.c:2542")
}

/// Raven `SP_NPC_Cultist_Saber_Powers`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2611-2662`
pub fn SP_NPC_Cultist_Saber_Powers(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Cultist_Saber_Powers — oracle/oracle/codemp/game/NPC_spawn.c:2611")
}

/// Raven `SP_NPC_Cultist`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2679-2725`
pub fn SP_NPC_Cultist(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Cultist — oracle/oracle/codemp/game/NPC_spawn.c:2679")
}

/// Raven `SP_NPC_Cultist_Commando`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2737-2744`
pub fn SP_NPC_Cultist_Commando(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Cultist_Commando — oracle/oracle/codemp/game/NPC_spawn.c:2737")
}

/// Raven `SP_NPC_Cultist_Destroyer`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2755-2759`
pub fn SP_NPC_Cultist_Destroyer(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Cultist_Destroyer — oracle/oracle/codemp/game/NPC_spawn.c:2755")
}

/// Raven `SP_NPC_Reelo`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2768-2773`
pub fn SP_NPC_Reelo(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Reelo — oracle/oracle/codemp/game/NPC_spawn.c:2768")
}

/// Raven `SP_NPC_Galak`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2784-2797`
pub fn SP_NPC_Galak(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Galak — oracle/oracle/codemp/game/NPC_spawn.c:2784")
}

/// Raven `SP_NPC_Desann`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2806-2813`
pub fn SP_NPC_Desann(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Desann — oracle/oracle/codemp/game/NPC_spawn.c:2806")
}

/// Raven `SP_NPC_Bartender`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2822-2827`
pub fn SP_NPC_Bartender(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Bartender — oracle/oracle/codemp/game/NPC_spawn.c:2822")
}

/// Raven `SP_NPC_MorganKatarn`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2836-2841`
pub fn SP_NPC_MorganKatarn(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_MorganKatarn — oracle/oracle/codemp/game/NPC_spawn.c:2836")
}

/// Raven `SP_NPC_Jedi`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2857-2887`
pub fn SP_NPC_Jedi(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Jedi — oracle/oracle/codemp/game/NPC_spawn.c:2857")
}

/// Raven `SP_NPC_Prisoner`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2896-2911`
pub fn SP_NPC_Prisoner(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Prisoner — oracle/oracle/codemp/game/NPC_spawn.c:2896")
}

/// Raven `SP_NPC_Rebel`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2920-2935`
pub fn SP_NPC_Rebel(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Rebel — oracle/oracle/codemp/game/NPC_spawn.c:2920")
}

/// Raven `SP_NPC_Stormtrooper`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2955-2986`
pub fn SP_NPC_Stormtrooper(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Stormtrooper — oracle/oracle/codemp/game/NPC_spawn.c:2955")
}

/// Raven `SP_NPC_StormtrooperOfficer`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:2987-2991`
pub fn SP_NPC_StormtrooperOfficer(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_Stormtrooper
    // (parked).
    todo!("Port SP_NPC_StormtrooperOfficer — oracle/oracle/codemp/game/NPC_spawn.c:2987")
}

/// Raven `SP_NPC_Snowtrooper`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3001-3006`
pub fn SP_NPC_Snowtrooper(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Snowtrooper — oracle/oracle/codemp/game/NPC_spawn.c:3001")
}

/// Raven `SP_NPC_Tie_Pilot`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3016-3021`
pub fn SP_NPC_Tie_Pilot(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Tie_Pilot — oracle/oracle/codemp/game/NPC_spawn.c:3016")
}

/// Raven `SP_NPC_Ugnaught`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3030-3045`
pub fn SP_NPC_Ugnaught(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Ugnaught — oracle/oracle/codemp/game/NPC_spawn.c:3030")
}

/// Raven `SP_NPC_Jawa`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3056-3071`
pub fn SP_NPC_Jawa(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Jawa — oracle/oracle/codemp/game/NPC_spawn.c:3056")
}

/// Raven `SP_NPC_Gran`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3084-3110`
pub fn SP_NPC_Gran(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Gran — oracle/oracle/codemp/game/NPC_spawn.c:3084")
}

/// Raven `SP_NPC_Rodian`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3121-3136`
pub fn SP_NPC_Rodian(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Rodian — oracle/oracle/codemp/game/NPC_spawn.c:3121")
}

/// Raven `SP_NPC_Weequay`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3145-3167`
pub fn SP_NPC_Weequay(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Weequay — oracle/oracle/codemp/game/NPC_spawn.c:3145")
}

/// Raven `SP_NPC_Trandoshan`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3176-3184`
pub fn SP_NPC_Trandoshan(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Trandoshan — oracle/oracle/codemp/game/NPC_spawn.c:3176")
}

/// Raven `SP_NPC_Tusken`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3193-3208`
pub fn SP_NPC_Tusken(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Tusken — oracle/oracle/codemp/game/NPC_spawn.c:3193")
}

/// Raven `SP_NPC_Noghri`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3217-3225`
pub fn SP_NPC_Noghri(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Noghri — oracle/oracle/codemp/game/NPC_spawn.c:3217")
}

/// Raven `SP_NPC_SwampTrooper`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3235-3250`
pub fn SP_NPC_SwampTrooper(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_SwampTrooper — oracle/oracle/codemp/game/NPC_spawn.c:3235")
}

/// Raven `SP_NPC_Imperial`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3267-3301`
pub fn SP_NPC_Imperial(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Imperial — oracle/oracle/codemp/game/NPC_spawn.c:3267")
}

/// Raven `SP_NPC_ImpWorker`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3310-3329`
pub fn SP_NPC_ImpWorker(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_ImpWorker — oracle/oracle/codemp/game/NPC_spawn.c:3310")
}

/// Raven `SP_NPC_BespinCop`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3338-3353`
pub fn SP_NPC_BespinCop(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_BespinCop — oracle/oracle/codemp/game/NPC_spawn.c:3338")
}

/// Raven `SP_NPC_Reborn`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3372-3400`
pub fn SP_NPC_Reborn(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Reborn — oracle/oracle/codemp/game/NPC_spawn.c:3372")
}

/// Raven `SP_NPC_ShadowTrooper`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3409-3427`
pub fn SP_NPC_ShadowTrooper(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_ShadowTrooper — oracle/oracle/codemp/game/NPC_spawn.c:3409")
}

/// Raven `SP_NPC_Monster_Murjj`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3439-3444`
pub fn SP_NPC_Monster_Murjj(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Murjj — oracle/oracle/codemp/game/NPC_spawn.c:3439")
}

/// Raven `SP_NPC_Monster_Swamp`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3453-3458`
pub fn SP_NPC_Monster_Swamp(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Swamp — oracle/oracle/codemp/game/NPC_spawn.c:3453")
}

/// Raven `SP_NPC_Monster_Howler`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3467-3472`
pub fn SP_NPC_Monster_Howler(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Howler — oracle/oracle/codemp/game/NPC_spawn.c:3467")
}

/// Raven `SP_NPC_MineMonster`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3481-3487`
pub fn SP_NPC_MineMonster(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_MineMonster — oracle/oracle/codemp/game/NPC_spawn.c:3481")
}

/// Raven `SP_NPC_Monster_Claw`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3496-3501`
pub fn SP_NPC_Monster_Claw(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Claw — oracle/oracle/codemp/game/NPC_spawn.c:3496")
}

/// Raven `SP_NPC_Monster_Glider`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3510-3515`
pub fn SP_NPC_Monster_Glider(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Glider — oracle/oracle/codemp/game/NPC_spawn.c:3510")
}

/// Raven `SP_NPC_Monster_Flier2`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3524-3529`
pub fn SP_NPC_Monster_Flier2(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Flier2 — oracle/oracle/codemp/game/NPC_spawn.c:3524")
}

/// Raven `SP_NPC_Monster_Lizard`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3538-3543`
pub fn SP_NPC_Monster_Lizard(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Lizard — oracle/oracle/codemp/game/NPC_spawn.c:3538")
}

/// Raven `SP_NPC_Monster_Fish`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3552-3557`
pub fn SP_NPC_Monster_Fish(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Fish — oracle/oracle/codemp/game/NPC_spawn.c:3552")
}

/// Raven `SP_NPC_Monster_Wampa`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3568-3575`
pub fn SP_NPC_Monster_Wampa(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Wampa — oracle/oracle/codemp/game/NPC_spawn.c:3568")
}

/// Raven `SP_NPC_Monster_Rancor`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3584-3589`
pub fn SP_NPC_Monster_Rancor(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Monster_Rancor — oracle/oracle/codemp/game/NPC_spawn.c:3584")
}

/// Raven `SP_NPC_Droid_Interrogator`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3602-3609`
pub fn SP_NPC_Droid_Interrogator(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Interrogator — oracle/oracle/codemp/game/NPC_spawn.c:3602")
}

/// Raven `SP_NPC_Droid_Probe`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3620-3627`
pub fn SP_NPC_Droid_Probe(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Probe — oracle/oracle/codemp/game/NPC_spawn.c:3620")
}

/// Raven `SP_NPC_Droid_Mark1`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3639-3646`
pub fn SP_NPC_Droid_Mark1(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Mark1 — oracle/oracle/codemp/game/NPC_spawn.c:3639")
}

/// Raven `SP_NPC_Droid_Mark2`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3658-3665`
pub fn SP_NPC_Droid_Mark2(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Mark2 — oracle/oracle/codemp/game/NPC_spawn.c:3658")
}

/// Raven `SP_NPC_Droid_ATST`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3674-3688`
pub fn SP_NPC_Droid_ATST(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_ATST — oracle/oracle/codemp/game/NPC_spawn.c:3674")
}

/// Raven `SP_NPC_Droid_Remote`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3699-3706`
pub fn SP_NPC_Droid_Remote(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Remote — oracle/oracle/codemp/game/NPC_spawn.c:3699")
}

/// Raven `SP_NPC_Droid_Seeker`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3717-3724`
pub fn SP_NPC_Droid_Seeker(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Seeker — oracle/oracle/codemp/game/NPC_spawn.c:3717")
}

/// Raven `SP_NPC_Droid_Sentry`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3735-3742`
pub fn SP_NPC_Droid_Sentry(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Sentry — oracle/oracle/codemp/game/NPC_spawn.c:3735")
}

/// Raven `SP_NPC_Droid_Gonk`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3755-3763`
pub fn SP_NPC_Droid_Gonk(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Gonk — oracle/oracle/codemp/game/NPC_spawn.c:3755")
}

/// Raven `SP_NPC_Droid_Mouse`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3776-3785`
pub fn SP_NPC_Droid_Mouse(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Mouse — oracle/oracle/codemp/game/NPC_spawn.c:3776")
}

/// Raven `SP_NPC_Droid_R2D2`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3798-3812`
pub fn SP_NPC_Droid_R2D2(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_R2D2 — oracle/oracle/codemp/game/NPC_spawn.c:3798")
}

/// Raven `SP_NPC_Droid_R5D2`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3826-3840`
pub fn SP_NPC_Droid_R5D2(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_R5D2 — oracle/oracle/codemp/game/NPC_spawn.c:3826")
}

/// Raven `SP_NPC_Droid_Protocol`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3851-3864`
pub fn SP_NPC_Droid_Protocol(
    self_: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on SP_NPC_spawner (parked).
    todo!("Port SP_NPC_Droid_Protocol — oracle/oracle/codemp/game/NPC_spawn.c:3851")
}

/// Raven `NPC_SpawnType`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:3872-4018`
pub fn NPC_SpawnType(
    ent: *mut gentity_t,
    npc_type: *mut c_char,
    targetname: *mut c_char,
    isVehicle: qboolean,
) -> *mut gentity_t {
    // PORT-ESCALATION(packet-contract): 146-LOC dispatcher over every
    // SP_NPC_* constructor above (all parked) plus G_Spawn/G_FreeEntity, not
    // resolved here.
    todo!("Port NPC_SpawnType — oracle/oracle/codemp/game/NPC_spawn.c:3872")
}

/// Raven `NPC_Spawn_f`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:4020-4039`
pub fn NPC_Spawn_f(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): depends on NPC_SpawnType (parked)
    // and trap_Argc/trap_Argv console-arg helpers not resolved here.
    todo!("Port NPC_Spawn_f — oracle/oracle/codemp/game/NPC_spawn.c:4020")
}

/// Raven `NPC_Kill_f`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:4045-4170`
pub fn NPC_Kill_f() {
    // PORT-ESCALATION(packet-contract): 126-LOC console command touching
    // g_entities/level and G_Damage, not resolved here.
    todo!("Port NPC_Kill_f — oracle/oracle/codemp/game/NPC_spawn.c:4045")
}

/// Raven `NPC_PrintScore`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:4172-4175`
pub fn NPC_PrintScore(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): needs trap_SendServerCommand /
    // score-string helpers, not resolved here.
    todo!("Port NPC_PrintScore — oracle/oracle/codemp/game/NPC_spawn.c:4172")
}

/// Raven `Cmd_NPC_f`.
///
/// Source: `oracle/oracle/codemp/game/NPC_spawn.c:4183-4243`
pub fn Cmd_NPC_f(
    ent: *mut gentity_t,
) {
    // PORT-ESCALATION(packet-contract): console-command dispatcher over
    // NPC_Spawn_f/NPC_Kill_f/NPC_PrintScore (all parked) plus trap_Argv, not
    // resolved here.
    todo!("Port Cmd_NPC_f — oracle/oracle/codemp/game/NPC_spawn.c:4183")
}
