//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_utils.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `CalcEntitySpot`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:20-168`
pub fn CalcEntitySpot(
    ent: *const gentity_t,
    spot: spot_t,
    point: vec3_t,
) {
    todo!("Port CalcEntitySpot — oracle/oracle/codemp/game/NPC_utils.c:20")
}

/// Raven `NPC_UpdateAngles`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:182-517`
pub fn NPC_UpdateAngles(
    doPitch: qboolean,
    doYaw: qboolean,
) -> qboolean {
    todo!("Port NPC_UpdateAngles — oracle/oracle/codemp/game/NPC_utils.c:182")
}

/// Raven `NPC_AimWiggle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:519-533`
pub fn NPC_AimWiggle(
    enemy_org: vec3_t,
) {
    todo!("Port NPC_AimWiggle — oracle/oracle/codemp/game/NPC_utils.c:519")
}

/// Raven `NPC_UpdateFiringAngles`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:540-731`
pub fn NPC_UpdateFiringAngles(
    doPitch: qboolean,
    doYaw: qboolean,
) -> qboolean {
    todo!("Port NPC_UpdateFiringAngles — oracle/oracle/codemp/game/NPC_utils.c:540")
}

/// Raven `NPC_UpdateShootAngles`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:740-808`
pub fn NPC_UpdateShootAngles(
    angles: vec3_t,
    doPitch: qboolean,
    doYaw: qboolean,
) {
    todo!("Port NPC_UpdateShootAngles — oracle/oracle/codemp/game/NPC_utils.c:740")
}

/// Raven `SetTeamNumbers`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:818-847`
pub fn SetTeamNumbers() {
    todo!("Port SetTeamNumbers — oracle/oracle/codemp/game/NPC_utils.c:818")
}

/// Raven `G_ActivateBehavior`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:851-894`
pub fn G_ActivateBehavior(
    self_: *mut gentity_t,
    bset: c_int,
) -> qboolean {
    todo!("Port G_ActivateBehavior — oracle/oracle/codemp/game/NPC_utils.c:851")
}

/// Raven `NPC_SetBoneAngles`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:906-995`
pub fn NPC_SetBoneAngles(
    ent: *mut gentity_t,
    bone: *mut c_char,
    angles: vec3_t,
) {
    todo!("Port NPC_SetBoneAngles — oracle/oracle/codemp/game/NPC_utils.c:906")
}

/// Raven `NPC_SetSurfaceOnOff`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1001-1039`
pub fn NPC_SetSurfaceOnOff(
    ent: *mut gentity_t,
    surfaceName: *const c_char,
    surfaceFlags: c_int,
) {
    todo!("Port NPC_SetSurfaceOnOff — oracle/oracle/codemp/game/NPC_utils.c:1001")
}

/// Raven `NPC_SomeoneLookingAtMe`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1042-1067`
pub fn NPC_SomeoneLookingAtMe(
    ent: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_SomeoneLookingAtMe — oracle/oracle/codemp/game/NPC_utils.c:1042")
}

/// Raven `NPC_ClearLOS`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1069-1072`
pub fn NPC_ClearLOS(
    start: vec3_t,
    end: vec3_t,
) -> qboolean {
    todo!("Port NPC_ClearLOS — oracle/oracle/codemp/game/NPC_utils.c:1069")
}

/// Raven `NPC_ClearLOS5`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1073-1076`
pub fn NPC_ClearLOS5(
    end: vec3_t,
) -> qboolean {
    todo!("Port NPC_ClearLOS5 — oracle/oracle/codemp/game/NPC_utils.c:1073")
}

/// Raven `NPC_ClearLOS4`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1077-1080`
pub fn NPC_ClearLOS4(
    ent: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_ClearLOS4 — oracle/oracle/codemp/game/NPC_utils.c:1077")
}

/// Raven `NPC_ClearLOS3`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1081-1084`
pub fn NPC_ClearLOS3(
    start: vec3_t,
    ent: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_ClearLOS3 — oracle/oracle/codemp/game/NPC_utils.c:1081")
}

/// Raven `NPC_ClearLOS2`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1085-1088`
pub fn NPC_ClearLOS2(
    ent: *mut gentity_t,
    end: vec3_t,
) -> qboolean {
    todo!("Port NPC_ClearLOS2 — oracle/oracle/codemp/game/NPC_utils.c:1085")
}

/// Raven `NPC_ValidEnemy`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1096-1187`
pub fn NPC_ValidEnemy(
    ent: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_ValidEnemy — oracle/oracle/codemp/game/NPC_utils.c:1096")
}

/// Raven `NPC_TargetVisible`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1195-1210`
pub fn NPC_TargetVisible(
    ent: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_TargetVisible — oracle/oracle/codemp/game/NPC_utils.c:1195")
}

/// Raven `NPC_FindNearestEnemy`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1246-1294`
pub fn NPC_FindNearestEnemy(
    ent: *mut gentity_t,
) -> c_int {
    todo!("Port NPC_FindNearestEnemy — oracle/oracle/codemp/game/NPC_utils.c:1246")
}

/// Raven `NPC_PickEnemyExt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1302-1348`
pub fn NPC_PickEnemyExt(
    checkAlerts: qboolean,
) -> *mut gentity_t {
    todo!("Port NPC_PickEnemyExt — oracle/oracle/codemp/game/NPC_utils.c:1302")
}

/// Raven `NPC_FindPlayer`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1356-1359`
pub fn NPC_FindPlayer() -> qboolean {
    todo!("Port NPC_FindPlayer — oracle/oracle/codemp/game/NPC_utils.c:1356")
}

/// Raven `NPC_CheckPlayerDistance`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1367-1399`
pub fn NPC_CheckPlayerDistance() -> qboolean {
    todo!("Port NPC_CheckPlayerDistance — oracle/oracle/codemp/game/NPC_utils.c:1367")
}

/// Raven `NPC_FindEnemy`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1407-1461`
pub fn NPC_FindEnemy(
    checkAlerts: qboolean,
) -> qboolean {
    todo!("Port NPC_FindEnemy — oracle/oracle/codemp/game/NPC_utils.c:1407")
}

/// Raven `NPC_CheckEnemyExt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1469-1483`
pub fn NPC_CheckEnemyExt(
    checkAlerts: qboolean,
) -> qboolean {
    todo!("Port NPC_CheckEnemyExt — oracle/oracle/codemp/game/NPC_utils.c:1469")
}

/// Raven `NPC_FacePosition`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1491-1547`
pub fn NPC_FacePosition(
    position: vec3_t,
    doPitch: qboolean,
) -> qboolean {
    todo!("Port NPC_FacePosition — oracle/oracle/codemp/game/NPC_utils.c:1491")
}

/// Raven `NPC_FaceEntity`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1555-1563`
pub fn NPC_FaceEntity(
    ent: *mut gentity_t,
    doPitch: qboolean,
) -> qboolean {
    todo!("Port NPC_FaceEntity — oracle/oracle/codemp/game/NPC_utils.c:1555")
}

/// Raven `NPC_FaceEnemy`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1571-1580`
pub fn NPC_FaceEnemy(
    doPitch: qboolean,
) -> qboolean {
    todo!("Port NPC_FaceEnemy — oracle/oracle/codemp/game/NPC_utils.c:1571")
}

/// Raven `NPC_CheckCanAttackExt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1588-1603`
pub fn NPC_CheckCanAttackExt() -> qboolean {
    todo!("Port NPC_CheckCanAttackExt — oracle/oracle/codemp/game/NPC_utils.c:1588")
}

/// Raven `NPC_ClearLookTarget`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1611-1625`
pub fn NPC_ClearLookTarget(
    self_: *mut gentity_t,
) {
    todo!("Port NPC_ClearLookTarget — oracle/oracle/codemp/game/NPC_utils.c:1611")
}

/// Raven `NPC_SetLookTarget`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1632-1646`
pub fn NPC_SetLookTarget(
    self_: *mut gentity_t,
    entNum: c_int,
    clearTime: c_int,
) {
    todo!("Port NPC_SetLookTarget — oracle/oracle/codemp/game/NPC_utils.c:1632")
}

/// Raven `NPC_CheckLookTarget`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1653-1679`
pub fn NPC_CheckLookTarget(
    self_: *mut gentity_t,
) -> qboolean {
    todo!("Port NPC_CheckLookTarget — oracle/oracle/codemp/game/NPC_utils.c:1653")
}

/// Raven `NPC_CheckCharmed`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1687-1705`
pub fn NPC_CheckCharmed() {
    todo!("Port NPC_CheckCharmed — oracle/oracle/codemp/game/NPC_utils.c:1687")
}

/// Raven `G_GetBoltPosition`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1707-1740`
pub fn G_GetBoltPosition(
    self_: *mut gentity_t,
    boltIndex: c_int,
    pos: vec3_t,
    modelIndex: c_int,
) {
    todo!("Port G_GetBoltPosition — oracle/oracle/codemp/game/NPC_utils.c:1707")
}

/// Raven `NPC_EntRangeFromBolt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1742-1754`
pub fn NPC_EntRangeFromBolt(
    targEnt: *mut gentity_t,
    boltIndex: c_int,
) -> f32 {
    todo!("Port NPC_EntRangeFromBolt — oracle/oracle/codemp/game/NPC_utils.c:1742")
}

/// Raven `NPC_EnemyRangeFromBolt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1756-1759`
pub fn NPC_EnemyRangeFromBolt(
    boltIndex: c_int,
) -> f32 {
    todo!("Port NPC_EnemyRangeFromBolt — oracle/oracle/codemp/game/NPC_utils.c:1756")
}

/// Raven `NPC_GetEntsNearBolt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_utils.c:1761-1782`
pub fn NPC_GetEntsNearBolt(
    radiusEnts: *mut c_int,
    radius: f32,
    boltIndex: c_int,
    boltOrg: vec3_t,
) -> c_int {
    todo!("Port NPC_GetEntsNearBolt — oracle/oracle/codemp/game/NPC_utils.c:1761")
}
