//! FAITHFUL signature skeleton for `oracle/oracle/codemp/game/NPC_AI_Remote.c`.
//!
//! Generated by `tools/closure-prototype/fnskel.py` from the fnsweep
//! manifest. STAGING ONLY — not wired into crates/. Bodies are
//! `todo!()`; types resolve against already-ported crates, unresolved
//! ones carry `//TODO: Port <type>` markers. Re-run after editing the
//! RULES TABLE in fnskel.py.
#![allow(non_snake_case, unused, clippy::all)]

use crate::prelude::*;


/// Raven `NPC_Remote_Precache`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:17-22`
pub fn NPC_Remote_Precache() {
    todo!("Port NPC_Remote_Precache — oracle/oracle/codemp/game/NPC_AI_Remote.c:17")
}

/// Raven `NPC_Remote_Pain`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:29-37`
pub fn NPC_Remote_Pain(
    self_: *mut gentity_t,
    attacker: *mut gentity_t,
    damage: c_int,
) {
    todo!("Port NPC_Remote_Pain — oracle/oracle/codemp/game/NPC_AI_Remote.c:29")
}

/// Raven `Remote_MaintainHeight`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:44-128`
pub fn Remote_MaintainHeight() {
    todo!("Port Remote_MaintainHeight — oracle/oracle/codemp/game/NPC_AI_Remote.c:44")
}

/// Raven `Remote_Strafe`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:139-168`
pub fn Remote_Strafe() {
    todo!("Port Remote_Strafe — oracle/oracle/codemp/game/NPC_AI_Remote.c:139")
}

/// Raven `Remote_Hunt`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:178-221`
pub fn Remote_Hunt(
    visible: qboolean,
    advance: qboolean,
    retreat: qboolean,
) {
    todo!("Port Remote_Hunt — oracle/oracle/codemp/game/NPC_AI_Remote.c:178")
}

/// Raven `Remote_Fire`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:229-257`
pub fn Remote_Fire() {
    todo!("Port Remote_Fire — oracle/oracle/codemp/game/NPC_AI_Remote.c:229")
}

/// Raven `Remote_Ranged`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:264-277`
pub fn Remote_Ranged(
    visible: qboolean,
    advance: qboolean,
    retreat: qboolean,
) {
    todo!("Port Remote_Ranged — oracle/oracle/codemp/game/NPC_AI_Remote.c:264")
}

/// Raven `Remote_Attack`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:290-332`
pub fn Remote_Attack() {
    todo!("Port Remote_Attack — oracle/oracle/codemp/game/NPC_AI_Remote.c:290")
}

/// Raven `Remote_Idle`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:339-344`
pub fn Remote_Idle() {
    todo!("Port Remote_Idle — oracle/oracle/codemp/game/NPC_AI_Remote.c:339")
}

/// Raven `Remote_Patrol`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:351-367`
pub fn Remote_Patrol() {
    todo!("Port Remote_Patrol — oracle/oracle/codemp/game/NPC_AI_Remote.c:351")
}

/// Raven `NPC_BSRemote_Default`.
///
/// Source: `oracle/oracle/codemp/game/NPC_AI_Remote.c:375-389`
pub fn NPC_BSRemote_Default() {
    todo!("Port NPC_BSRemote_Default — oracle/oracle/codemp/game/NPC_AI_Remote.c:375")
}
