[package]
name = "mp_engine_client"
version = "0.1.0"
edition = "2021"

[lib]
name = "mp_engine_client"

[dependencies]
native_platform = { path = "../../../native/platform" }
native_types = { path = "../../../native/types" }
mp_qshared = { path = "../../qshared" }
mp_engine_qcommon = { path = "../qcommon" }
mp_abi = { path = "../../abi" }
