export const meta = {
  name: 'port-wave',
  description: 'Port one wave of Raven C types from pre-generated packets (pre-wired skeleton, fully parallel porters, machine-verified)',
  whenToUse: 'Batch type-porting. args = {mpModule, spModule, mpCrate, spCrate, manifestPath, skipDocs?, mp: [entry...], sp: [entry...]} — generate packets with tools/closure-prototype/sweep.py <module> --header <h> --packets --json (filter to unported), adding {folder, level?, crate?, srcDir?, file?} per entry. level = heavy dependency level (1 = no unported by-value deps among heavies, 2 = depends on level-1 heavies, ...). crate/srcDir override the run defaults for seam types targeting abi/qshared; file overrides the snake_case default.',
  phases: [
    { title: 'Skeleton', detail: 'pre-create every type file + fully wire mod.rs — porters never touch shared files' },
    { title: 'Port', detail: 'per-folder, MP chunks parallel then SP chunks parallel; haiku trivials, sonnet mediums' },
    { title: 'Heavy', detail: 'dependency levels; within a level all heavies parallel, SP chained after its MP twin' },
    { title: 'Verify', detail: 'one-parse badge sweep + cargo, fixer rounds' },
    { title: 'Docs', detail: 'update docs/type-port-todo.md' },
  ],
}

// args = { mpModule, spModule, mpCrate, spCrate, manifestPath,
//          mp: [{name, kind, sizeB, tier, folder, cite, level?}...], sp: [...] }
// manifestPath: JSON file holding the SAME entries WITH packet fields
// (source, asserts) generated by sweep.py --packets --json. Porters read
// their own entries from it; args stays small.
const A = (typeof args === 'string' ? JSON.parse(args) : args) || {}
for (const k of ['mpModule', 'spModule', 'mpCrate', 'spCrate', 'manifestPath']) {
  if (!A[k]) throw new Error(`args.${k} required`)
}
const snake = n => n.replace(/([a-z0-9])([A-Z])/g, '$1_$2').replace(/__+/g, '_').toLowerCase()
// Per-entry {crate, srcDir} may override the run defaults, so one run can mix
// module-private targets with abi/qshared seam targets (parsed via the same
// module TU). Defaults: run-level args.mpCrate/spCrate + module-derived src.
const prep = (list, defCrate, defSrcDir) => (list || []).filter(t => t.folder).map(t => ({
  ...t,
  file: t.file || `${snake(t.name)}.rs`,
  crate: t.crate || defCrate,
  srcDir: t.srcDir || defSrcDir,
}))
const modSrc = (m, ov) => ov || `crates/${m.replace('-', '/')}/src`
const MP = prep(A.mp, A.mpCrate, modSrc(A.mpModule, A.mpSrcDir))
const SP = prep(A.sp, A.spCrate, modSrc(A.spModule, A.spSrcDir))
if (!MP.length && !SP.length) throw new Error('args.mp / args.sp packet lists are empty')

const SWEEP = 'tools/closure-prototype/.venv/bin/python tools/closure-prototype/sweep.py'

const RULES = `HOUSE RULES (binding — docs/porting-rules.md):
- NEVER edit anything under oracle/oracle/.
- Enum-vs-alias fidelity: "typedef enum {...} X" -> #[repr(i32)] pub enum X;
  "typedef int X" + separate anon enum -> pub type X = c_int + pub const items.
  NEVER flatten a named enum to an int alias. (The packet's "kind" field tells
  you which: kind=enum -> repr(i32) enum; kind=alias -> type alias + consts.)
- Your target file(s) ALREADY EXIST as ABI-sized placeholder stubs and are
  ALREADY registered in mod.rs. Overwrite each placeholder with the port.
  NEVER edit mod.rs, lib.rs, or any file that is not one of your assigned
  type files.
- By-value deps that are still placeholders: import and embed them NORMALLY —
  every wave file already has the correct size/alignment, so your offsets and
  asserts are right from the first cargo check. Do NOT hand-roll [u8; N]
  blob fields for wave siblings.
- If house style renames your item (C tag -> typedef name), ALSO emit
  pub type <manifest name> = <new name>; when they differ, so siblings that
  imported the manifest name stay green.
- Every item gets a doc comment + source ref, exactly this shape:
    /// Raven \`X\` — <one-line description>.
    ///
    /// Raven: <original Raven comment, if any>.
    /// Type definition source: \`oracle/oracle/codemp/game/bg_public.h:NNN-MMM\`
- #[repr(C)] structs: exact Raven field names/order; paste the provided assert
  block verbatim; gate pointer-width-dependent asserts with
  #[cfg(target_pointer_width = "64")].
- Unported deps: //TODO: Port <RavenIdent> + // Source: <oracle path:line>;
  pointer-only deps may stay opaque (*mut c_void or a c_void alias).
- By-value fields of sibling wave types: import them via the crate path of the
  sibling file (same folder -> use super::<file>::<Type>).
- Preserve Raven's comments from the packet source; state conclusions, don't
  re-derive C mechanics. Trust ONLY cargo check (rust-analyzer is stale).
- IMPORT CHEAT SHEET (do NOT spend tool calls rediscovering these):
  qboolean, qhandle_t, sfxHandle_t, fxHandle_t, clipHandle_t, fileHandle_t,
  vec_t, vec2_t, vec3_t, vec4_t, gameState_t, vmCvar_t are all re-exported
  from <tree>_qshared::shared (e.g. use mp_qshared::shared::{qboolean,
  vec4_t}; SP: sp_qshared::shared::{...}).
  Tree-specific types sit under <tree>_qshared::common::<mp|sp>::<subsystem>
  (e.g. mp_qshared::common::mp::cgame::glconfig_t::glconfig_t).
  Wave-2 bg types: <tree>_bg::<folder>::<file>::<Type>.
  Wave-3 renderer types (refEntity_t, refdef_t, glconfig_t, polyVert_t, ...):
  MP mp_qshared::common::mp::cgame::<file>::<Type>; SP
  sp_qshared::common::sp::renderer::<file>::<Type>.
  Wave-3 ui_shared types (displayContextDef_t, menuDef_t, itemDef_s, ...):
  <tree>_uishared::shared::<file>::<Type>.
  Cross-crate wave siblings (e.g. snapshot_t in <tree>_abi): use the crate
  path <crate>::<folder-path>::<file>::<Type> exactly as listed in the
  sibling's target file. If a needed item truly isn't there, ONE grep for
  "pub struct <Name>\\|pub type <Name>" across crates/ settles it — then move
  on.
- STYLE PRECEDENT: crates/mp/bg/src/weapons/weapon_data_t.rs is a known-good
  medium port; copy its shape (doc header, repr, assert block placement)
  instead of exploring other files for precedent. Structs: no derives unless
  the packet demands one; keep C tag name only if the typedef differs from it
  (pub struct X_s + pub type X_t = X_s is NOT house style — name the struct by
  the typedef, like playerState_t).
- The placeholder file must be Read once before you overwrite it (Write-tool
  requirement) — one Read, one Write, no re-read after.
- Every new file starts with #![allow(non_camel_case_types, non_snake_case)]
  (file-level, like the existing ports) — the build must stay at ZERO new
  warnings, not just zero errors.
- Tools and orchestration are BLACK BOXES: never read or inspect sweep.py /
  closure.py / anything under .claude/workflows/ / any tool source. Run the
  exact command given, read its stdout, move on. A badge line looks like:
  \`  gitem_t   ☑ crates/.../game_item.rs\`  (☑ = verified, anything else =
  fix your port).`

const PORT_SCHEMA = {
  type: 'object',
  properties: {
    ported: { type: 'array', items: { type: 'object', properties: {
      name: { type: 'string' }, file: { type: 'string' } }, required: ['name', 'file'] } },
    deferred: { type: 'array', items: { type: 'object', properties: {
      subject: { type: 'string' }, source: { type: 'string' } }, required: ['subject', 'source'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['ported', 'deferred', 'problems'],
}

function portPrompt(mode, module, list, mpFiles) {
  const { crate, srcDir, folder } = list[0]
  const spNote = mode === 'SP' ? `
SP pass: the packets are from the SP oracle (code/), which DIVERGES from MP.
Use the MP baseline file listed per type as a style/diff reference only —
port what the SP packet source says. No MP baseline -> port fresh.` : ''
  const names = list.map(t => t.name)
  return `Port these Raven types into ${srcDir}/${folder}/ (crate ${crate}).
Your packets are pre-generated. Extract ONLY your entries (the manifest is too
large to cat) with exactly:
  python3 -c "import json; d=json.load(open('${A.manifestPath}')); ns={${names.map(n => `'${n}'`).join(',')}}; print(json.dumps([e for e in d['${mode.toLowerCase()}'] if e['name'] in ns], indent=1))"
Each entry has the verbatim oracle source (line-numbered), cite, and (for
structs) a ready assert block. Do NOT explore the oracle or run closure.py;
transcribe faithfully into the pre-created placeholder file listed per type,
verify.
${RULES}
${spNote}
Types (type -> your file, in ${srcDir}/${folder}/):
${list.map(t => `- ${t.name} (${t.kind}, ${t.tier}, ${t.sizeB}B) -> ${t.file}${mode === 'SP' && mpFiles && mpFiles[t.name] ? ` [MP baseline: ${mpFiles[t.name]}]` : ''}`).join('\n')}

End state:
1. cargo check -p ${crate} GREEN (zero new warnings).
2. Self-check badges (single call):
   ${SWEEP} ${module} --badges ${list.map(t => t.name).join(',')}
   Every struct you ported must show ☑. Fix before returning if not.
Return ONLY the structured result; final message is data, not prose.`
}

// ---------------------------------------------------------------- Skeleton
// Pre-create EVERY type file as a compilable placeholder and wire every
// mod.rs line up front. After this, no two agents ever write the same file,
// so Port and Heavy phases parallelize freely.
phase('Skeleton')
const allCrates = [...new Set([...MP, ...SP].map(t => t.crate))]
const skeletonSpec = [
  { module: A.mpModule, types: MP },
  { module: A.spModule, types: SP },
].filter(s => s.types.length).map(s => ({
  module: s.module,
  files: s.types.map(t => ({
    path: `${t.srcDir}/${t.folder}/${t.file}`,
    crate: t.crate, name: t.name, cite: t.cite,
    kind: t.kind, sizeB: t.sizeB,
  })),
}))
await agent(
`Prepare crate skeletons for a type-port wave (repo root cwd). NEVER touch
oracle/oracle/. For each entry below:
1. Ensure the folder exists with a mod.rs registered up to the crate's lib.rs
   (folders are subsystem dirs; match the existing style of sibling mod.rs
   files — a //! doc line then pub mod lines, alphabetical).
2. Create EVERY listed type file as an ABI-SIZED placeholder so siblings can
   embed the type by value before its real port lands (port order then never
   matters). Every placeholder starts with:
     #![allow(non_camel_case_types, non_snake_case)]
     //TODO: Port <name>
     // Source: <cite>
   then, by kind:
   - struct/union (sizeB = N > 0):
       #[repr(C, align(A))]
       pub struct <name>(pub [u8; N]);
       const _: () = assert!(core::mem::size_of::<<name>>() == N);
     where A = 8 if N%8==0 else 4 if N%4==0 else 2 if N%2==0 else 1.
   - enum or alias: pub type <name> = ::core::ffi::c_int;
     (ABI-identical 4-byte placeholder; the real port replaces it.)
   If the file already exists with real content, leave it alone but still
   ensure it is registered.
3. Register every file in its folder's mod.rs (pub mod <file-stem>;).
Use ONE python3 heredoc to create everything, then verify.
Spec (JSON): ${JSON.stringify(skeletonSpec)}
Finish with cargo check ${allCrates.map(c => `-p ${c}`).join(' ')} GREEN, zero new warnings.`,
  { label: 'skeleton', phase: 'Skeleton', model: 'sonnet' }
)

// ------------------------------------------------------------------- Port
// Per-folder pipelines: within a folder, all MP chunks run in PARALLEL
// (files pre-wired, no shared edits), then that folder's SP chunks — SP
// still waits only on its own folder's MP pass (baseline references).
phase('Port')
const CHUNK = { trivial: 8, medium: 4 }
function chunks(list) {
  const triv = list.filter(t => t.tier === 'trivial')
  const med = list.filter(t => t.tier === 'medium')
  const out = []
  for (let i = 0; i < triv.length; i += CHUNK.trivial)
    out.push({ tier: 'trivial', types: triv.slice(i, i + CHUNK.trivial) })
  for (let i = 0; i < med.length; i += CHUNK.medium)
    out.push({ tier: 'medium', types: med.slice(i, i + CHUNK.medium) })
  return out
}
const groupKey = t => `${t.srcDir}/${t.folder}`
const folders = [...new Set([...MP.map(groupKey), ...SP.map(groupKey)])]
const mpFiles = {}
const lightResults = await parallel(folders.map(key => async () => {
  const out = []
  const label = key.split('/').slice(-1)[0]
  const mpChunks = chunks(MP.filter(t => groupKey(t) === key && t.tier !== 'heavy'))
  const mpRs = await parallel(mpChunks.map(c => () => agent(
    portPrompt('MP', A.mpModule, c.types, null),
    { label: `mp:${label}:${c.tier}`, phase: 'Port',
      model: c.tier === 'trivial' ? 'haiku' : 'sonnet', schema: PORT_SCHEMA })))
  for (const r of mpRs.filter(Boolean)) { out.push(r); r.ported.forEach(p => { mpFiles[p.name] = p.file }) }
  const spChunks = chunks(SP.filter(t => groupKey(t) === key && t.tier !== 'heavy'))
  const spRs = await parallel(spChunks.map(c => () => agent(
    portPrompt('SP', A.spModule, c.types, mpFiles),
    { label: `sp:${label}:${c.tier}`, phase: 'Port',
      model: c.tier === 'trivial' ? 'haiku' : 'sonnet', schema: PORT_SCHEMA })))
  out.push(...spRs.filter(Boolean))
  return out
}))
const lightPorted = lightResults.filter(Boolean).flat().flatMap(r => r.ported.map(p => p.name))
log(`light ports done: ${lightPorted.length}`)

// ------------------------------------------------------------------ Heavy
// Heavies grouped by dependency level (entry.level, default 1). Levels run
// sequentially; within a level every MP heavy runs in parallel, each chaining
// its same-name SP twin the moment the MP file lands.
phase('Heavy')
const heavyPorted = { mp: [], sp: [] }
const HEAVY_NOTE = `
HEAVY layout-critical struct: paste the FULL provided assert block (all
offsets). Wave-sibling by-value deps: embed normally (placeholders are
ABI-sized). A by-value dep that is OUTSIDE the wave and unported (e.g. a C++
class): //TODO: Port marker + an ABI-compatible [u8; N] field sized/aligned
from the assert block, recorded under deferred.`
const heavyAgent = async (key, t) => {
  const module = key === 'mp' ? A.mpModule : A.spModule
  const r = await agent(
    portPrompt(key.toUpperCase(), module, [t], key === 'sp' ? mpFiles : null) + HEAVY_NOTE,
    { label: `heavy-${key}:${t.name}`, phase: 'Heavy',
      model: 'sonnet', effort: 'high', schema: PORT_SCHEMA })
  if (r) {
    heavyPorted[key].push(...r.ported.map(p => p.name))
    if (key === 'mp') r.ported.forEach(p => { mpFiles[p.name] = p.file })
  }
}
const mpHeavy = MP.filter(t => t.tier === 'heavy')
const spHeavy = SP.filter(t => t.tier === 'heavy')
const levels = [...new Set([...mpHeavy, ...spHeavy].map(t => t.level || 1))].sort((a, b) => a - b)
for (const L of levels) {
  const mpL = mpHeavy.filter(t => (t.level || 1) === L)
  const spL = spHeavy.filter(t => (t.level || 1) === L)
  const spTwin = new Map(spL.map(t => [t.name, t]))
  const spOnly = spL.filter(t => !mpL.some(m => m.name === t.name))
  log(`heavy level ${L}: ${mpL.length} MP (+chained SP twins), ${spOnly.length} SP-only`)
  await parallel([
    ...mpL.map(t => async () => {
      await heavyAgent('mp', t)
      if (spTwin.has(t.name)) await heavyAgent('sp', spTwin.get(t.name))
    }),
    ...spOnly.map(t => () => heavyAgent('sp', t)),
  ])
}

// ----------------------------------------------------------------- Verify
phase('Verify')
const claimed = {
  [A.mpModule]: [...new Set([...MP.filter(t => lightPorted.includes(t.name)).map(t => t.name), ...heavyPorted.mp])],
  [A.spModule]: [...new Set([...SP.filter(t => lightPorted.includes(t.name)).map(t => t.name), ...heavyPorted.sp])],
}
const VERIFY_SCHEMA = {
  type: 'object',
  properties: {
    cargoGreen: { type: 'boolean' },
    failures: { type: 'array', items: { type: 'object', properties: {
      module: { type: 'string' }, name: { type: 'string' }, detail: { type: 'string' } },
      required: ['module', 'name', 'detail'] } },
  },
  required: ['cargoGreen', 'failures'],
}
let verdict = null
for (let round = 0; round < 3; round++) {
  verdict = await agent(
`Machine-verify the wave (repo root cwd).
1. cargo check --workspace — report failures verbatim. Also report any
   remaining placeholder stubs (files whose entire content is a //TODO: Port
   marker) among: ${[...MP, ...SP].map(t => t.name).filter(n => !claimed[A.mpModule].includes(n) && !claimed[A.spModule].includes(n)).join(', ') || '(none expected)'}
2. One badge sweep per module (single tool call each):
${Object.entries(claimed).filter(([, ns]) => ns.length).map(([m, ns]) =>
  `   ${SWEEP} ${m} --badges ${ns.join(',')}`).join('\n')}
   Structs must show ☑; "NO SIZE ASSERT"/"SIZE MISMATCH"/☐ are failures.
   Aliases/enums showing ☑ or a plain path are fine.
Return the structured result only.`,
    { label: `verify#${round + 1}`, phase: 'Verify', model: 'sonnet', schema: VERIFY_SCHEMA })
  if (!verdict || (verdict.cargoGreen && verdict.failures.length === 0) || round === 2) break
  log(`verify round ${round + 1}: ${verdict.failures.length} failures — fixing`)
  await agent(
`Fix these wave-port verification failures (repo root cwd).
${RULES}
Failures:
${verdict.failures.map(f => `- [${f.module}] ${f.name}: ${f.detail}`).join('\n')}
${verdict.cargoGreen ? '' : 'cargo check --workspace is failing — fix compile errors first.'}
Ground truth: ${SWEEP} <module> --badges <names> and closure.py --layout/--asserts.
If a mismatch is a genuine oracle divergence you cannot resolve, remove the bad
assert, add //TODO: Port marker, note it. End with cargo check --workspace GREEN.`,
    { label: `fix#${round + 1}`, phase: 'Verify', model: 'sonnet' })
}

// ------------------------------------------------------------------- Docs
// A.skipDocs: when several port-wave runs execute concurrently they must not
// race on the todo doc — the orchestrator updates it once at the end instead.
if (A.skipDocs) {
  return { mpPorted: claimed[A.mpModule], spPorted: claimed[A.spModule], verify: verdict }
}
phase('Docs')
const docs = await agent(
`Update ${A.todoDoc || 'docs/type-port-todo.md'} for the wave that just landed
(repo root cwd). Match the existing table format exactly (☐/◐/☑ marks, oracle
cites, SP divergence notes). Newly ported:
MP (${A.mpModule}): ${claimed[A.mpModule].join(', ') || '(none)'}
SP (${A.spModule}): ${claimed[A.spModule].join(', ') || '(none)'}
Do not commit. Only edit that one doc.`,
  { label: 'docs', phase: 'Docs', model: 'sonnet' })

return { mpPorted: claimed[A.mpModule], spPorted: claimed[A.spModule], verify: verdict, docs }
