export const meta = {
  name: 'port-wave',
  description: 'Port one wave of Raven C types from pre-generated packets (MP+SP pipelined per folder, machine-verified)',
  whenToUse: 'Batch type-porting. args = {mpModule, spModule, mpCrate, spCrate, mp: [packet...], sp: [packet...]} — generate packets with tools/closure-prototype/sweep.py <module> --header <h> --packets --json (filter to unported), adding {folder} per entry.',
  phases: [
    { title: 'Skeleton', detail: 'pre-wire folders/lib.rs so porters never collide' },
    { title: 'Port', detail: 'per-folder pipelines, MP then SP; haiku trivials, sonnet mediums' },
    { title: 'Heavy', detail: 'layout-critical structs, one serial chain, high effort' },
    { title: 'Verify', detail: 'one-parse badge sweep + cargo, fixer rounds' },
    { title: 'Docs', detail: 'update docs/type-port-todo.md' },
  ],
}

// args = { mpModule, spModule, mpCrate, spCrate, manifestPath,
//          mp: [{name, kind, sizeB, tier, folder, cite}...], sp: [...] }
// manifestPath: JSON file holding the SAME entries WITH packet fields
// (source, asserts) generated by sweep.py --packets --json. Porters read
// their own entries from it; args stays small.
const A = (typeof args === 'string' ? JSON.parse(args) : args) || {}
for (const k of ['mpModule', 'spModule', 'mpCrate', 'spCrate', 'manifestPath']) {
  if (!A[k]) throw new Error(`args.${k} required`)
}
const MP = (A.mp || []).filter(t => t.folder)
const SP = (A.sp || []).filter(t => t.folder)
if (!MP.length && !SP.length) throw new Error('args.mp / args.sp packet lists are empty')

const SWEEP = 'tools/closure-prototype/.venv/bin/python tools/closure-prototype/sweep.py'

const RULES = `HOUSE RULES (binding — docs/porting-rules.md):
- NEVER edit anything under oracle/oracle/.
- Enum-vs-alias fidelity: "typedef enum {...} X" -> #[repr(i32)] pub enum X;
  "typedef int X" + separate anon enum -> pub type X = c_int + pub const items.
  NEVER flatten a named enum to an int alias. (The packet's "kind" field tells
  you which: kind=enum -> repr(i32) enum; kind=alias -> type alias + consts.)
- One FLAT file per type — <type_name>.rs (snake_case, like team.rs), inside
  the target folder; never a per-type subfolder. Register in the folder's
  mod.rs ONLY (lib.rs / parents are already wired).
- Every item gets a doc comment + source ref, exactly this shape:
    /// Raven \`X\` — <one-line description>.
    ///
    /// Raven: <original Raven comment, if any>.
    /// Type definition source: \`oracle/oracle/codemp/game/bg_public.h:NNN-MMM\`
- #[repr(C)] structs: exact Raven field names/order; paste the provided assert
  block verbatim; gate pointer-width-dependent asserts with
  #[cfg(target_pointer_width = "64")].
- Unported deps: //TODO: Port <RavenIdent> + // Source: <oracle path:line>;
  pointer-only deps may stay opaque.
- Preserve Raven's comments from the packet source; state conclusions, don't
  re-derive C mechanics. Trust ONLY cargo check (rust-analyzer is stale).
- Every new file starts with #![allow(non_camel_case_types, non_snake_case)]
  (file-level, like the existing ports) — the build must stay at ZERO new
  warnings, not just zero errors.
- Tools are BLACK BOXES: never read or inspect sweep.py / closure.py / any
  tool source. Run the exact command given, read its stdout, move on. A badge
  line looks like:  \`  gitem_t   ☑ crates/.../game_item.rs\`  (☑ = verified,
  anything else = fix your port).`

const PORT_SCHEMA = {
  type: 'object',
  properties: {
    ported: { type: 'array', items: { type: 'object', properties: {
      name: { type: 'string' }, file: { type: 'string' } }, required: ['name', 'file'] } },
    deferred: { type: 'array', items: { type: 'object', properties: {
      subject: { type: 'string' }, source: { type: 'string' } }, required: ['subject', 'source'] } },
    problems: { type: 'array', items: { type: 'string' } },
  },
  required: ['ported', 'deferred', 'problems'],
}

function portPrompt(mode, module, crate, folder, list, mpFiles) {
  const spNote = mode === 'SP' ? `
SP pass: the packets are from the SP oracle (code/), which DIVERGES from MP.
Use the MP baseline file listed per type as a style/diff reference only —
port what the SP packet source says. No MP baseline -> port fresh.` : ''
  return `Port these Raven types into crates/${module.replace('-', '/')}/src/${folder}/ (crate ${crate}).
Your packets are pre-generated: read ${A.manifestPath}
and take the "${mode.toLowerCase()}" entries whose name is listed below — each has the
verbatim oracle source (line-numbered), cite, and (for structs) a ready assert
block. Do NOT explore the oracle or run closure.py; transcribe faithfully,
wire mod.rs, verify.
${RULES}
${spNote}
Types: ${list.map(t => `${t.name} (${t.kind}, ${t.tier}, ${t.sizeB}B)${mode === 'SP' && mpFiles && mpFiles[t.name] ? ` [MP baseline: ${mpFiles[t.name]}]` : ''}`).join(', ')}

End state:
1. cargo check -p ${crate} GREEN.
2. Self-check badges (single call):
   ${SWEEP} ${module} --badges ${list.map(t => t.name).join(',')}
   Every struct you ported must show ☑. Fix before returning if not.
Return ONLY the structured result; final message is data, not prose.`
}

// ---------------------------------------------------------------- Skeleton
phase('Skeleton')
const mpFolders = [...new Set(MP.map(t => t.folder))]
const spFolders = [...new Set(SP.map(t => t.folder))]
await agent(
`Prepare crate skeletons (repo root cwd). ${RULES}
- In crates/${A.mpModule.replace('-', '/')}/src/: ensure folders ${JSON.stringify(mpFolders)} exist,
  each with a mod.rs, registered up to lib.rs.
- In crates/${A.spModule.replace('-', '/')}/src/: same for ${JSON.stringify(spFolders)}.
- Folders are subsystem dirs; do NOT create type files or stub modules.
- If already wired, leave alone. Finish with cargo check -p ${A.mpCrate} -p ${A.spCrate} GREEN.`,
  { label: 'skeleton', phase: 'Skeleton', model: 'sonnet' }
)

// ------------------------------------------------------------------- Port
// Per-folder pipelines: within a folder, MP chunks run serially (mod.rs
// safety), then that folder's SP chunks — so SP never waits on other folders.
phase('Port')
const CHUNK = { trivial: 8, medium: 4 }
function chunks(list) {
  const triv = list.filter(t => t.tier === 'trivial')
  const med = list.filter(t => t.tier === 'medium')
  const out = []
  for (let i = 0; i < triv.length; i += CHUNK.trivial)
    out.push({ tier: 'trivial', types: triv.slice(i, i + CHUNK.trivial) })
  for (let i = 0; i < med.length; i += CHUNK.medium)
    out.push({ tier: 'medium', types: med.slice(i, i + CHUNK.medium) })
  return out
}
const folders = [...new Set([...mpFolders, ...spFolders])]
const mpFiles = {}
const lightResults = await parallel(folders.map(folder => async () => {
  const out = []
  for (const c of chunks(MP.filter(t => t.folder === folder && t.tier !== 'heavy'))) {
    const r = await agent(
      portPrompt('MP', A.mpModule, A.mpCrate, folder, c.types, null),
      { label: `mp:${folder}:${c.tier}`, phase: 'Port',
        model: c.tier === 'trivial' ? 'haiku' : 'sonnet', schema: PORT_SCHEMA })
    if (r) { out.push(r); r.ported.forEach(p => { mpFiles[p.name] = p.file }) }
  }
  for (const c of chunks(SP.filter(t => t.folder === folder && t.tier !== 'heavy'))) {
    const r = await agent(
      portPrompt('SP', A.spModule, A.spCrate, folder, c.types, mpFiles),
      { label: `sp:${folder}:${c.tier}`, phase: 'Port',
        model: c.tier === 'trivial' ? 'haiku' : 'sonnet', schema: PORT_SCHEMA })
    if (r) out.push(r)
  }
  return out
}))
const lightPorted = lightResults.filter(Boolean).flat().flatMap(r => r.ported.map(p => p.name))
log(`light ports done: ${lightPorted.length}`)

// ------------------------------------------------------------------ Heavy
phase('Heavy')
const heavyPorted = { mp: [], sp: [] }
for (const [key, list, module, crate] of [['mp', MP, A.mpModule, A.mpCrate], ['sp', SP, A.spModule, A.spCrate]]) {
  for (const t of list.filter(x => x.tier === 'heavy')) {
    const r = await agent(
      portPrompt(key.toUpperCase(), module, crate, t.folder, [t], key === 'sp' ? mpFiles : null) +
      `\nHEAVY layout-critical struct: paste the FULL provided assert block (all
offsets). If a by-value dep is unported and non-trivial, STOP: add the
//TODO: Port marker, record it under deferred, keep the field ABI-compatible.`,
      { label: `heavy-${key}:${t.name}`, phase: 'Heavy',
        model: 'sonnet', effort: 'high', schema: PORT_SCHEMA })
    if (r) {
      heavyPorted[key].push(...r.ported.map(p => p.name))
      if (key === 'mp') r.ported.forEach(p => { mpFiles[p.name] = p.file })
    }
  }
}

// ----------------------------------------------------------------- Verify
phase('Verify')
const claimed = {
  [A.mpModule]: [...new Set([...MP.filter(t => lightPorted.includes(t.name)).map(t => t.name), ...heavyPorted.mp])],
  [A.spModule]: [...new Set([...SP.filter(t => lightPorted.includes(t.name)).map(t => t.name), ...heavyPorted.sp])],
}
const VERIFY_SCHEMA = {
  type: 'object',
  properties: {
    cargoGreen: { type: 'boolean' },
    failures: { type: 'array', items: { type: 'object', properties: {
      module: { type: 'string' }, name: { type: 'string' }, detail: { type: 'string' } },
      required: ['module', 'name', 'detail'] } },
  },
  required: ['cargoGreen', 'failures'],
}
let verdict = null
for (let round = 0; round < 3; round++) {
  verdict = await agent(
`Machine-verify the wave (repo root cwd).
1. cargo check --workspace — report failures verbatim.
2. One badge sweep per module (single tool call each):
${Object.entries(claimed).filter(([, ns]) => ns.length).map(([m, ns]) =>
  `   ${SWEEP} ${m} --badges ${ns.join(',')}`).join('\n')}
   Structs must show ☑; "NO SIZE ASSERT"/"SIZE MISMATCH"/☐ are failures.
   Aliases/enums showing ☑ or a plain path are fine.
Return the structured result only.`,
    { label: `verify#${round + 1}`, phase: 'Verify', model: 'sonnet', schema: VERIFY_SCHEMA })
  if (!verdict || (verdict.cargoGreen && verdict.failures.length === 0) || round === 2) break
  log(`verify round ${round + 1}: ${verdict.failures.length} failures — fixing`)
  await agent(
`Fix these wave-port verification failures (repo root cwd).
${RULES}
Failures:
${verdict.failures.map(f => `- [${f.module}] ${f.name}: ${f.detail}`).join('\n')}
${verdict.cargoGreen ? '' : 'cargo check --workspace is failing — fix compile errors first.'}
Ground truth: ${SWEEP} <module> --badges <names> and closure.py --layout/--asserts.
If a mismatch is a genuine oracle divergence you cannot resolve, remove the bad
assert, add //TODO: Port marker, note it. End with cargo check --workspace GREEN.`,
    { label: `fix#${round + 1}`, phase: 'Verify', model: 'sonnet' })
}

// ------------------------------------------------------------------- Docs
phase('Docs')
const docs = await agent(
`Update ${A.todoDoc || 'docs/type-port-todo.md'} for the wave that just landed
(repo root cwd). Match the existing table format exactly (☐/◐/☑ marks, oracle
cites, SP divergence notes). Newly ported:
MP (${A.mpModule}): ${claimed[A.mpModule].join(', ') || '(none)'}
SP (${A.spModule}): ${claimed[A.spModule].join(', ') || '(none)'}
Do not commit. Only edit that one doc.`,
  { label: 'docs', phase: 'Docs', model: 'sonnet' })

return { mpPorted: claimed[A.mpModule], spPorted: claimed[A.spModule], verify: verdict, docs }
