[package]
name = "sp_engine_qcommon"
version = "0.1.0"
edition = "2021"

[lib]
name = "sp_engine_qcommon"

[dependencies]
sp_qshared = { path = "../../qshared" }
abi_transport = { path = "../../../abi-transport" }
native_types = { path = "../../../native/types" }
native_platform = { path = "../../../native/platform" }
