#!/usr/bin/env python3
"""PROTOTYPE — throwaway. cgame type inventory for the client-port C0 stage
(DEC-45), sibling of uitypes.py — retargeted from ui to cgame, same
machinery.

Runs the sweep.py type extractor over every cgame-owned header (`cg_local.h`,
`cg_public.h`, `cg_lights.h`, `cg_media.h`, `fx_local.h`, `animtable.h`,
`holocronicons.h`) from one mp-cgame parse, cross-references each type
against the ported Rust tree (crates/mp/cgame, crates/mp/uishared,
crates/mp/abi/src/cgame, crates/native/types — via closure.scan_ported's
verified badges), and classifies each PORTED / STUB / MISSING. Emits
out/cgame/cgame-type-inventory.{json,md}.

Diff vs uitypes.py: HEADERS retargeted to the cgame-owned set (see below for
what was excluded and why); everything else — sweep_header, badge_verdict,
the two-artifact render — is unchanged.

`tr_types.h` (renderer refEntity_t/refdef_t/polyVert_t/… — cgame's Class-B
copy shapes at the CG_TRACE/refresh traps) is deliberately NOT in HEADERS:
it's owned by the renderer subsystem, not cgame, and is already covered by
the R3 renderer wave's own type inventory; listing it here would double-count
against a different module's crate. `cg_media.h` is 0 lines (empty file —
cgMedia_t lives in cg_local.h) and is kept in HEADERS anyway for parity with
uitypes.py's "owns 0 types" tolerance (menudef.h); it costs nothing and keeps
the header list matching the oracle directory listing exactly.

Usage:
  .venv/bin/python cgtypes.py [--out DIR]
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# cgame-owned headers, oracle-relative suffixes (relative to codemp/).
HEADERS = ["cgame/cg_local.h", "cgame/cg_public.h", "cgame/cg_lights.h",
           "cgame/cg_media.h", "cgame/fx_local.h", "cgame/animtable.h",
           "cgame/holocronicons.h"]


def badge_verdict(badge: str) -> str:
    """Map a closure.make_badger glyph to a PORTED / STUB / MISSING verdict.
    ☑ = declared + size-assert-verified; ◐ = declared-no-assert or a TODO
    marker (a stub); ✗ = declared but size MISMATCH (a broken stub); ☐ = no
    declaration at all."""
    if badge.startswith("☑"):      # ☑ declared + verified
        return "PORTED"
    if badge.startswith("☐"):      # ☐ UNPORTED (no declaration)
        return "MISSING"
    if badge.startswith("✗"):      # ✗ declared but size MISMATCH
        return "STUB"
    if badge.startswith("◐"):      # ◐ TODO marker / declared-no-assert
        return "STUB"
    return "MISSING"


def sweep_header(header: str):
    r = subprocess.run(
        [str(HERE / ".venv/bin/python"), str(HERE / "sweep.py"), "mp-cgame",
         "--header", header, "--json"],
        capture_output=True, text=True, cwd=str(HERE))
    if r.returncode != 0:
        sys.exit(f"sweep failed for {header}:\n{r.stderr}")
    return json.loads(r.stdout or "[]")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out", default=str(HERE / "out" / "cgame"))
    args = ap.parse_args()
    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)

    inventory = {}
    for h in HEADERS:
        rows = sweep_header(h)
        for r in rows:
            r["verdict"] = badge_verdict(r["badge"])
        inventory[h] = rows

    totals = {"PORTED": 0, "STUB": 0, "MISSING": 0}
    for rows in inventory.values():
        for r in rows:
            totals[r["verdict"]] += 1
    total_types = sum(totals.values())

    payload = {
        "module": "mp-cgame",
        "headers": HEADERS,
        "totals": totals,
        "total_types": total_types,
        "note": "cg_media.h is 0 lines (empty file; cgMedia_t lives in "
                "cg_local.h, owns 0 types here). tr_types.h (renderer's "
                "refEntity_t/refdef_t/polyVert_t — cgame's Class-B copy "
                "shapes) is deliberately excluded: owned by the renderer "
                "subsystem, covered by its own R3 type inventory.",
        "by_header": inventory,
    }
    (outdir / "cgame-type-inventory.json").write_text(json.dumps(payload, indent=1))

    o = []
    o.append("# cgame type inventory (mp-cgame) — PORTED / STUB / MISSING\n")
    o.append("Generated by `tools/closure-prototype/cgtypes.py` (fans "
             "`sweep.py mp-cgame --header <h> --json` over the cgame-owned "
             "headers; badges are size-assert-verified against the ported "
             "Rust tree — crates/mp/cgame, crates/mp/uishared, "
             "crates/mp/abi/src/cgame, crates/native/types).\n")
    o.append("## Headline\n")
    o.append(f"- **Types owned by cgame headers:** {total_types}")
    o.append(f"- **PORTED:** {totals['PORTED']}  ·  **STUB:** {totals['STUB']}  "
             f"·  **MISSING:** {totals['MISSING']}\n")
    o.append(f"{payload['note']}\n")
    for h in HEADERS:
        rows = inventory[h]
        o.append(f"## `{h}` — {len(rows)} types\n")
        if not rows:
            o.append("_Owns no types._\n")
            continue
        o.append("| type | kind | size | tier | verdict | Rust home / marker | oracle cite |")
        o.append("| --- | --- | ---: | --- | --- | --- | --- |")
        for r in sorted(rows, key=lambda r: r["name"]):
            home = r["badge"].split(" ", 1)[1] if " " in r["badge"] else r["badge"]
            o.append(f"| `{r['name']}` | {r['kind']} | {r['sizeB']}B | {r['tier']} "
                     f"| {r['verdict']} | {home} | {r['cite']} |")
        o.append("")
    (outdir / "cgame-type-inventory.md").write_text("\n".join(o))

    print(f"[cgtypes] {total_types} types  "
          f"PORTED={totals['PORTED']} STUB={totals['STUB']} MISSING={totals['MISSING']}")
    print(f"[cgtypes] wrote {outdir / 'cgame-type-inventory.json'}")
    print(f"[cgtypes] wrote {outdir / 'cgame-type-inventory.md'}")


if __name__ == "__main__":
    main()
