[package]
name = "sp_qshared"
version = "0.1.0"
edition = "2021"

[lib]
name = "sp_qshared"

[dependencies]
native_math = { path = "../../native/math" }
native_platform = { path = "../../native/platform" }
native_string = { path = "../../native/string" }
native_types = { path = "../../native/types" }
