#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

use super::ammo_t::ammo_t;
use super::weapon_data_t::weaponData_t;
use super::weapon_t::WP_NUM_WEAPONS;

/// Raven `weaponData[WP_NUM_WEAPONS]` — per-weapon combat/ammo tuning table.
///
/// Source: `oracle/oracle/codemp/game/bg_weapons.c:31-356`
pub static weaponData: [weaponData_t; WP_NUM_WEAPONS as usize] = [
	weaponData_t {	// WP_NONE
		//		"No Weapon",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_NONE as i32,
		ammoLow: 0,
		energyPerShot: 0,
		fireTime: 0,
		range: 0,
		altEnergyPerShot: 0,
		altFireTime: 0,
		altRange: 0,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_STUN_BATON
		//		"Stun Baton",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_NONE as i32,
		ammoLow: 5,
		energyPerShot: 0,
		fireTime: 400,
		range: 8192,
		altEnergyPerShot: 0,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_MELEE
		//		"Melee",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_NONE as i32,
		ammoLow: 5,
		energyPerShot: 0,
		fireTime: 400,
		range: 8192,
		altEnergyPerShot: 0,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_SABER,
		//		"Lightsaber",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_NONE as i32,
		ammoLow: 5,
		energyPerShot: 0,
		fireTime: 100,
		range: 8192,
		altEnergyPerShot: 0,
		altFireTime: 100,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_BRYAR_PISTOL,
		//		"Bryar Pistol",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_BLASTER as i32,
		ammoLow: 0,	// 15,
		energyPerShot: 0,	// 2,
		fireTime: 800,	// 400,
		range: 8192,
		altEnergyPerShot: 0,	// 2,
		altFireTime: 800,	// 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,	// 200,
		chargeSub: 0,
		altChargeSub: 0,	// 1,
		maxCharge: 0,
		altMaxCharge: 0,	// 1500
	},
	weaponData_t {	// WP_BLASTER
		//		"E11 Blaster Rifle",	//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_BLASTER as i32,
		ammoLow: 5,
		energyPerShot: 2,
		fireTime: 350,
		range: 8192,
		altEnergyPerShot: 3,
		altFireTime: 150,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_DISRUPTOR
		//		"Tenloss Disruptor Rifle",//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_POWERCELL as i32,
		ammoLow: 5,
		energyPerShot: 5,
		fireTime: 600,
		range: 8192,
		altEnergyPerShot: 6,
		altFireTime: 1300,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 200,
		chargeSub: 0,
		altChargeSub: 3,
		maxCharge: 0,
		altMaxCharge: 1700,
	},
	weaponData_t {	// WP_BOWCASTER
		//		"Wookiee Bowcaster",		//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_POWERCELL as i32,
		ammoLow: 5,
		energyPerShot: 5,
		fireTime: 1000,
		range: 8192,
		altEnergyPerShot: 5,
		altFireTime: 750,
		altRange: 8192,
		chargeSubTime: 400,
		altChargeSubTime: 0,
		chargeSub: 5,
		altChargeSub: 0,
		maxCharge: 1700,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_REPEATER
		//		"Imperial Heavy Repeater",//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_METAL_BOLTS as i32,
		ammoLow: 5,
		energyPerShot: 1,
		fireTime: 100,
		range: 8192,
		altEnergyPerShot: 15,
		altFireTime: 800,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_DEMP2
		//		"DEMP2",				//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_POWERCELL as i32,
		ammoLow: 5,
		energyPerShot: 8,
		fireTime: 500,
		range: 8192,
		altEnergyPerShot: 6,
		altFireTime: 900,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 250,
		chargeSub: 0,
		altChargeSub: 3,
		maxCharge: 0,
		altMaxCharge: 2100,
	},
	weaponData_t {	// WP_FLECHETTE
		//		"Golan Arms Flechette",	//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_METAL_BOLTS as i32,
		ammoLow: 5,
		energyPerShot: 10,
		fireTime: 700,
		range: 8192,
		altEnergyPerShot: 15,
		altFireTime: 800,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_ROCKET_LAUNCHER
		//		"Merr-Sonn Missile System",	//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_ROCKETS as i32,
		ammoLow: 5,
		energyPerShot: 1,
		fireTime: 900,
		range: 8192,
		altEnergyPerShot: 2,
		altFireTime: 1200,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_THERMAL
		//		"Thermal Detonator",	//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_THERMAL as i32,
		ammoLow: 0,
		energyPerShot: 1,
		fireTime: 800,
		range: 8192,
		altEnergyPerShot: 1,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_TRIP_MINE
		//		"Trip Mine",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_TRIPMINE as i32,
		ammoLow: 0,
		energyPerShot: 1,
		fireTime: 800,
		range: 8192,
		altEnergyPerShot: 1,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_DET_PACK
		//		"Det Pack",				//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_DETPACK as i32,
		ammoLow: 0,
		energyPerShot: 1,
		fireTime: 800,
		range: 8192,
		altEnergyPerShot: 0,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_CONCUSSION
		//		"Concussion Rifle",		//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_METAL_BOLTS as i32,
		ammoLow: 40,
		energyPerShot: 40,
		fireTime: 800,
		range: 8192,
		altEnergyPerShot: 50,
		altFireTime: 1200,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_BRYAR_OLD,
		//		"Bryar Pistol",			//	char	classname[32];		// Spawning name
		ammoIndex: ammo_t::AMMO_BLASTER as i32,
		ammoLow: 15,
		energyPerShot: 2,
		fireTime: 400,
		range: 8192,
		altEnergyPerShot: 2,
		altFireTime: 400,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 200,
		chargeSub: 0,
		altChargeSub: 1,
		maxCharge: 0,
		altMaxCharge: 1500,
	},
	weaponData_t {	// WP_EMPLCACED_GUN
		//		"Emplaced Gun",			//	char	classname[32];		// Spawning name
		ammoIndex: 0,	// /*AMMO_BLASTER*/0,
		ammoLow: 0,	// /*5*/0,
		energyPerShot: 0,	// /*2*/0,
		fireTime: 100,
		range: 8192,
		altEnergyPerShot: 0,	// /*3*/0,
		altFireTime: 100,
		altRange: 8192,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
	weaponData_t {	// WP_TURRET - NOTE NOT ACTUALLY USEABLE BY PLAYER!
		//		"Emplaced Gun",			//	char	classname[32];		// Spawning name
		ammoIndex: 0,	// /*AMMO_BLASTER*/0,
		ammoLow: 0,	// /*5*/0,
		energyPerShot: 0,	// /*2*/0,
		fireTime: 0,
		range: 0,
		altEnergyPerShot: 0,	// /*3*/0,
		altFireTime: 0,
		altRange: 0,
		chargeSubTime: 0,
		altChargeSubTime: 0,
		chargeSub: 0,
		altChargeSub: 0,
		maxCharge: 0,
		altMaxCharge: 0,
	},
];
