#!/usr/bin/env python3
# gen_animcfg.py -- generate the SYNTHETIC animation.cfg fixture for the pmove
# slice from the oracle animTable (cgame/animtable.h). See README "Synthetic
# animation.cfg". This is committed output; rerun only if the anim set changes.
#
# Grammar (oracle BG_ParseAnimationFile, bg_panimate.c:2442-2520):
#   <TOKEN> <firstFrame> <numFrames> <loopFrames> <fps>
# Unknown tokens are skipped; every animTable entry is initialised to
# (0,0,-1,100) before parsing, and BG_SetAnimFinal ASSERTS firstFrame>0 ||
# numFrames>0 on any anim it sets. So we emit EVERY token with a valid frame
# block: the ~40 movement anims the on-foot MELEE path actually plays carry
# hand-tuned, distinct, realistic values (so legsTimer/torsoTimer/bobCycle
# goldens are non-degenerate); every other token carries a uniform filler
# (1 1 -1 20) purely to satisfy the assert -- it is never played on this path.
import re, sys, pathlib

ANIMTABLE = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else \
    pathlib.Path("../../oracle/codemp/cgame/animtable.h")

names = []
for m in re.finditer(r"ENUM2STRING\(([A-Z0-9_]+)\)", ANIMTABLE.read_text()):
    if m.group(1) not in names:
        names.append(m.group(1))

# Hand-tuned movement anims: TOKEN -> (firstFrame, numFrames, loopFrames, fps).
# Values are synthetic but plausible; both dumper and Rust port read this exact
# file, so parity holds regardless of the specific numbers.
MOVEMENT = {
    "BOTH_STAND1":         (0,    1,   -1, 20),   # idle base
    "BOTH_STAND1IDLE1":    (10,   40,   0, 15),
    "BOTH_STAND2":         (60,   1,   -1, 20),
    "BOTH_STAND2TO1":      (70,   8,    0, 20),
    "BOTH_STAND1TO2":      (80,   8,    0, 20),
    "BOTH_STAND4":         (90,   1,   -1, 20),
    "BOTH_WALK1":          (100,  20,   0, 20),
    "BOTH_WALK2":          (130,  20,   0, 20),
    "BOTH_WALKBACK1":      (160,  20,   0, 20),
    "BOTH_WALKBACK2":      (190,  20,   0, 20),
    "BOTH_RUN1":           (220,  16,   0, 25),
    "BOTH_RUN2":           (250,  16,   0, 25),
    "BOTH_RUN1START":      (280,  8,    0, 25),
    "BOTH_RUN1STOP":       (300,  8,    0, 25),
    "BOTH_RUNBACK1":       (320,  16,   0, 25),
    "BOTH_RUNBACK2":       (350,  16,   0, 25),
    "BOTH_JUMP1":          (380,  8,    0, 20),
    "BOTH_INAIR1":         (400,  1,   -1, 20),
    "BOTH_LAND1":          (410,  5,   -1, 20),
    "BOTH_JUMPBACK1":      (420,  8,    0, 20),
    "BOTH_INAIRBACK1":     (430,  1,   -1, 20),
    "BOTH_LANDBACK1":      (440,  5,   -1, 20),
    "BOTH_JUMPLEFT1":      (450,  8,    0, 20),
    "BOTH_INAIRLEFT1":     (460,  1,   -1, 20),
    "BOTH_LANDLEFT1":      (470,  5,   -1, 20),
    "BOTH_JUMPRIGHT1":     (480,  8,    0, 20),
    "BOTH_INAIRRIGHT1":    (490,  1,   -1, 20),
    "BOTH_LANDRIGHT1":     (500,  5,   -1, 20),
    "BOTH_CROUCH1":        (510,  1,   -1, 20),
    "BOTH_CROUCH1IDLE":    (520,  20,   0, 15),
    "BOTH_CROUCH1WALK":    (550,  20,   0, 20),
    "BOTH_CROUCH1WALKBACK":(580,  20,   0, 20),
    "BOTH_GETUP1":         (610,  10,   0, 20),
    "BOTH_ROLL_F":         (620,  12,   0, 25),
    "BOTH_ROLL_B":         (640,  12,   0, 25),
    "BOTH_ROLL_L":         (660,  12,   0, 25),
    "BOTH_ROLL_R":         (680,  12,   0, 25),
    "BOTH_TURNL":          (700,  8,    0, 20),
    "BOTH_TURNR":          (710,  8,    0, 20),
    "BOTH_TURNSTANDL":     (720,  8,    0, 20),
    "BOTH_TURNSTANDR":     (730,  8,    0, 20),
    "TORSO_WEAPONREADY1":  (740,  1,   -1, 20),
    "TORSO_WEAPONREADY3":  (750,  1,   -1, 20),
    "TORSO_DROPWEAP1":     (760,  8,    0, 20),
    "TORSO_RAISEWEAP1":    (770,  8,    0, 20),
    "BOTH_ATTACK4":        (780,  10,   0, 20),
    "BOTH_MELEE1":         (800,  10,   0, 20),
    "BOTH_MELEE2":         (820,  10,   0, 20),
}

FILLER = (1, 1, -1, 20)

out = []
out.append("// SYNTHETIC animation.cfg -- generated by gen_animcfg.py from the")
out.append("// oracle animTable (cgame/animtable.h). NOT a real Raven asset.")
out.append("// Movement anims carry hand-tuned frame blocks; all other tokens")
out.append("// carry filler (1 1 -1 20) to satisfy BG_SetAnimFinal's frame")
out.append("// assert. Both the C dumper and the Rust parity test parse THIS")
out.append("// file, so the specific numbers only need to be deterministic.")
for nm in names:
    ff, nf, lf, fps = MOVEMENT.get(nm, FILLER)
    out.append(f"{nm}\t\t{ff}\t{nf}\t{lf}\t{fps}")

sys.stdout.write("\n".join(out) + "\n")
