// Header-free abort() stubs for every w_saber.c extern *function* NOT on the
// two tested leaf paths (G_SaberLockAnim / G_KnockawayForParry). Compiled
// WITHOUT the game headers, so these argless K&R-style definitions never clash
// with the real prototypes -- the C linker binds by symbol name alone. A firing
// stub means a fixture leaked off the tested path; the abort makes it loud and
// greppable. Generated to match the exact undefined-symbol set left after
// linking main + w_saber + q_shared + q_math.
#include <stdio.h>
#include <stdlib.h>

#define STUB(name) \
	long name() { fprintf(stderr, "wsaber-oracle: STUB " #name " reached -- fixture off the tested path\n"); abort(); return 0; }

STUB(BG_AnimLength)
STUB(BG_BrokenParryForAttack)
STUB(BG_BrokenParryForParry)
STUB(BG_CanUseFPNow)
STUB(BG_CheckIncrementLockAnim)
STUB(BG_EvaluateTrajectory)
STUB(BG_G2ATSTAngles)
STUB(BG_G2PlayerAngles)
STUB(BG_HasYsalamiri)
STUB(BG_IK_MoveArm)
STUB(BG_InExtraDefenseSaberMove)
STUB(BG_InGrappleMove)
STUB(BG_InKnockDown)
STUB(BG_InKnockDownOnGround)
STUB(BG_InRoll)
STUB(BG_InSpecialJump)
STUB(BG_KickingAnim)
STUB(BG_KnockawayForParry)
STUB(BG_KnockDownable)
STUB(BG_SaberInAttack)
STUB(BG_SaberInAttackPure)
STUB(BG_SaberInKata)
STUB(BG_SaberInReturn)
STUB(BG_SaberInSpecial)
STUB(BG_SaberInSpecialAttack)
STUB(BG_SaberInTransitionAny)
STUB(BG_SabersOff)
STUB(BG_SaberStartTransAnim)
STUB(BG_SpinningSaberAnim)
STUB(BG_StabDownAnim)
STUB(BG_SuperBreakLoseAnim)
STUB(BG_SuperBreakWinAnim)
STUB(ForceThrow)
STUB(G_Damage)
STUB(G_EntIsBreakable)
STUB(G_EntitySound)
STUB(G_FreeEntity)
STUB(G_GetBoltPosition)
STUB(G_InitGentity)
STUB(G_Knockdown)
STUB(G_ModelIndex)
STUB(G_RunObject)
STUB(G_SetAnim)
STUB(G_SetEnemy)
STUB(G_SetOrigin)
STUB(G_Sound)
STUB(G_SoundIndex)
STUB(G_Spawn)
STUB(G_TempEntity)
STUB(G_TestLine)
STUB(G_Throw)
STUB(G_UpdateClientAnims)
STUB(InFront)
STUB(Jedi_Ambush)
STUB(Jedi_SaberBlockGo)
STUB(Jedi_WaitingAmbush)
STUB(NPC_SetBoneAngles)
STUB(OnSameTeam)
STUB(PM_InKnockDown)
STUB(PM_InSaberAnim)
STUB(PM_SaberBounceForAttack)
STUB(PM_SaberDeflectionForQuad)
STUB(PM_SaberInBounce)
STUB(PM_SaberInBrokenParry)
STUB(PM_SaberInDeflect)
STUB(PM_SaberInKnockaway)
STUB(PM_SaberInParry)
STUB(PM_SaberInReflect)
STUB(PM_SaberInTransition)
STUB(SetClientViewAngle)
STUB(TIMER_Done)
STUB(TIMER_Set)
STUB(trap_EntitiesInBox)
STUB(trap_G2API_AddBolt)
STUB(trap_G2API_CollisionDetect)
STUB(trap_G2API_CollisionDetectCache)
STUB(trap_G2API_GetBoltMatrix)
STUB(trap_G2API_InitGhoul2Model)
STUB(trap_G2API_OverrideServer)
STUB(trap_G2API_RemoveGhoul2Models)
STUB(trap_G2Trace)
STUB(trap_InPVS)
STUB(trap_LinkEntity)
STUB(trap_Trace)
STUB(tri_tri_intersect)
STUB(vectoyaw)
STUB(WP_ForcePowerUsable)
STUB(WP_SaberBladeDoTransitionDamage)
STUB(WP_SaberBladeUseSecondBladeStyle)
