// Header-free abort() stubs for every g_combat.c extern *function* NOT on the
// three tested leaf paths (RaySphereIntersections / G_GetHitLocation /
// CheckArmor). Compiled WITHOUT the game headers, so these argless K&R-style
// definitions never clash with the real prototypes — the C linker binds by
// symbol name alone. A firing stub means a fixture leaked off the tested path;
// the abort makes it loud and greppable. Generated to match the exact
// undefined-symbol set left after linking main + g_combat + q_shared + q_math.
#include <stdio.h>
#include <stdlib.h>

#define STUB(name) \
	long name() { fprintf(stderr, "gcombat-oracle: STUB " #name " reached -- fixture off the tested path\n"); abort(); return 0; }

STUB(AI_DeleteSelfFromGroup)
STUB(AI_GroupMemberKilled)
STUB(BG_ClearRocketLock)
STUB(BG_FindItemForPowerup)
STUB(BG_FindItemForWeapon)
STUB(BG_FlippingAnim)
STUB(BG_GetItemIndexByTag)
STUB(BG_GetRootSurfNameWithVariant)
STUB(BG_HasAnimation)
STUB(BG_InDeathAnim)
STUB(BG_InRoll)
STUB(BG_KnockDownable)
STUB(BG_PickAnim)
STUB(BlowDetpacks)
STUB(BotDamageNotification)
STUB(CalculateRanks)
STUB(CheckExitRules)
STUB(ClientUserinfoChanged)
STUB(Cmd_Score_f)
STUB(Drop_Item)
STUB(G_ActivateBehavior)
STUB(G_AddEvent)
STUB(G_BreakArm)
STUB(G_CheckTKAutoKickBan)
STUB(G_EffectIndex)
STUB(G_FlyVehicleDestroySurface)
STUB(G_FreeEntity)
STUB(G_LetGoOfWall)
STUB(G_LogPrintf)
STUB(G_LogWeaponDamage)
STUB(G_LogWeaponDeath)
STUB(G_LogWeaponFrag)
STUB(G_LogWeaponKill)
STUB(G_MuteSound)
STUB(G_PlayEffectID)
STUB(G_PreDefSound)
STUB(G_Printf)
STUB(G_RunExPhys)
STUB(G_ScaleNetHealth)
STUB(G_SetAnim)
STUB(G_SetEnemy)
STUB(G_SetOrigin)
STUB(G_ShipSurfaceForSurfName)
STUB(G_Sound)
STUB(G_SoundIndex)
STUB(G_Spawn)
STUB(G_TempEntity)
STUB(G_UpdateClientAnims)
STUB(G_UseTargets)
STUB(G_UseTargets2)
STUB(G_VehicleSetDamageLocFlags)
STUB(G_VehUpdateShields)
STUB(GlobalUse)
STUB(InFOV)
STUB(Jedi_WaitingAmbush)
STUB(Jetpack_Off)
STUB(LaunchItem)
STUB(LogAccuracyHit)
STUB(NPC_ClearLOS2)
STUB(NPC_FreeCombatPoint)
STUB(OnSameTeam)
STUB(Rancor_DropVictim)
STUB(Team_CheckHurtCarrier)
STUB(Team_FragBonuses)
STUB(Team_ReturnFlag)
STUB(ThrowSaberToAttacker)
STUB(TIMER_Clear2)
STUB(TIMER_Set)
STUB(trap_EntitiesInBox)
STUB(trap_G2API_AddBolt)
STUB(trap_G2API_GetBoltMatrix)
STUB(trap_G2API_GetSurfaceName)
STUB(trap_G2API_GetSurfaceRenderStatus)
STUB(trap_G2API_SetSurfaceOnOff)
STUB(trap_InPVS)
STUB(trap_LinkEntity)
STUB(trap_PointContents)
STUB(trap_Trace)
STUB(trap_UnlinkEntity)
STUB(UpdateClientRenderBolts)
STUB(vectoyaw)
