//! FAITHFUL port of Raven `codemp/game/bg_misc.c` item registry, in the
//! idiomatic `GItem` form (DEC-31 g_items slice).
//!
//! `bg_itemlist`/`bg_numItems` are the single bg-owned master item table that
//! `game/g_items.c` and `bg_misc.c` both index by `s.modelindex` ([`ItemId`]);
//! it lives in the bg crate so both mp_bg and jampgame consumers see one
//! definition per the "family resolves together" rule.
//!
//! Source: `oracle/codemp/game/bg_misc.c:795-1771`

#![allow(non_upper_case_globals)]

use core::ffi::{c_int, CStr};

use super::g_item::GItem;
use super::holdable::*;
use super::item_kind::ItemKind;
use super::powerup::*;
use crate::weapons::ammo_t::ammo_t::*;
use crate::weapons::weapon_t::*;

/// Raven `bg_itemlist[]` — master item table. Index 0 is the deliberately
/// blank "leave index 0 alone" sentinel ([`ItemKind::Bad`]); the trailing Raven
/// `{NULL}` end-of-list marker is dropped (C-only, porting-rules §20 — callers
/// bound on `bg_numItems`, never on a null terminator).
///
/// Source: `oracle/codemp/game/bg_misc.c:795-1770`
pub static bg_itemlist: [GItem; 51] = [
    GItem {
        // Raven `{ NULL, NULL, {NULL×4}, NULL, NULL, 0,0,0, "", "", "" }` — the
        // "leave index 0 alone" sentinel (Raven bg_misc.c:797).
        classname: "",
        pickup_sound: None,
        world_model: &[],
        view_model: None,
        icon: None,
        quantity: 0,
        kind: ItemKind::Bad,
        precaches: "",
        sounds: "",
        description: None,
    },
    GItem {
        classname: "item_shield_sm_instant",
        pickup_sound: Some("sound/player/pickupshield.wav"),
        world_model: &["models/map_objects/mp/psd_sm.md3"],
        view_model: None,
        icon: Some("gfx/mp/small_shield"),
        quantity: 25,
        kind: ItemKind::Armor { rating: 1 },
        precaches: "",
        sounds: "",
        // Raven source omits this field (a missing comma after `sounds`
        // concatenates two "" literals) — C zero-inits the rest, so NULL.
        description: None,
    },
    GItem {
        classname: "item_shield_lrg_instant",
        pickup_sound: Some("sound/player/pickupshield.wav"),
        world_model: &["models/map_objects/mp/psd.md3"],
        view_model: None,
        icon: Some("gfx/mp/large_shield"),
        quantity: 100,
        kind: ItemKind::Armor { rating: 2 },
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_medpak_instant",
        pickup_sound: Some("sound/player/pickuphealth.wav"),
        world_model: &["models/map_objects/mp/medpac.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_medkit"),
        quantity: 25,
        kind: ItemKind::Health,
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_seeker",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/remote.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_seeker"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_SEEKER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_AN_ATTACK_DRONE_SIMILAR"),
    },
    GItem {
        classname: "item_shield",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/map_objects/mp/shield.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_shieldwall"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_SHIELD),
        precaches: "",
        sounds: "sound/weapons/detpack/stick.wav sound/movers/doors/forcefield_on.wav sound/movers/doors/forcefield_off.wav sound/movers/doors/forcefield_lp.wav sound/effects/bumpfield.wav",
        description: Some("@MENUS_THIS_STATIONARY_ENERGY"),
    },
    GItem {
        classname: "item_medpac",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/map_objects/mp/bacta.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_bacta"),
        quantity: 25,
        kind: ItemKind::Holdable(HI_MEDPAC),
        precaches: "",
        sounds: "",
        description: Some("@SP_INGAME_BACTA_DESC"),
    },
    GItem {
        classname: "item_medpac_big",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/big_bacta.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_big_bacta"),
        quantity: 25,
        kind: ItemKind::Holdable(HI_MEDPAC_BIG),
        precaches: "",
        sounds: "",
        description: Some("@SP_INGAME_BACTA_DESC"),
    },
    GItem {
        classname: "item_binoculars",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/binoculars.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_zoom"),
        quantity: 60,
        kind: ItemKind::Holdable(HI_BINOCULARS),
        precaches: "",
        sounds: "",
        description: Some("@SP_INGAME_LA_GOGGLES_DESC"),
    },
    GItem {
        classname: "item_sentry_gun",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/psgun.glm"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_sentrygun"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_SENTRY_GUN),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THIS_DEADLY_WEAPON_IS"),
    },
    GItem {
        classname: "item_jetpack",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/psgun.glm"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_jetpack"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_JETPACK),
        precaches: "effects/boba/jet.efx",
        sounds: "sound/chars/boba/JETON.wav sound/chars/boba/JETHOVER.wav sound/effects/fire_lp.wav",
        description: Some("@MENUS_JETPACK_DESC"),
    },
    GItem {
        classname: "item_healthdisp",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/map_objects/mp/bacta.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_healthdisp"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_HEALTHDISP),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_ammodisp",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/map_objects/mp/bacta.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_ammodisp"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_AMMODISP),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_eweb_holdable",
        pickup_sound: Some("sound/interface/shieldcon_empty"),
        world_model: &["models/map_objects/hoth/eweb_model.glm"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_eweb"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_EWEB),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_EWEB_DESC"),
    },
    GItem {
        classname: "item_cloak",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/items/psgun.glm"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_cloak"),
        quantity: 120,
        kind: ItemKind::Holdable(HI_CLOAK),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_CLOAK_DESC"),
    },
    GItem {
        classname: "item_force_enlighten_light",
        pickup_sound: Some("sound/player/enlightenment.wav"),
        world_model: &["models/map_objects/mp/jedi_enlightenment.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_jlight"),
        quantity: 25,
        kind: ItemKind::Powerup(PW_FORCE_ENLIGHTENED_LIGHT),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_force_enlighten_dark",
        pickup_sound: Some("sound/player/enlightenment.wav"),
        world_model: &["models/map_objects/mp/dk_enlightenment.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_dklight"),
        quantity: 25,
        kind: ItemKind::Powerup(PW_FORCE_ENLIGHTENED_DARK),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_force_boon",
        pickup_sound: Some("sound/player/boon.wav"),
        world_model: &["models/map_objects/mp/force_boon.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_fboon"),
        quantity: 25,
        kind: ItemKind::Powerup(PW_FORCE_BOON),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_ysalimari",
        pickup_sound: Some("sound/player/ysalimari.wav"),
        world_model: &["models/map_objects/mp/ysalimari.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_ysamari"),
        quantity: 25,
        kind: ItemKind::Powerup(PW_YSALAMIRI),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "weapon_stun_baton",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/stun_baton/baton_w.glm"],
        view_model: Some("models/weapons2/stun_baton/baton.md3"),
        icon: Some("gfx/hud/w_icon_stunbaton"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_STUN_BATON),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "weapon_melee",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/stun_baton/baton_w.glm"],
        view_model: Some("models/weapons2/stun_baton/baton.md3"),
        icon: Some("gfx/hud/w_icon_melee"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_MELEE),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_MELEE_DESC"),
    },
    GItem {
        classname: "weapon_saber",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/saber/saber_w.glm"],
        view_model: Some("models/weapons2/saber/saber_w.md3"),
        icon: Some("gfx/hud/w_icon_lightsaber"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_SABER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_AN_ELEGANT_WEAPON_FOR"),
    },
    GItem {
        classname: "weapon_blaster_pistol",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/blaster_pistol/blaster_pistol_w.glm"],
        view_model: Some("models/weapons2/blaster_pistol/blaster_pistol.md3"),
        icon: Some("gfx/hud/w_icon_blaster_pistol"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_BRYAR_PISTOL),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_BLASTER_PISTOL_DESC"),
    },
    GItem {
        classname: "weapon_concussion_rifle",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/concussion/c_rifle_w.glm"],
        view_model: Some("models/weapons2/concussion/c_rifle.md3"),
        icon: Some("gfx/hud/w_icon_c_rifle"),
        quantity: 50,
        kind: ItemKind::Weapon(WP_CONCUSSION),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_CONC_RIFLE_DESC"),
    },
    GItem {
        classname: "weapon_bryar_pistol",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/briar_pistol/briar_pistol_w.glm"],
        view_model: Some("models/weapons2/briar_pistol/briar_pistol.md3"),
        icon: Some("gfx/hud/w_icon_briar"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_BRYAR_OLD),
        precaches: "",
        sounds: "",
        description: Some("@SP_INGAME_BLASTER_PISTOL"),
    },
    GItem {
        classname: "weapon_blaster",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/blaster_r/blaster_w.glm"],
        view_model: Some("models/weapons2/blaster_r/blaster.md3"),
        icon: Some("gfx/hud/w_icon_blaster"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_BLASTER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THE_PRIMARY_WEAPON_OF"),
    },
    GItem {
        classname: "weapon_disruptor",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/disruptor/disruptor_w.glm"],
        view_model: Some("models/weapons2/disruptor/disruptor.md3"),
        icon: Some("gfx/hud/w_icon_disruptor"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_DISRUPTOR),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THIS_NEFARIOUS_WEAPON"),
    },
    GItem {
        classname: "weapon_bowcaster",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/bowcaster/bowcaster_w.glm"],
        view_model: Some("models/weapons2/bowcaster/bowcaster.md3"),
        icon: Some("gfx/hud/w_icon_bowcaster"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_BOWCASTER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THIS_ARCHAIC_LOOKING"),
    },
    GItem {
        classname: "weapon_repeater",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/heavy_repeater/heavy_repeater_w.glm"],
        view_model: Some("models/weapons2/heavy_repeater/heavy_repeater.md3"),
        icon: Some("gfx/hud/w_icon_repeater"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_REPEATER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THIS_DESTRUCTIVE_PROJECTILE"),
    },
    GItem {
        classname: "weapon_demp2",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/demp2/demp2_w.glm"],
        view_model: Some("models/weapons2/demp2/demp2.md3"),
        icon: Some("gfx/hud/w_icon_demp2"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_DEMP2),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_COMMONLY_REFERRED_TO"),
    },
    GItem {
        classname: "weapon_flechette",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/golan_arms/golan_arms_w.glm"],
        view_model: Some("models/weapons2/golan_arms/golan_arms.md3"),
        icon: Some("gfx/hud/w_icon_flechette"),
        quantity: 100,
        kind: ItemKind::Weapon(WP_FLECHETTE),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_WIDELY_USED_BY_THE_CORPORATE"),
    },
    GItem {
        classname: "weapon_rocket_launcher",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/merr_sonn/merr_sonn_w.glm"],
        view_model: Some("models/weapons2/merr_sonn/merr_sonn.md3"),
        icon: Some("gfx/hud/w_icon_merrsonn"),
        quantity: 3,
        kind: ItemKind::Weapon(WP_ROCKET_LAUNCHER),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THE_PLX_2M_IS_AN_EXTREMELY"),
    },
    GItem {
        classname: "ammo_thermal",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/thermal/thermal_pu.md3", "models/weapons2/thermal/thermal_w.glm"],
        view_model: Some("models/weapons2/thermal/thermal.md3"),
        icon: Some("gfx/hud/w_icon_thermal"),
        quantity: 4,
        kind: ItemKind::Ammo(AMMO_THERMAL as c_int),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THE_THERMAL_DETONATOR"),
    },
    GItem {
        classname: "ammo_tripmine",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/laser_trap/laser_trap_pu.md3", "models/weapons2/laser_trap/laser_trap_w.glm"],
        view_model: Some("models/weapons2/laser_trap/laser_trap.md3"),
        icon: Some("gfx/hud/w_icon_tripmine"),
        quantity: 3,
        kind: ItemKind::Ammo(AMMO_TRIPMINE as c_int),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_TRIP_MINES_CONSIST_OF"),
    },
    GItem {
        classname: "ammo_detpack",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/detpack/det_pack_pu.md3", "models/weapons2/detpack/det_pack_proj.glm", "models/weapons2/detpack/det_pack_w.glm"],
        view_model: Some("models/weapons2/detpack/det_pack.md3"),
        icon: Some("gfx/hud/w_icon_detpack"),
        quantity: 3,
        kind: ItemKind::Ammo(AMMO_DETPACK as c_int),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_A_DETONATION_PACK_IS"),
    },
    GItem {
        classname: "weapon_thermal",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/thermal/thermal_w.glm", "models/weapons2/thermal/thermal_pu.md3"],
        view_model: Some("models/weapons2/thermal/thermal.md3"),
        icon: Some("gfx/hud/w_icon_thermal"),
        quantity: 4,
        kind: ItemKind::Weapon(WP_THERMAL),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_THE_THERMAL_DETONATOR"),
    },
    GItem {
        classname: "weapon_trip_mine",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/laser_trap/laser_trap_w.glm", "models/weapons2/laser_trap/laser_trap_pu.md3"],
        view_model: Some("models/weapons2/laser_trap/laser_trap.md3"),
        icon: Some("gfx/hud/w_icon_tripmine"),
        quantity: 3,
        kind: ItemKind::Weapon(WP_TRIP_MINE),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_TRIP_MINES_CONSIST_OF"),
    },
    GItem {
        classname: "weapon_det_pack",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/detpack/det_pack_proj.glm", "models/weapons2/detpack/det_pack_pu.md3", "models/weapons2/detpack/det_pack_w.glm"],
        view_model: Some("models/weapons2/detpack/det_pack.md3"),
        icon: Some("gfx/hud/w_icon_detpack"),
        quantity: 3,
        kind: ItemKind::Weapon(WP_DET_PACK),
        precaches: "",
        sounds: "",
        description: Some("@MENUS_A_DETONATION_PACK_IS"),
    },
    GItem {
        classname: "weapon_emplaced",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/blaster_r/blaster_w.glm"],
        view_model: Some("models/weapons2/blaster_r/blaster.md3"),
        icon: Some("gfx/hud/w_icon_blaster"),
        quantity: 50,
        kind: ItemKind::Weapon(WP_EMPLACED_GUN),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "weapon_turretwp",
        pickup_sound: Some("sound/weapons/w_pkup.wav"),
        world_model: &["models/weapons2/blaster_r/blaster_w.glm"],
        view_model: Some("models/weapons2/blaster_r/blaster.md3"),
        icon: Some("gfx/hud/w_icon_blaster"),
        quantity: 50,
        kind: ItemKind::Weapon(WP_TURRET),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_force",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/energy_cell.md3"],
        view_model: None,
        icon: Some("gfx/hud/w_icon_blaster"),
        quantity: 100,
        kind: ItemKind::Ammo(AMMO_FORCE as c_int),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_blaster",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/energy_cell.md3"],
        view_model: None,
        icon: Some("gfx/hud/i_icon_battery"),
        quantity: 100,
        kind: ItemKind::Ammo(AMMO_BLASTER as c_int),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_powercell",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/power_cell.md3"],
        view_model: None,
        icon: Some("gfx/mp/ammo_power_cell"),
        quantity: 100,
        kind: ItemKind::Ammo(AMMO_POWERCELL as c_int),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_metallic_bolts",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/metallic_bolts.md3"],
        view_model: None,
        icon: Some("gfx/mp/ammo_metallic_bolts"),
        quantity: 100,
        kind: ItemKind::Ammo(AMMO_METAL_BOLTS as c_int),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_rockets",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/rockets.md3"],
        view_model: None,
        icon: Some("gfx/mp/ammo_rockets"),
        quantity: 3,
        kind: ItemKind::Ammo(AMMO_ROCKETS as c_int),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "ammo_all",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/items/battery.md3"],
        view_model: None,
        icon: Some("gfx/mp/ammo_rockets"),
        quantity: 0,
        // `ammo_all` — Raven giTag `-1`: the give-all dispenser refill.
        kind: ItemKind::Ammo(-1),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "team_CTF_redflag",
        pickup_sound: None,
        world_model: &["models/flags/r_flag.md3", "models/flags/r_flag_ysal.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_rflag"),
        quantity: 0,
        kind: ItemKind::Team(PW_REDFLAG),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "team_CTF_blueflag",
        pickup_sound: None,
        world_model: &["models/flags/b_flag.md3", "models/flags/b_flag_ysal.md3"],
        view_model: None,
        icon: Some("gfx/hud/mpi_bflag"),
        quantity: 0,
        kind: ItemKind::Team(PW_BLUEFLAG),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "team_CTF_neutralflag",
        pickup_sound: None,
        world_model: &["models/flags/n_flag.md3"],
        view_model: None,
        icon: Some("icons/iconf_neutral1"),
        quantity: 0,
        kind: ItemKind::Team(PW_NEUTRALFLAG),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_redcube",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/powerups/orb/r_orb.md3"],
        view_model: None,
        icon: Some("icons/iconh_rorb"),
        quantity: 0,
        kind: ItemKind::Team(0),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
    GItem {
        classname: "item_bluecube",
        pickup_sound: Some("sound/player/pickupenergy.wav"),
        world_model: &["models/powerups/orb/b_orb.md3"],
        view_model: None,
        icon: Some("icons/iconh_borb"),
        quantity: 0,
        kind: ItemKind::Team(0),
        precaches: "",
        sounds: "",
        description: Some(""),
    },
];

/// Raven `bg_numItems` — the count the Raven `ARRAY_LEN(bg_itemlist) - 1` formula
/// yielded (it excluded the trailing `{NULL}` marker). With that marker dropped,
/// `bg_itemlist.len()` is the same value (51), keeping the CS_ITEMS
/// registered-items configstring length byte-identical.
///
/// Source: `oracle/codemp/game/bg_misc.c:1771`
pub const bg_numItems: c_int = bg_itemlist.len() as c_int;

/// Companion C-string classnames, parallel to [`bg_itemlist`]. Bridge for the
/// `gentity_t::classname` (`*mut c_char`) field, which still takes the item
/// classname pointer this slice; retires when that field flips. Kept in lockstep
/// with the `classname` above (same source order).
pub static ITEM_CLASSNAMES_C: [&CStr; 51] = [
    c"",
    c"item_shield_sm_instant",
    c"item_shield_lrg_instant",
    c"item_medpak_instant",
    c"item_seeker",
    c"item_shield",
    c"item_medpac",
    c"item_medpac_big",
    c"item_binoculars",
    c"item_sentry_gun",
    c"item_jetpack",
    c"item_healthdisp",
    c"item_ammodisp",
    c"item_eweb_holdable",
    c"item_cloak",
    c"item_force_enlighten_light",
    c"item_force_enlighten_dark",
    c"item_force_boon",
    c"item_ysalimari",
    c"weapon_stun_baton",
    c"weapon_melee",
    c"weapon_saber",
    c"weapon_blaster_pistol",
    c"weapon_concussion_rifle",
    c"weapon_bryar_pistol",
    c"weapon_blaster",
    c"weapon_disruptor",
    c"weapon_bowcaster",
    c"weapon_repeater",
    c"weapon_demp2",
    c"weapon_flechette",
    c"weapon_rocket_launcher",
    c"ammo_thermal",
    c"ammo_tripmine",
    c"ammo_detpack",
    c"weapon_thermal",
    c"weapon_trip_mine",
    c"weapon_det_pack",
    c"weapon_emplaced",
    c"weapon_turretwp",
    c"ammo_force",
    c"ammo_blaster",
    c"ammo_powercell",
    c"ammo_metallic_bolts",
    c"ammo_rockets",
    c"ammo_all",
    c"team_CTF_redflag",
    c"team_CTF_blueflag",
    c"team_CTF_neutralflag",
    c"item_redcube",
    c"item_bluecube",
];

#[cfg(test)]
mod item_classnames_c_tests {
    use super::{bg_itemlist, ITEM_CLASSNAMES_C};

    /// The C-string companion table must mirror `bg_itemlist`'s classnames
    /// slot-for-slot (it exists only to feed the still-raw
    /// `gentity_t::classname`; retires when that field flips).
    #[test]
    fn companion_table_matches_itemlist() {
        assert_eq!(bg_itemlist.len(), ITEM_CLASSNAMES_C.len());
        for (i, (it, c)) in bg_itemlist.iter().zip(ITEM_CLASSNAMES_C).enumerate() {
            assert_eq!(
                it.classname,
                c.to_str().unwrap(),
                "classname mismatch at slot {i}"
            );
        }
    }
}
