//! FAITHFUL port of Raven `codemp/game/bg_misc.c` item registry.
//!
//! `bg_itemlist`/`bg_numItems` are the single bg-owned master item table that
//! `game/g_items.c` and `bg_misc.c` both index by pointer arithmetic
//! (`item - bg_itemlist`); moved here (bg crate) so both mp_bg and jampgame
//! consumers see one definition per the "family resolves together" rule.
//!
//! Source: `oracle/codemp/game/bg_misc.c:795-1771`

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals)]

use core::ffi::{c_char, c_int};

use super::holdable::*;
use super::item_type::*;
use super::powerup::*;
use crate::weapons::ammo_t::ammo_t::*;
use crate::weapons::weapon_t::*;
use mp_qshared::common::mp::qcommon::game_item::gitem_t;

/// Raven `bg_itemlist[]` — master item table (index 0 is a deliberately blank
/// "leave index 0 alone" sentinel per the Raven comment; last entry is the
/// Raven `{NULL}` end-of-list marker).
///
/// Source: `oracle/codemp/game/bg_misc.c:795-1770`
pub static bg_itemlist: [gitem_t; 52] = [
    gitem_t {
        classname: core::ptr::null_mut(),
        pickup_sound: core::ptr::null_mut(),
        world_model: [core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: core::ptr::null_mut(),
        quantity: 0,
        giType: 0,
        giTag: 0,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_shield_sm_instant".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupshield.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/psd_sm.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/small_shield".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_ARMOR,
        giTag: 1,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: core::ptr::null_mut(), // source omits this field (missing comma after `sounds` concatenates two "" literals) — C zero-inits the rest
    },
    gitem_t {
        classname: c"item_shield_lrg_instant".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupshield.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/psd.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/large_shield".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_ARMOR,
        giTag: 2,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_medpak_instant".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickuphealth.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/medpac.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_medkit".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_HEALTH,
        giTag: 0,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_seeker".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/remote.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_seeker".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_SEEKER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_AN_ATTACK_DRONE_SIMILAR".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_shield".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/shield.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_shieldwall".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_SHIELD,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"sound/weapons/detpack/stick.wav sound/movers/doors/forcefield_on.wav sound/movers/doors/forcefield_off.wav sound/movers/doors/forcefield_lp.wav sound/effects/bumpfield.wav".as_ptr() as *mut c_char,
        description: c"@MENUS_THIS_STATIONARY_ENERGY".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_medpac".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/bacta.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_bacta".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_HOLDABLE,
        giTag: HI_MEDPAC,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@SP_INGAME_BACTA_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_medpac_big".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/big_bacta.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_big_bacta".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_HOLDABLE,
        giTag: HI_MEDPAC_BIG,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@SP_INGAME_BACTA_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_binoculars".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/binoculars.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_zoom".as_ptr() as *mut c_char,
        quantity: 60,
        giType: IT_HOLDABLE,
        giTag: HI_BINOCULARS,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@SP_INGAME_LA_GOGGLES_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_sentry_gun".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/psgun.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_sentrygun".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_SENTRY_GUN,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THIS_DEADLY_WEAPON_IS".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_jetpack".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/psgun.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_jetpack".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_JETPACK,
        precaches: c"effects/boba/jet.efx".as_ptr() as *mut c_char,
        sounds: c"sound/chars/boba/JETON.wav sound/chars/boba/JETHOVER.wav sound/effects/fire_lp.wav".as_ptr() as *mut c_char,
        description: c"@MENUS_JETPACK_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_healthdisp".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/bacta.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_healthdisp".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_HEALTHDISP,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_ammodisp".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/bacta.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_ammodisp".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_AMMODISP,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_eweb_holdable".as_ptr() as *mut c_char,
        pickup_sound: c"sound/interface/shieldcon_empty".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/hoth/eweb_model.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_eweb".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_EWEB,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_EWEB_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_cloak".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/psgun.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_cloak".as_ptr() as *mut c_char,
        quantity: 120,
        giType: IT_HOLDABLE,
        giTag: HI_CLOAK,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_CLOAK_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_force_enlighten_light".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/enlightenment.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/jedi_enlightenment.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_jlight".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_POWERUP,
        giTag: PW_FORCE_ENLIGHTENED_LIGHT,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_force_enlighten_dark".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/enlightenment.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/dk_enlightenment.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_dklight".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_POWERUP,
        giTag: PW_FORCE_ENLIGHTENED_DARK,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_force_boon".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/boon.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/force_boon.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_fboon".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_POWERUP,
        giTag: PW_FORCE_BOON,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_ysalimari".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/ysalimari.wav".as_ptr() as *mut c_char,
        world_model: [c"models/map_objects/mp/ysalimari.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_ysamari".as_ptr() as *mut c_char,
        quantity: 25,
        giType: IT_POWERUP,
        giTag: PW_YSALAMIRI,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_stun_baton".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/stun_baton/baton_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/stun_baton/baton.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_stunbaton".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_STUN_BATON,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_melee".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/stun_baton/baton_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/stun_baton/baton.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_melee".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_MELEE,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_MELEE_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_saber".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/saber/saber_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/saber/saber_w.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_lightsaber".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_SABER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_AN_ELEGANT_WEAPON_FOR".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_blaster_pistol".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/blaster_pistol/blaster_pistol_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/blaster_pistol/blaster_pistol.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_blaster_pistol".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_BRYAR_PISTOL,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_BLASTER_PISTOL_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_concussion_rifle".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/concussion/c_rifle_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/concussion/c_rifle.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_c_rifle".as_ptr() as *mut c_char,
        quantity: 50,
        giType: IT_WEAPON,
        giTag: WP_CONCUSSION,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_CONC_RIFLE_DESC".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_bryar_pistol".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/briar_pistol/briar_pistol_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/briar_pistol/briar_pistol.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_briar".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_BRYAR_OLD,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@SP_INGAME_BLASTER_PISTOL".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_blaster".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/blaster_r/blaster_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/blaster_r/blaster.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_blaster".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_BLASTER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THE_PRIMARY_WEAPON_OF".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_disruptor".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/disruptor/disruptor_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/disruptor/disruptor.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_disruptor".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_DISRUPTOR,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THIS_NEFARIOUS_WEAPON".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_bowcaster".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/bowcaster/bowcaster_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/bowcaster/bowcaster.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_bowcaster".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_BOWCASTER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THIS_ARCHAIC_LOOKING".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_repeater".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/heavy_repeater/heavy_repeater_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/heavy_repeater/heavy_repeater.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_repeater".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_REPEATER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THIS_DESTRUCTIVE_PROJECTILE".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_demp2".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/demp2/demp2_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/demp2/demp2.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_demp2".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_DEMP2,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_COMMONLY_REFERRED_TO".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_flechette".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/golan_arms/golan_arms_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/golan_arms/golan_arms.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_flechette".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_WEAPON,
        giTag: WP_FLECHETTE,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_WIDELY_USED_BY_THE_CORPORATE".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_rocket_launcher".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/merr_sonn/merr_sonn_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/merr_sonn/merr_sonn.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_merrsonn".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_WEAPON,
        giTag: WP_ROCKET_LAUNCHER,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THE_PLX_2M_IS_AN_EXTREMELY".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_thermal".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/thermal/thermal_pu.md3".as_ptr() as *mut c_char, c"models/weapons2/thermal/thermal_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/thermal/thermal.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_thermal".as_ptr() as *mut c_char,
        quantity: 4,
        giType: IT_AMMO,
        giTag: AMMO_THERMAL as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THE_THERMAL_DETONATOR".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_tripmine".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/laser_trap/laser_trap_pu.md3".as_ptr() as *mut c_char, c"models/weapons2/laser_trap/laser_trap_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/laser_trap/laser_trap.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_tripmine".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_AMMO,
        giTag: AMMO_TRIPMINE as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_TRIP_MINES_CONSIST_OF".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_detpack".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/detpack/det_pack_pu.md3".as_ptr() as *mut c_char, c"models/weapons2/detpack/det_pack_proj.glm".as_ptr() as *mut c_char, c"models/weapons2/detpack/det_pack_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut()],
        view_model: c"models/weapons2/detpack/det_pack.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_detpack".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_AMMO,
        giTag: AMMO_DETPACK as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_A_DETONATION_PACK_IS".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_thermal".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/thermal/thermal_w.glm".as_ptr() as *mut c_char, c"models/weapons2/thermal/thermal_pu.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/thermal/thermal.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_thermal".as_ptr() as *mut c_char,
        quantity: 4,
        giType: IT_WEAPON,
        giTag: WP_THERMAL,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_THE_THERMAL_DETONATOR".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_trip_mine".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/laser_trap/laser_trap_w.glm".as_ptr() as *mut c_char, c"models/weapons2/laser_trap/laser_trap_pu.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/laser_trap/laser_trap.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_tripmine".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_WEAPON,
        giTag: WP_TRIP_MINE,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_TRIP_MINES_CONSIST_OF".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_det_pack".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/detpack/det_pack_proj.glm".as_ptr() as *mut c_char, c"models/weapons2/detpack/det_pack_pu.md3".as_ptr() as *mut c_char, c"models/weapons2/detpack/det_pack_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut()],
        view_model: c"models/weapons2/detpack/det_pack.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_detpack".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_WEAPON,
        giTag: WP_DET_PACK,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"@MENUS_A_DETONATION_PACK_IS".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_emplaced".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/blaster_r/blaster_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/blaster_r/blaster.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_blaster".as_ptr() as *mut c_char,
        quantity: 50,
        giType: IT_WEAPON,
        giTag: WP_EMPLACED_GUN,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"weapon_turretwp".as_ptr() as *mut c_char,
        pickup_sound: c"sound/weapons/w_pkup.wav".as_ptr() as *mut c_char,
        world_model: [c"models/weapons2/blaster_r/blaster_w.glm".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: c"models/weapons2/blaster_r/blaster.md3".as_ptr() as *mut c_char,
        icon: c"gfx/hud/w_icon_blaster".as_ptr() as *mut c_char,
        quantity: 50,
        giType: IT_WEAPON,
        giTag: WP_TURRET,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_force".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/energy_cell.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/w_icon_blaster".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_AMMO,
        giTag: AMMO_FORCE as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_blaster".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/energy_cell.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/i_icon_battery".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_AMMO,
        giTag: AMMO_BLASTER as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_powercell".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/power_cell.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/ammo_power_cell".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_AMMO,
        giTag: AMMO_POWERCELL as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_metallic_bolts".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/metallic_bolts.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/ammo_metallic_bolts".as_ptr() as *mut c_char,
        quantity: 100,
        giType: IT_AMMO,
        giTag: AMMO_METAL_BOLTS as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_rockets".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/rockets.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/ammo_rockets".as_ptr() as *mut c_char,
        quantity: 3,
        giType: IT_AMMO,
        giTag: AMMO_ROCKETS as c_int,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"ammo_all".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/items/battery.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/mp/ammo_rockets".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_AMMO,
        giTag: -1,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"team_CTF_redflag".as_ptr() as *mut c_char,
        pickup_sound: core::ptr::null_mut(),
        world_model: [c"models/flags/r_flag.md3".as_ptr() as *mut c_char, c"models/flags/r_flag_ysal.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_rflag".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_TEAM,
        giTag: PW_REDFLAG,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"team_CTF_blueflag".as_ptr() as *mut c_char,
        pickup_sound: core::ptr::null_mut(),
        world_model: [c"models/flags/b_flag.md3".as_ptr() as *mut c_char, c"models/flags/b_flag_ysal.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"gfx/hud/mpi_bflag".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_TEAM,
        giTag: PW_BLUEFLAG,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"team_CTF_neutralflag".as_ptr() as *mut c_char,
        pickup_sound: core::ptr::null_mut(),
        world_model: [c"models/flags/n_flag.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"icons/iconf_neutral1".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_TEAM,
        giTag: PW_NEUTRALFLAG,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_redcube".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/powerups/orb/r_orb.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"icons/iconh_rorb".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_TEAM,
        giTag: 0,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    gitem_t {
        classname: c"item_bluecube".as_ptr() as *mut c_char,
        pickup_sound: c"sound/player/pickupenergy.wav".as_ptr() as *mut c_char,
        world_model: [c"models/powerups/orb/b_orb.md3".as_ptr() as *mut c_char, core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: c"icons/iconh_borb".as_ptr() as *mut c_char,
        quantity: 0,
        giType: IT_TEAM,
        giTag: 0,
        precaches: c"".as_ptr() as *mut c_char,
        sounds: c"".as_ptr() as *mut c_char,
        description: c"".as_ptr() as *mut c_char,
    },
    // end of list marker
    gitem_t {
        classname: core::ptr::null_mut(),
        pickup_sound: core::ptr::null_mut(),
        world_model: [core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut(), core::ptr::null_mut()],
        view_model: core::ptr::null_mut(),
        icon: core::ptr::null_mut(),
        quantity: 0,
        giType: 0,
        giTag: 0,
        precaches: core::ptr::null_mut(),
        sounds: core::ptr::null_mut(),
        description: core::ptr::null_mut(),
    },
];

/// Raven `bg_numItems` = `sizeof(bg_itemlist) / sizeof(bg_itemlist[0]) - 1`
/// (excludes the trailing `{NULL}` end-of-list marker).
///
/// Source: `oracle/codemp/game/bg_misc.c:1771`
pub const bg_numItems: c_int = (bg_itemlist.len() - 1) as c_int;
